set PROJECT_PATH=%~dp0
cmake -DDEBUG=1 -DCMAKE_BUILD_TYPE=Debug "-DCMAKE_C_COMPILER=%COMPILER_PATH%" "-DCMAKE_CXX_COMPILER=%COMPILER_PATH%" "-DCMAKE_MAKE_PROGRAM=%NINJA_PATH%" -G Ninja -S %PROJECT_PATH% -B %PROJECT_PATH%debug
pause