xpe::render::cShaderManager
unordered_map< string, sShaderStage > * xpe::render::cShaderManager::s_Stages
cShader * xpe::render::cShaderManager::s_ComputeShaders
cShader * xpe::render::cShaderManager::s_PrepassShaders
cShader * xpe::render::cShaderManager::s_OpaqueShaders
cShader * xpe::render::cShaderManager::s_TransparentShaders
cShader * xpe::render::cShaderManager::s_PostfxShaders
cShader * xpe::render::cShaderManager::s_UiShaders
cShader * xpe::render::cShaderManager::s_FinalShaders
void xpe::render::cShaderManager::Init()
References xpe::core::cFileManager::CreateDir, LogInfo.
void xpe::render::cShaderManager::Free()
References LogInfo.
sShaderStage * xpe::render::cShaderManager::GetFromFile(const sShaderStage::eType &type, const char *filepath)
References GetFromSrc, xpe::core::cFileManager::ReadFileWithIncludes.
Referenced by xpe::render::cCanvas::cCanvas, xpe::render::cCompositeTransparentShader::cCompositeTransparentShader, xpe::render::cDirectionalShadowShader::cDirectionalShadowShader, xpe::render::cFinalShader::cFinalShader, xpe::render::cOpaqueShader::cOpaqueShader, xpe::render::cPointShadowShader::cPointShadowShader, xpe::render::cSkyboxShader::cSkyboxShader, xpe::render::cSpotShadowShader::cSpotShadowShader, xpe::render::cSsaoShader::cSsaoShader, xpe::render::cTextShader::cTextShader, xpe::render::cTransparentShader::cTransparentShader, xpe::render::cWidgetShader::cWidgetShader.
sShaderStage * xpe::render::cShaderManager::GetFromSrc(const sShaderStage::eType &type, const string &id, const string &src)
References xpe::render::context::CompileShaderStage, xpe::render::sShaderStage::COMPUTE, xpe::render::context::CreateShaderStage, xpe::render::sShaderStage::GEOMETRY, xpe::core::Hash, K_ENTRY_POINT_COMPUTE, K_ENTRY_POINT_GEOMETRY, K_ENTRY_POINT_PIXEL, K_ENTRY_POINT_VERTEX, K_PROFILE_COMPUTE, K_PROFILE_GEOMETRY, K_PROFILE_PIXEL, K_PROFILE_VERTEX, LogError, xpe::render::sShaderStage::PIXEL, xpe::render::sShaderStage::VERTEX.
Referenced by GetFromFile.
void xpe::render::cShaderManager::SetShader(cShader *shader)
References xpe::render::cShader::COMPUTE, xpe::render::cShader::FINAL, xpe::render::cShader::OPAQUE, xpe::render::cShader::POSTFX, xpe::render::cShader::PREPASS, SetShader, xpe::render::cShader::TRANSPARENT, xpe::render::cShader::UI.
Referenced by xpe::render::cCanvas::cCanvas, xpe::core::cApp::InitShaders, SetShader, SetShaderAfter.
void xpe::render::cShaderManager::SetShaderAfter(cShader *shader, const string &name)
References xpe::render::cShader::COMPUTE, xpe::render::cShader::FINAL, xpe::core::Hash, xpe::render::cShader::OPAQUE, xpe::render::cShader::POSTFX, xpe::render::cShader::PREPASS, SetShader, xpe::render::cShader::TRANSPARENT, xpe::render::cShader::UI.
cShader * xpe::render::cShaderManager::GetShaders(cShader::eCategory category)
References xpe::render::cShader::COMPUTE, xpe::render::cShader::FINAL, xpe::render::cShader::NONE, xpe::render::cShader::OPAQUE, xpe::render::cShader::POSTFX, xpe::render::cShader::PREPASS, xpe::render::cShader::TRANSPARENT, xpe::render::cShader::UI.
cShader * xpe::render::cShaderManager::GetShader(const string &name)
References GetShader, xpe::core::Hash.
Referenced by GetShader, xpe::core::cApp::InitShaders.
void xpe::render::cShaderManager::ReloadStage(const char *filepath)
References xpe::render::context::CreateShaderStage, xpe::render::context::FreeShaderStage, LogError, xpe::core::cFileManager::ReadFileWithIncludes.
void xpe::render::cShaderManager::FreeStages()
void xpe::render::cShaderManager::WriteGeneratedShader(const char *filepath, const string &src)
void xpe::render::cShaderManager::SetShader(cShader *&dest, cShader *src)
void xpe::render::cShaderManager::SetShader(cShader *&dest, cShader *src, u64 id)
cShader * xpe::render::cShaderManager::GetShader(cShader *&src, u64 id)