xpe::core::cTaskManager
cTaskDispatcher * xpe::core::cTaskManager::s_AudioDispatcher
cTaskDispatcher * xpe::core::cTaskManager::s_NetworkDispatcher
cSimulationDispatcher * xpe::core::cTaskManager::s_SimulationDispatcher
cTaskDispatcher * xpe::core::cTaskManager::s_ThreadPoolDispatcher
void xpe::core::cTaskManager::Init()
References xpe::core::cHardwareManager::CPU, xpe::core::cThread::NORMAL.
Referenced by xpe::core::cApp::Run.
void xpe::core::cTaskManager::Free()
Referenced by xpe::core::cApp::Run.
void xpe::core::cTaskManager::SubmitTask(const sTask &task)
References xpe::core::sTask::ANIMATION, xpe::core::sTask::AUDIO, xpe::core::cTaskDispatcher::Dispatch, xpe::core::sTask::NETWORK, xpe::core::sTask::PHYSICS, xpe::core::sTask::THREAD_POOL.
Referenced by xpe::core::cApp::Run.
void xpe::core::cTaskManager::SubmitTask(u32 tasksPerThread, u32 totalTasks, const sTask &task)
References xpe::core::sTask::ANIMATION, xpe::core::sTask::AUDIO, xpe::core::cTaskDispatcher::Dispatch, xpe::core::sTask::NETWORK, xpe::core::sTask::PHYSICS, xpe::core::sTask::THREAD_POOL.
cSimulationDispatcher * xpe::core::cTaskManager::GetSimulationDispatcher()
Referenced by xpe::core::cApp::Run.