xpe::render::cInstancingShader
sInstanceBuffer xpe::render::cInstancingShader::m_InstanceBuffer
Referenced by cInstancingShader, DrawInstanced.
xpe::render::cInstancingShader::cInstancingShader(eCategory category, const string &name)
References m_InstanceBuffer, xpe::render::sListBuffer< T >::Reserve.
void xpe::render::cInstancingShader::DrawInstanced(cScene *scene, const sGeometryInfo &geometryInfo, const std::function< void(EntityID entityId, sRenderInstance &)> &callback=[](EntityID, sRenderInstance &) {})
References xpe::render::sListBuffer< T >::Add, xpe::render::context::BindPrimitiveTopology, xpe::render::sListBuffer< T >::Clear, xpe::render::context::DrawIndexed, xpe::render::context::DrawVertexed, xpe::render::sListBuffer< T >::Flush, m_InstanceBuffer, xpe::render::sRenderInstance::ModelMatrix, xpe::math::cMathManager::UpdateModelMatrix, xpe::math::cMathManager::UpdateNormalMatrix, xpe::render::context::VSBindBuffer, xpe::render::context::VSUnbindBuffer.
Referenced by xpe::render::cOpaqueShader::Draw, xpe::render::cTransparentShader::Draw, xpe::render::cShadowShader::DrawShadow.