xpe::core::cEventManager
cEventManager * xpe::core::cEventManager::s_Instance
Referenced by Free, Get, Init.
cEventBuffer<fWindowClosed> xpe::core::cEventManager::WindowClosedEvents
cEventBuffer<fWindowResized> xpe::core::cEventManager::WindowResizedEvents
cEventBuffer<fWindowFrameResized> xpe::core::cEventManager::WindowFrameResizedEvents
cEventBuffer<fWindowMoved> xpe::core::cEventManager::WindowMovedEvents
cEventBuffer<fWindowFocused> xpe::core::cEventManager::WindowFocusedEvents
cEventBuffer<fWindowFocusLost> xpe::core::cEventManager::WindowFocusLostEvents
cEventBuffer<fKeyPressed> xpe::core::cEventManager::KeyPressedEvents
cEventBuffer<fKeyReleased> xpe::core::cEventManager::KeyReleasedEvents
cEventBuffer<fKeyHold> xpe::core::cEventManager::KeyHoldEvents
cEventBuffer<fMousePressed> xpe::core::cEventManager::MousePressedEvents
cEventBuffer<fMouseReleased> xpe::core::cEventManager::MouseReleasedEvents
cEventBuffer<fMouseHold> xpe::core::cEventManager::MouseHoldEvents
cEventBuffer<fCursorMoved> xpe::core::cEventManager::CursorMovedEvents
cEventBuffer<fCursorEntered> xpe::core::cEventManager::CursorEnteredEvents
cEventBuffer<fCursorLeft> xpe::core::cEventManager::CursorLeftEvents
cEventBuffer<fScrollChanged> xpe::core::cEventManager::ScrollChangedEvents
cEventBuffer<fCharTyped> xpe::core::cEventManager::CharTypedEvents
cEventBuffer<fCharModsTyped> xpe::core::cEventManager::CharModsTypedEvents
cEventBuffer<fSampleCountChanged> xpe::core::cEventManager::SampleCountChangedEvents
Referenced by xpe::core::sObserverSampleCount::sObserverSampleCount.
cEventBuffer<fWindowRatioChanged> xpe::core::cEventManager::WindowRatioChangedEvents
Referenced by xpe::core::sObserverWindowRatio::sObserverWindowRatio.
void xpe::core::cEventManager::Init()
References s_Instance.
Referenced by xpe::core::cApp::Run.
void xpe::core::cEventManager::Free()
References s_Instance.
Referenced by xpe::core::cApp::Run.
cEventManager & xpe::core::cEventManager::Get()
References s_Instance.
Referenced by xpe::core::sObserverSampleCount::sObserverSampleCount, xpe::core::sObserverWindowRatio::sObserverWindowRatio.