xpe::core::cMemoryPoolStack
std::vector<cMemoryPool> xpe::core::cMemoryPoolStack::Pools
Referenced by Allocate, cMemoryPoolStack, Free, LogPools, ~cMemoryPoolStack.
usize xpe::core::cMemoryPoolStack::PoolByteSize
Referenced by Allocate.
usize xpe::core::cMemoryPoolStack::PoolAllocs
Referenced by Allocate.
usize xpe::core::cMemoryPoolStack::TotalAllocCount
Referenced by Allocate, LogPools.
usize xpe::core::cMemoryPoolStack::TotalFreeCount
Referenced by Free, LogPools.
usize xpe::core::cMemoryPoolStack::TotalBytes
Referenced by Allocate, cMemoryPoolStack, LogPools.
usize xpe::core::cMemoryPoolStack::TotalBytesOccupied
Referenced by Allocate, LogPools.
usize xpe::core::cMemoryPoolStack::TotalBytesFreed
Referenced by Free, LogPools.
usize xpe::core::cMemoryPoolStack::Alignment
Referenced by Allocate.
const char* xpe::core::cMemoryPoolStack::USID
Referenced by LogPools.
xpe::core::cMemoryPoolStack::cMemoryPoolStack(const char *usid, usize poolCount, usize poolByteSize, usize poolAllocs, const usize alignment)
References xpe::core::cMemoryPool::Init, Pools, TotalBytes.
xpe::core::cMemoryPoolStack::~cMemoryPoolStack()
References Pools.
usize xpe::core::cMemoryPoolStack::GetPoolCount() const
usize xpe::core::cMemoryPoolStack::GetAllocCount(u32 index) const
usize xpe::core::cMemoryPoolStack::GetPoolSize(u32 index) const
void * xpe::core::cMemoryPoolStack::Allocate(const usize size)
References Alignment, xpe::core::cMemoryPool::Init, PoolAllocs, PoolByteSize, Pools, TotalAllocCount, TotalBytes, TotalBytesOccupied.
Referenced by AllocateConstruct, AllocateConstructArgs.
void xpe::core::cMemoryPoolStack::Free(void *address)
References Pools, TotalBytesFreed, TotalFreeCount.
T * xpe::core::cMemoryPoolStack::AllocateConstruct()
References Allocate, xpe::core::T.
T * xpe::core::cMemoryPoolStack::AllocateConstructArgs(Args &&... args)
References Allocate, xpe::core::T.
void xpe::core::cMemoryPoolStack::LogPools()
References K_MEMORY_KB, K_MEMORY_MB, LogMemory, Pools, TotalAllocCount, TotalBytes, TotalBytesFreed, TotalBytesOccupied, TotalFreeCount, USID.
Referenced by xpe::core::cMemoryManager::LogPools.