xpe::render::cCameraManager
cCamera * xpe::render::cCameraManager::s_Camera
void xpe::render::cCameraManager::Init()
References xpe::render::Buffers::Camera.
void xpe::render::cCameraManager::Free()
References xpe::render::Buffers::Camera.
glm::mat4 xpe::render::cCameraManager::GetViewProjection()
References xpe::render::Buffers::Camera, xpe::render::sItemBuffer< T >::Item, xpe::render::sCameraData::Projection, xpe::render::sCameraData::View.
Referenced by xpe::render::cWidgetShader::Draw, xpe::render::cTextShader::Draw.
void xpe::render::cCameraManager::Flush()
References xpe::render::Buffers::Camera, xpe::render::sItemBuffer< T >::Flush.
Referenced by xpe::render::cRenderSystem::WindowFrameResized.
void xpe::render::cCameraManager::Bind()
References xpe::render::Buffers::Camera, xpe::render::context::VSBindBuffer.
void xpe::render::cCameraManager::Unbind()
References xpe::render::Buffers::Camera, xpe::render::context::VSUnbindBuffer.
void xpe::render::cCameraManager::SetExposure(float exposure)
References xpe::render::Buffers::Camera, xpe::render::sCameraData::Exposure, xpe::render::sItemBuffer< T >::Flush, xpe::render::sItemBuffer< T >::Item.
Referenced by xpe::core::cApp::Run.
void xpe::render::cCameraManager::SetGamma(float gamma)
References xpe::render::Buffers::Camera, xpe::render::sItemBuffer< T >::Flush, xpe::render::sCameraData::Gamma, xpe::render::sItemBuffer< T >::Item.
Referenced by xpe::core::cApp::Run.
float xpe::render::cCameraManager::GetExposure()
References xpe::render::Buffers::Camera, xpe::render::sCameraData::Exposure, xpe::render::sItemBuffer< T >::Item.
float xpe::render::cCameraManager::GetGamma()
References xpe::render::Buffers::Camera, xpe::render::sCameraData::Gamma, xpe::render::sItemBuffer< T >::Item.
void xpe::render::cCameraManager::SetViewport(const sViewport &viewport)
References xpe::render::Buffers::Camera, xpe::render::sItemBuffer< T >::Flush, xpe::render::sItemBuffer< T >::Item, xpe::render::sCameraData::Viewport.
Referenced by xpe::render::cRenderSystem::cRenderSystem.
sViewport * xpe::render::cCameraManager::GetViewport()
References xpe::render::Buffers::Camera, xpe::render::sItemBuffer< T >::Item, xpe::render::sCameraData::Viewport.
Referenced by xpe::render::cCanvas::cCanvas, xpe::render::cRenderSystem::cRenderSystem, xpe::render::cWidgetShader::Draw, xpe::render::cTextShader::Draw, xpe::render::cRenderSystem::WindowFrameResized.
cCamera * xpe::render::cCameraManager::GetCamera()
void xpe::render::cCameraManager::SetCamera(cCamera *camera)