xpe::core::cTime
float xpe::core::cTime::m_Fps
float xpe::core::cTime::m_Millis
float xpe::core::cTime::m_Seconds
float xpe::core::cTime::m_Minutes
float xpe::core::cTime::m_Hours
xpe::core::cTime::cTime()=default
xpe::core::cTime::cTime(const float millis)
xpe::core::cTime::cTime(const cTime &time)
float xpe::core::cTime::Millis() const
float xpe::core::cTime::Seconds() const
Referenced by xpe::core::cApp::Run.
float xpe::core::cTime::Minutes() const
float xpe::core::cTime::Hours() const
float xpe::core::cTime::Fps() const
Referenced by xpe::core::cApp::LockFPSFromConfig.
void xpe::core::cTime::SetFps(float fps)
Referenced by xpe::core::cApp::LockFPSFromConfig, xpe::core::cApp::Run.
cTime & xpe::core::cTime::operator=(float f)
xpe::core::cTime::operator float() const
cTime operator+(const cTime &t1, const cTime &t2)
cTime operator-(const cTime &t1, const cTime &t2)
cTime operator*(const cTime &t1, const cTime &t2)
cTime operator/(const cTime &t1, const cTime &t2)
void operator+=(cTime &t1, const cTime &t2)
void operator-=(cTime &t1, const cTime &t2)
void operator*=(cTime &t1, const cTime &t2)
void operator/=(cTime &t1, const cTime &t2)
float operator+(const cTime &t1, float t2)
float operator-(const cTime &t1, float t2)
float operator*(const cTime &t1, float t2)
float operator/(const cTime &t1, float t2)
void operator+=(cTime &t1, float t2)
void operator-=(cTime &t1, float t2)
void operator*=(cTime &t1, float t2)
void operator/=(cTime &t1, float t2)
void xpe::core::cTime::Update()