xpe::core::cFileManager
string xpe::core::cFileManager::ReadFileWithIncludes(const string &filepath, string includeIdentifier="#include")
References LogError, ReadFileWithIncludes.
Referenced by xpe::render::cShaderManager::GetFromFile, ReadFileWithIncludes, xpe::render::cShaderManager::ReloadStage.
string xpe::core::cFileManager::ReadFile(const char *filepath)
References LogError.
bool xpe::core::cFileManager::WriteFile(const char *filepath, const string &str)
References WriteFile.
Referenced by CopyFile, WriteFile.
bool xpe::core::cFileManager::WriteFile(const char *filepath, const char *bytes, usize byteSize)
References LogError.
bool xpe::core::cFileManager::CreateDir(const char *dirName)
Referenced by xpe::render::cShaderManager::Init.
void xpe::core::cFileManager::CopyFile(const char *srcPath, const char *destPath)
References WriteFile.
void xpe::core::cFileManager::CopyDirs(const char *srcPath, const char *destPath, const bool createRoot=false)
References CopyDirs, LogError.
Referenced by CopyDirs.
hstring xpe::core::cFileManager::GetFullFileName(const char *path)
hstring xpe::core::cFileManager::GetFileName(const char *path)
bool xpe::core::cFileManager::Exists(const char *filepath)
string xpe::core::cFileManager::GetAbsolutePath(const char *path)
hstring xpe::core::cFileManager::GetDirectory(const char *filepath)
void xpe::core::cFileManager::GetFilepath(const string &fullPath, string &pathWithoutFilename)