xpe::core::cApp
cTime xpe::core::cApp::CPUTime
Referenced by Run.
cTime xpe::core::cApp::DeltaTime
Referenced by LockFPSFromConfig, Render, Run.
cTime xpe::core::cApp::CurrentTime
Referenced by Run.
sAppConfig xpe::core::cApp::Config
Referenced by InitShaders, LockFPSFromConfig, Run.
std::atomic_bool xpe::core::cApp::m_Opened
Referenced by Run.
cScene* xpe::core::cApp::m_Scene
Referenced by Render, Run.
cCanvas* xpe::core::cApp::m_Canvas
Referenced by Render, Run.
sViewport xpe::core::cApp::m_Viewport
Referenced by Run.
cRenderSystem* xpe::core::cApp::m_RenderSystem
Referenced by Render, Run.
cAnimSystem* xpe::core::cApp::m_AnimSystem
Referenced by Run.
cAudioSystem* xpe::core::cApp::m_AudioSystem
Referenced by Run.
cPhysicsSystem* xpe::core::cApp::m_PhysicsSystem
Referenced by Run.
xpe::core::cApp::cApp()
xpe::core::cApp::~cApp()
void xpe::core::cApp::Run()
References xpe::core::sTask::ANIMATION, xpe::core::sTask::AUDIO, Config, CPUTime, CurrentTime, DeltaTime, xpe::render::context::EnableErrorLog, xpe::core::sAppConfig::EnableGPUErrorLog, xpe::core::sAppConfig::EnableGPUInfoLog, xpe::core::sAppConfig::EnableGPUWarnLog, xpe::render::context::EnableInfoLog, xpe::render::context::EnableWarnLog, xpe::core::sAppConfig::Exposure, xpe::core::sAppConfig::FPS, Free, xpe::core::cEventManager::Free, xpe::core::cInputManager::Free, xpe::core::cTaskManager::Free, xpe::core::cWindowManager::Free, xpe::physics::cPhysicsManager::Free, FreeLogger, xpe::core::cWindowManager::FreeWindow, xpe::core::sAppConfig::Fullscreen, xpe::core::sAppConfig::Gamma, xpe::core::cWindowManager::GetHeight, xpe::core::cTaskManager::GetSimulationDispatcher, xpe::core::cWindowManager::GetWidth, xpe::render::sViewport::Height, Init, xpe::core::cEventManager::Init, xpe::core::cInputManager::Init, xpe::core::cTaskManager::Init, xpe::core::cWindowManager::Init, xpe::physics::cPhysicsManager::Init, InitLogger, InitShaders, xpe::core::cWindowManager::InitWindow, xpe::core::sAppConfig::LogBacktrace, LogCpuTime, LogMemoryPools, LogStackMemory, LogTime, xpe::core::sAppConfig::LogTimeDelaySeconds, xpe::core::sAppConfig::LogTitle, m_AnimSystem, m_AudioSystem, m_Canvas, m_Opened, m_PhysicsSystem, m_RenderSystem, m_Scene, m_Viewport, xpe::core::sAppConfig::MsaaSampleCount, xpe::core::sLoggerDescriptor::Name, xpe::core::cWindowManager::PollEvents, xpe::render::cRenderSystem::Prepare, Render, xpe::core::cTime::Seconds, xpe::render::cCameraManager::SetExposure, xpe::core::cTime::SetFps, xpe::render::cCameraManager::SetGamma, xpe::core::cWindowManager::ShouldClose, xpe::core::cTaskManager::SubmitTask, xpe::core::cWindowManager::Swap, xpe::core::sWindowDescriptor::Title, Update, xpe::anim::cAnimSystem::Update, xpe::audio::cAudioSystem::Update, xpe::physics::cPhysicsSystem::Update, xpe::core::sAppConfig::VSync, xpe::render::sViewport::Width, xpe::core::sAppConfig::WinHeight, xpe::core::sAppConfig::WinWidth, xpe::core::sAppConfig::WinX, xpe::core::sAppConfig::WinY.
virtual void xpe::core::cApp::Init()
Referenced by Run.
virtual void xpe::core::cApp::Update()
Referenced by Run.
virtual void xpe::core::cApp::Free()
Referenced by Run.
void xpe::core::cApp::Render()
References xpe::render::sRenderTarget::Clear, DeltaTime, xpe::render::cCanvas::Draw, m_Canvas, m_RenderSystem, m_Scene, xpe::render::RenderTargets::SSAO, xpe::render::cRenderSystem::Update.
Referenced by Run.
void xpe::core::cApp::InitShaders()
References Config, xpe::render::cShader::Enable, xpe::core::sAppConfig::EnableSSAO, xpe::render::cShaderManager::GetShader, xpe::core::sAppConfig::MsaaSampleCount, xpe::render::cShaderManager::SetShader.
Referenced by Run.
void xpe::core::cApp::LockFPSFromConfig()
References Config, DeltaTime, xpe::core::sAppConfig::FPS, xpe::core::cTime::Fps, xpe::core::sAppConfig::LockOnFps, xpe::core::cTime::SetFps.