xpe::core::cTaskDispatcher
cRingBuffer<sTask> xpe::core::cTaskDispatcher::m_TaskBuffer
Referenced by cTaskDispatcher, Dispatch, Dispatch, InitThread.
std::condition_variable xpe::core::cTaskDispatcher::m_WakeCondition
Referenced by Dispatch, Dispatch, Poll.
std::mutex xpe::core::cTaskDispatcher::m_WakeMutex
u64 xpe::core::cTaskDispatcher::m_TasksTodo
Referenced by cTaskDispatcher, Dispatch, Dispatch, IsBusy.
std::atomic<u64> xpe::core::cTaskDispatcher::m_TasksDone
Referenced by cTaskDispatcher, IsBusy.
u32 xpe::core::cTaskDispatcher::m_WorkerCount
Referenced by cTaskDispatcher, GetWorkerCount.
xpe::core::cTaskDispatcher::cTaskDispatcher(u32 workerSize, usize taskBufferSize, const char *name, cThread::ePriority priority)
References InitThread, m_TaskBuffer, m_TasksDone, m_TasksTodo, m_WorkerCount.
void xpe::core::cTaskDispatcher::Dispatch(const sTask &task)
References m_TaskBuffer, m_TasksTodo, m_WakeCondition, Poll.
Referenced by xpe::core::cTaskManager::SubmitTask, xpe::core::cSimulationDispatcher::submitTask, xpe::core::cTaskManager::SubmitTask.
void xpe::core::cTaskDispatcher::Dispatch(u32 tasksPerThread, u32 taskSize, const sTask &task)
References m_TaskBuffer, m_TasksTodo, m_WakeCondition, Poll, xpe::core::sTask::Todo.
bool xpe::core::cTaskDispatcher::IsBusy()
References m_TasksDone, m_TasksTodo.
Referenced by Wait.
u32 xpe::core::cTaskDispatcher::GetWorkerCount() const
References m_WorkerCount.
Referenced by xpe::core::cSimulationDispatcher::getWorkerCount.
void xpe::core::cTaskDispatcher::Wait()
References IsBusy, Poll.
void xpe::core::cTaskDispatcher::Poll()
References m_WakeCondition.
Referenced by Dispatch, Dispatch, Wait.
void xpe::core::cTaskDispatcher::InitThread(u32 workerId, const char *name, cThread::ePriority priority)
References m_TaskBuffer, xpe::core::cThread::SetFormat.
Referenced by cTaskDispatcher.