xpe::render::sListBuffer
vector<T> xpe::render::sListBuffer< T >::m_List
Referenced by xpe::render::sListBuffer< T >::Capacity, xpe::render::sListBuffer< T >::Get, xpe::render::sListBuffer< T >::GetList, xpe::render::sListBuffer< T >::Size.
xpe::render::sListBuffer< T >::sListBuffer()=default
xpe::render::sListBuffer< T >::sListBuffer(usize count, u32 slot, sBuffer::eSubType subtype=sBuffer::eSubType::NONE, sBuffer::eViewType viewtype=sBuffer::eViewType::SRV)
References xpe::render::context::CopyBuffer, xpe::render::context::CreateBuffer, xpe::render::sBuffer::LIST, xpe::core::T.
xpe::render::sListBuffer< T >::~sListBuffer()
References xpe::render::context::FreeBuffer.
void xpe::render::sListBuffer< T >::Flush()
References xpe::render::context::CopyBuffer.
Referenced by xpe::render::cMaterialManager::AddMaterial, xpe::render::cMaterialManager::Clear, xpe::render::cInstancingShader::DrawInstanced, xpe::anim::cSkeletonManager::Flush.
void xpe::render::sListBuffer< T >::FlushItem(u32 index, const T &item)
References xpe::render::context::CopyBufferOffset, xpe::core::T.
Referenced by xpe::render::cMaterialManager::Flush.
void xpe::render::sListBuffer< T >::FlushItemAt(u32 index)
References xpe::render::context::CopyBufferOffset, xpe::core::T.
u32 xpe::render::sListBuffer< T >::Add(Args &&... args)
Referenced by xpe::render::cMaterialManager::AddMaterial, xpe::render::cInstancingShader::DrawInstanced.
void xpe::render::sListBuffer< T >::RemoveAt(u32 index)
void xpe::render::sListBuffer< T >::Resize(const usize count)
Referenced by xpe::anim::cSkeletonManager::AddSkeleton.
void xpe::render::sListBuffer< T >::Reserve(const usize count)
Referenced by xpe::render::cInstancingShader::cInstancingShader, xpe::render::cTextShader::cTextShader, xpe::render::cWidgetShader::cWidgetShader.
void xpe::render::sListBuffer< T >::Recreate(const usize count)
References xpe::render::context::CopyBuffer, xpe::render::context::CreateBuffer, xpe::render::context::FreeBuffer.
void xpe::render::sListBuffer< T >::Clear()
Referenced by xpe::render::cMaterialManager::Clear, xpe::render::cInstancingShader::DrawInstanced.
bool xpe::render::sListBuffer< T >::Empty()
vector< T > & xpe::render::sListBuffer< T >::GetList()
References xpe::render::sListBuffer< T >::m_List.
usize xpe::render::sListBuffer< T >::Size() const
References xpe::render::sListBuffer< T >::m_List.
Referenced by xpe::render::cMaterialManager::AddMaterial, xpe::anim::cSkeletonManager::AddSkeleton.
usize xpe::render::sListBuffer< T >::Capacity() const
References xpe::render::sListBuffer< T >::m_List.
T * xpe::render::sListBuffer< T >::Get(u32 index)
References LogError, xpe::render::sListBuffer< T >::m_List.
Referenced by xpe::render::sListBuffer< T >::operator[].
T * xpe::render::sListBuffer< T >::operator[](u32 index)
References xpe::render::sListBuffer< T >::Get.