xpe::core::cInputManager
sMouseCursor xpe::core::cInputManager::s_Cursor
void xpe::core::cInputManager::Init()
References xpe::core::cWindowManager::GetInstance, LogInfo.
Referenced by xpe::core::cApp::Run.
void xpe::core::cInputManager::Free()
Referenced by xpe::core::cApp::Run.
void xpe::core::cInputManager::CaptureCursor()
References CaptureCursor.
Referenced by CaptureCursor.
void xpe::core::cInputManager::CaptureCursor(const double x, const double y)
References xpe::core::sMouseCursor::Delta, xpe::core::sMouseCursor::Position, xpe::core::x.
bool xpe::core::cInputManager::KeyPressed(const eKey key)
bool xpe::core::cInputManager::KeyReleased(const eKey key)
bool xpe::core::cInputManager::KeyHold(const eKey key)
sKeyState xpe::core::cInputManager::GetKeyState(const eKey key)
References xpe::core::sKeyState::Pressed.
bool xpe::core::cInputManager::MousePressed(const eMouse mouse)
Referenced by xpe::render::cWidgetShader::Draw.
bool xpe::core::cInputManager::MouseReleased(const eMouse mouse)
bool xpe::core::cInputManager::MouseHold(const eMouse mouse)
sMouseState xpe::core::cInputManager::GetMouseState(const eMouse mouse)
References xpe::core::sMouseState::Pressed.
static const sMouseCursor & xpe::core::cInputManager::GetMouseCursor()
void xpe::core::cInputManager::InitWindowCallbacks()
void xpe::core::cInputManager::InitKeyCallbacks()
void xpe::core::cInputManager::InitMouseCallbacks()
void xpe::core::cInputManager::InitCursorCallbacks()
void xpe::core::cInputManager::InitScrollCallbacks()
void xpe::core::cInputManager::InitCharCallbacks()