xpe::math::cMathManager
sRay xpe::math::cMathManager::ToLocalSpace(const sRay &ray, const glm::mat4 &modelMatrix)
References xpe::math::sRay::Origin.
sRay xpe::math::cMathManager::ToWorldSpace(const sRay &ray, const glm::mat4 &modelMatrix)
References xpe::math::sRay::Origin.
sRay xpe::math::cMathManager::ToWorldSpaceInverse(const sRay &ray, const glm::mat4 &viewMatrix)
References xpe::math::sRay::Origin.
sRay xpe::math::cMathManager::ToViewSpace(const sRay &ray, const glm::mat4 &viewMatrix)
References xpe::math::sRay::Origin.
sRay xpe::math::cMathManager::ToViewSpaceInverse(const sRay &ray, const float fov, const float aspectRatio)
sRay xpe::math::cMathManager::ToViewSpaceInverse(const sRay &ray, const glm::mat4 &perspectiveMatrix)
References xpe::math::sRay::Origin.
sRay xpe::math::cMathManager::ToClipSpace(const sRay &ray, const float fov, const float aspectRatio)
sRay xpe::math::cMathManager::ToClipSpace(const sRay &ray, const glm::mat4 &perspectiveMatrix)
References xpe::math::sRay::Origin.
sRay xpe::math::cMathManager::ToClipSpaceInverse(const sRay &ray)
References xpe::math::sRay::Origin.
sRay xpe::math::cMathManager::ToNDCSpace(const sRay &ray)
References xpe::math::sRay::Origin.
sRay xpe::math::cMathManager::ToNDCSpaceInverse(const sRay &ray, int width, int height)
References xpe::math::sRay::Origin.
sRay xpe::math::cMathManager::ToScreenSpace(const sRay &ray, int width, int height)
References xpe::math::sRay::Origin.
glm::mat4 xpe::math::cMathManager::UpdateModelMatrix(const sModelMatrix &modelMatrix)
Referenced by xpe::render::cInstancingShader::DrawInstanced.
glm::mat4 xpe::math::cMathManager::UpdateNormalMatrix(const glm::mat4 &modelMatrix)
Referenced by xpe::render::cInstancingShader::DrawInstanced.
glm::mat4 xpe::math::cMathManager::UpdateViewMatrix(const sViewMatrix &viewMatrix)
Referenced by xpe::render::cOrthoCamera::Flush, UpdateLightMatrix, UpdateLightMatrix.
glm::mat4 xpe::math::cMathManager::UpdateOrthoMatrix(const sOrthoMatrix &orthoMatrix)
Referenced by xpe::render::cWidgetShader::Draw, xpe::render::cTextShader::Draw, xpe::render::cOrthoCamera::Flush, UpdateLightMatrix.
glm::mat4 xpe::math::cMathManager::UpdatePerspectiveMatrix(const sPerspectiveMatrix &perspectiveMatrix)
Referenced by UpdateLightMatrix.
glm::mat4 xpe::math::cMathManager::UpdateLightMatrix(const sOrthoMatrix &orthoMatrix, const sViewMatrix &viewMatrix)
References UpdateOrthoMatrix, UpdateViewMatrix.
glm::mat4 xpe::math::cMathManager::UpdateLightMatrix(const sPerspectiveMatrix &perspectiveMatrix, const sViewMatrix &viewMatrix)
References UpdatePerspectiveMatrix, UpdateViewMatrix.