xpe::render::cShadowShader
xpe::render::cShadowShader::cShadowShader(const string &name)
void xpe::render::cShadowShader::DrawShadow(cScene *scene, u32 lightIndex)
References xpe::render::cInstancingShader::DrawInstanced.
Referenced by xpe::render::cDirectionalShadowShader::Draw, xpe::render::cPointShadowShader::Draw, xpe::render::cSpotShadowShader::Draw.
void xpe::render::cShadowShader::InitPrepass() override
References xpe::render::ALL, xpe::render::cDefaultShader::BlendMode, xpe::render::sRasterizer::CullMode, xpe::render::cDefaultShader::DepthStencilMode, xpe::render::sDepthStencilMode::DepthWriteMask, xpe::render::sBlendTarget::Enable, xpe::render::FRONT, xpe::render::sBlendMode::IndependentBlendEnable, xpe::render::cDefaultShader::Rasterizer, xpe::render::sBlendMode::Targets.