xpe::render::cDefaultShader
ePrimitiveTopology xpe::render::cDefaultShader::PrimitiveTopology
Referenced by Bind, xpe::render::cTextShader::cTextShader, xpe::render::cWidgetShader::cWidgetShader.
sInputLayout xpe::render::cDefaultShader::InputLayout
Referenced by Bind, Init, ~cDefaultShader.
sShaderStage* xpe::render::cDefaultShader::VertexStage
Referenced by Bind, xpe::render::cCanvas::cCanvas, xpe::render::cCompositeTransparentShader::cCompositeTransparentShader, xpe::render::cDirectionalShadowShader::cDirectionalShadowShader, xpe::render::cFinalShader::cFinalShader, xpe::render::cOpaqueShader::cOpaqueShader, xpe::render::cPointShadowShader::cPointShadowShader, xpe::render::cSkyboxShader::cSkyboxShader, xpe::render::cSpotShadowShader::cSpotShadowShader, xpe::render::cSsaoShader::cSsaoShader, xpe::render::cTextShader::cTextShader, xpe::render::cTransparentShader::cTransparentShader, xpe::render::cWidgetShader::cWidgetShader, xpe::render::cCanvas::Draw, Init, Unbind.
sShaderStage* xpe::render::cDefaultShader::PixelStage
Referenced by Bind, xpe::render::cCanvas::cCanvas, xpe::render::cCompositeTransparentShader::cCompositeTransparentShader, xpe::render::cDirectionalShadowShader::cDirectionalShadowShader, xpe::render::cFinalShader::cFinalShader, xpe::render::cOpaqueShader::cOpaqueShader, xpe::render::cPointShadowShader::cPointShadowShader, xpe::render::cSkyboxShader::cSkyboxShader, xpe::render::cSpotShadowShader::cSpotShadowShader, xpe::render::cSsaoShader::cSsaoShader, xpe::render::cTextShader::cTextShader, xpe::render::cTransparentShader::cTransparentShader, xpe::render::cWidgetShader::cWidgetShader, xpe::render::cCanvas::Draw, Unbind.
sShaderStage* xpe::render::cDefaultShader::GeometryStage
Referenced by Bind, Unbind.
sRenderTarget* xpe::render::cDefaultShader::RenderTarget
Referenced by Bind, xpe::render::cCompositeTransparentShader::cCompositeTransparentShader, xpe::render::cDirectionalShadowShader::cDirectionalShadowShader, xpe::render::cFinalShader::cFinalShader, xpe::render::cOpaqueShader::cOpaqueShader, xpe::render::cPointShadowShader::cPointShadowShader, xpe::render::cSkyboxShader::cSkyboxShader, xpe::render::cSpotShadowShader::cSpotShadowShader, xpe::render::cSsaoShader::cSsaoShader, xpe::render::cTextShader::cTextShader, xpe::render::cTransparentShader::cTransparentShader, xpe::render::cWidgetShader::cWidgetShader, Unbind.
sRasterizer xpe::render::cDefaultShader::Rasterizer
Referenced by Bind, Init, InitOpaque, xpe::render::cSkyboxShader::InitOpaque, InitPrepass, xpe::render::cShadowShader::InitPrepass, InitTransparent, ~cDefaultShader.
sDepthStencilMode xpe::render::cDefaultShader::DepthStencilMode
Referenced by Bind, Init, InitFinal, InitOpaque, xpe::render::cSkyboxShader::InitOpaque, InitPostFX, xpe::render::cCompositeTransparentShader::InitPostFX, InitPrepass, xpe::render::cShadowShader::InitPrepass, InitTransparent, InitUI, ~cDefaultShader.
sBlendMode xpe::render::cDefaultShader::BlendMode
Referenced by Bind, Init, InitFinal, InitOpaque, InitPostFX, xpe::render::cCompositeTransparentShader::InitPostFX, InitPrepass, xpe::render::cShadowShader::InitPrepass, InitTransparent, InitUI, ~cDefaultShader.
xpe::render::cDefaultShader::cDefaultShader(cShader::eCategory category, const string &name)
xpe::render::cDefaultShader::~cDefaultShader() override
References BlendMode, xpe::render::cShader::Category, DepthStencilMode, xpe::render::context::FreeBlendMode, xpe::render::context::FreeDepthStencilMode, xpe::render::context::FreeInputLayout, xpe::render::context::FreeRasterizer, InputLayout, xpe::render::cShader::NONE, Rasterizer.
void xpe::render::cDefaultShader::Bind() override
References xpe::render::sRenderTarget::Bind, xpe::render::context::BindBlendMode, xpe::render::context::BindDepthStencilMode, xpe::render::context::BindGSStage, xpe::render::context::BindInputLayout, xpe::render::context::BindPrimitiveTopology, xpe::render::context::BindPSStage, xpe::render::context::BindRasterizer, xpe::render::context::BindVSStage, BlendMode, DepthStencilMode, GeometryStage, InputLayout, PixelStage, PrimitiveTopology, Rasterizer, RenderTarget, xpe::render::sDepthStencilMode::State, xpe::render::sBlendMode::State, xpe::render::sRasterizer::State, VertexStage.
void xpe::render::cDefaultShader::Unbind() override
References GeometryStage, PixelStage, RenderTarget, xpe::render::sRenderTarget::Unbind, xpe::render::context::UnbindGSStage, xpe::render::context::UnbindPSStage, xpe::render::context::UnbindVSStage, VertexStage.
void xpe::render::cDefaultShader::Init()
References BlendMode, xpe::render::sShaderStage::Blob, xpe::render::cShader::Category, xpe::render::context::CreateBlendMode, xpe::render::context::CreateDepthStencilMode, xpe::render::context::CreateInputLayout, xpe::render::context::CreateRasterizer, DepthStencilMode, xpe::render::cShader::FINAL, InitFinal, InitOpaque, InitPostFX, InitPrepass, InitTransparent, InitUI, InputLayout, LogError, xpe::render::cShader::NONE, xpe::render::cShader::OPAQUE, xpe::render::cShader::POSTFX, xpe::render::cShader::PREPASS, Rasterizer, xpe::render::cShader::TRANSPARENT, xpe::render::cShader::UI, VertexStage.
Referenced by xpe::render::cCompositeTransparentShader::cCompositeTransparentShader, xpe::render::cDirectionalShadowShader::cDirectionalShadowShader, xpe::render::cFinalShader::cFinalShader, xpe::render::cOpaqueShader::cOpaqueShader, xpe::render::cPointShadowShader::cPointShadowShader, xpe::render::cSkyboxShader::cSkyboxShader, xpe::render::cSpotShadowShader::cSpotShadowShader, xpe::render::cSsaoShader::cSsaoShader, xpe::render::cTextShader::cTextShader, xpe::render::cTransparentShader::cTransparentShader, xpe::render::cWidgetShader::cWidgetShader.
void xpe::render::cDefaultShader::InitPrepass()
References xpe::render::ALL, BlendMode, xpe::render::sRasterizer::CullMode, DepthStencilMode, xpe::render::sDepthStencilMode::DepthWriteMask, xpe::render::sBlendTarget::Enable, xpe::render::sBlendMode::IndependentBlendEnable, xpe::render::NONE, Rasterizer, xpe::render::sBlendMode::Targets.
Referenced by Init.
void xpe::render::cDefaultShader::InitOpaque()
References xpe::render::ALL, BlendMode, xpe::render::sRasterizer::CullMode, DepthStencilMode, xpe::render::sDepthStencilMode::DepthWriteMask, xpe::render::sBlendTarget::Enable, xpe::render::sBlendMode::IndependentBlendEnable, xpe::render::NONE, Rasterizer, xpe::render::sBlendMode::Targets.
Referenced by Init, xpe::render::cSkyboxShader::InitOpaque.
void xpe::render::cDefaultShader::InitTransparent()
References xpe::render::ADD, BlendMode, xpe::render::sRasterizer::CullMode, DepthStencilMode, xpe::render::sDepthStencilMode::DepthWriteMask, xpe::render::sBlendTarget::Enable, xpe::render::sBlendMode::IndependentBlendEnable, xpe::render::INV_SRC_COLOR, xpe::render::NONE, xpe::render::ONE, Rasterizer, xpe::render::sBlendMode::Targets, xpe::render::ZERO.
Referenced by Init.
void xpe::render::cDefaultShader::InitPostFX()
References xpe::render::ALL, BlendMode, DepthStencilMode, xpe::render::sDepthStencilMode::DepthWriteMask, xpe::render::sBlendTarget::Enable, xpe::render::sBlendMode::IndependentBlendEnable, xpe::render::sBlendMode::Targets.
Referenced by Init.
void xpe::render::cDefaultShader::InitUI()
References xpe::render::ALL, BlendMode, DepthStencilMode, xpe::render::sDepthStencilMode::DepthWriteMask, xpe::render::sBlendTarget::Enable, xpe::render::sBlendMode::IndependentBlendEnable, xpe::render::sBlendMode::Targets.
Referenced by Init.
void xpe::render::cDefaultShader::InitFinal()
References xpe::render::ALL, BlendMode, DepthStencilMode, xpe::render::sDepthStencilMode::DepthWriteMask, xpe::render::sBlendTarget::Enable, xpe::render::sBlendMode::IndependentBlendEnable, xpe::render::sBlendMode::Targets.
Referenced by Init.