xpe::core::cWindowManager
sWindow xpe::core::cWindowManager::s_Window
int xpe::core::cWindowManager::s_WindowModeX
int xpe::core::cWindowManager::s_WindowModeY
int xpe::core::cWindowManager::s_WindowModeWidth
int xpe::core::cWindowManager::s_WindowModeHeight
bool xpe::core::cWindowManager::s_EnableFullscreen
void xpe::core::cWindowManager::Init()
References LogError, LogInfo.
Referenced by xpe::core::cApp::Run.
void xpe::core::cWindowManager::Free()
References LogInfo.
Referenced by xpe::core::cApp::Run.
void xpe::core::cWindowManager::InitWindow(const sWindowDescriptor &windowDescriptor)
References xpe::core::sWindow::Descriptor, xpe::core::sWindow::Instance, LogInfo, SetFullscreen, SetPos, SetSize, SetVSync, SetWindowed, xpe::core::sWindow::Win32Instance.
Referenced by xpe::core::cApp::Run.
void xpe::core::cWindowManager::FreeWindow()
References xpe::core::sWindow::Instance, LogInfo.
Referenced by xpe::core::cApp::Run.
const sWindowDescriptor & xpe::core::cWindowManager::GetDescriptor()
References xpe::core::sWindow::Descriptor.
bool xpe::core::cWindowManager::ShouldClose()
Referenced by xpe::core::cApp::Run.
void xpe::core::cWindowManager::Close()
void xpe::core::cWindowManager::PollEvents()
Referenced by xpe::core::cApp::Run.
void xpe::core::cWindowManager::Swap()
Referenced by xpe::core::cApp::Run.
bool xpe::core::cWindowManager::IsWindowed()
bool xpe::core::cWindowManager::IsFullscreen()
int xpe::core::cWindowManager::GetWidth()
References xpe::core::sWindow::Descriptor, xpe::core::sWindowDescriptor::Height, xpe::core::sWindowDescriptor::Width.
Referenced by xpe::core::cApp::Run.
int xpe::core::cWindowManager::GetHeight()
References xpe::core::sWindow::Descriptor, xpe::core::sWindowDescriptor::Height, xpe::core::sWindowDescriptor::Width.
Referenced by xpe::core::cApp::Run.
int xpe::core::cWindowManager::GetFrameWidth()
References xpe::core::sWindow::Descriptor, xpe::core::sWindowDescriptor::FrameHeight, xpe::core::sWindowDescriptor::FrameWidth.
Referenced by xpe::render::cSsaoShader::cSsaoShader.
int xpe::core::cWindowManager::GetFrameHeight()
References xpe::core::sWindow::Descriptor, xpe::core::sWindowDescriptor::FrameHeight, xpe::core::sWindowDescriptor::FrameWidth.
Referenced by xpe::render::cSsaoShader::cSsaoShader.
int xpe::core::cWindowManager::GetPosX()
References xpe::core::sWindow::Descriptor, xpe::core::sWindowDescriptor::X, xpe::core::sWindowDescriptor::Y.
int xpe::core::cWindowManager::GetPosY()
References xpe::core::sWindow::Descriptor, xpe::core::sWindowDescriptor::X, xpe::core::sWindowDescriptor::Y.
const char * xpe::core::cWindowManager::GetTitle()
References xpe::core::sWindow::Descriptor, xpe::core::sWindowDescriptor::Title.
void * xpe::core::cWindowManager::GetInstance()
References xpe::core::sWindow::Instance.
Referenced by xpe::core::cInputManager::Init.
void * xpe::core::cWindowManager::GetWin32Instance()
References xpe::core::sWindow::Win32Instance.
int xpe::core::cWindowManager::GetRefreshRate()
int xpe::core::cWindowManager::GetMonitorWidth()
int xpe::core::cWindowManager::GetMonitorHeight()
void xpe::core::cWindowManager::SetPos(int x, int y)
References xpe::core::sWindow::Descriptor, xpe::core::x, xpe::core::sWindowDescriptor::X, xpe::core::sWindowDescriptor::Y.
Referenced by InitWindow.
void xpe::core::cWindowManager::SetSize(int w, int h)
References xpe::core::sWindow::Descriptor, xpe::core::sWindowDescriptor::Height, xpe::core::w, xpe::core::sWindowDescriptor::Width.
Referenced by InitWindow.
void xpe::core::cWindowManager::SetUserPointer(void *userPtr)
void * xpe::core::cWindowManager::GetUserPointer()
void xpe::core::cWindowManager::SetVSync(bool vsync)
Referenced by InitWindow.
void xpe::core::cWindowManager::SetFullscreen()
References xpe::core::sWindow::Descriptor, xpe::core::sWindowDescriptor::Height, xpe::core::sWindowDescriptor::Width, xpe::core::sWindowDescriptor::X, xpe::core::sWindowDescriptor::Y.
Referenced by InitWindow, ToggleWindowMode.
void xpe::core::cWindowManager::SetWindowed()
References xpe::core::sWindow::Descriptor, xpe::core::sWindowDescriptor::Height, xpe::core::sWindowDescriptor::Width, xpe::core::sWindowDescriptor::X, xpe::core::sWindowDescriptor::Y.
Referenced by InitWindow, ToggleWindowMode.
void xpe::core::cWindowManager::SetFullscreenWindowed()
References xpe::core::sWindow::Descriptor, xpe::core::sWindowDescriptor::Height, xpe::core::sWindowDescriptor::Width, xpe::core::sWindowDescriptor::X, xpe::core::sWindowDescriptor::Y.
void xpe::core::cWindowManager::ToggleWindowMode()
References SetFullscreen, SetWindowed.
void xpe::core::cWindowManager::CreatePrimaryMonitor()