xpe::ecs::cScene
physx::PxScene* xpe::ecs::cScene::PhysicsScene
string xpe::ecs::cScene::m_Tag
cRegistry xpe::ecs::cScene::m_Registry
unordered_map<EntityID, unordered_map<ComponentID, cJson*> > xpe::ecs::cScene::m_Jsons
unordered_map<EntityID, unordered_map<ComponentID, cXml*> > xpe::ecs::cScene::m_Xmls
void xpe::ecs::cScene::SetTag(const string &tag)
const string & xpe::ecs::cScene::GetTag() const
EntityID xpe::ecs::cScene::CreateEntity()
Referenced by xpe::ecs::cEntity::cEntity.
void xpe::ecs::cScene::RemoveEntity(EntityID entityId)
bool xpe::ecs::cScene::IsValidEntity(EntityID entityId)
void xpe::ecs::cScene::ClearEntities()
T & xpe::ecs::cScene::AddComponent(EntityID entityId, Args &&... args)
References xpe::core::T.
Referenced by xpe::ecs::cEntity::Add.
void xpe::ecs::cScene::RemoveComponent(EntityID entityId)
References xpe::core::T.
Referenced by xpe::ecs::cEntity::Remove.
T & xpe::ecs::cScene::GetComponent(EntityID entityId)
References xpe::core::T.
Referenced by xpe::ecs::cEntity::Get.
bool xpe::ecs::cScene::HasAnyComponent(EntityID entityId)
References xpe::core::T.
Referenced by xpe::ecs::cEntity::HasAny.
bool xpe::ecs::cScene::HasAllComponent(EntityID entityId)
References xpe::core::T.
Referenced by xpe::ecs::cEntity::HasAll.
void xpe::ecs::cScene::ClearComponents()
References xpe::core::T.
auto xpe::ecs::cScene::GetComponents()
References xpe::core::T.
Referenced by xpe::anim::cAnimSystem::Update.
unordered_map< ComponentID, cJson * > & xpe::ecs::cScene::GetJsons(EntityID entityId)
Referenced by xpe::ecs::cEntity::FromJson, xpe::ecs::cEntity::ToJson.
unordered_map< ComponentID, cXml * > & xpe::ecs::cScene::GetXmls(EntityID entityId)
Referenced by xpe::ecs::cEntity::FromXml, xpe::ecs::cEntity::ToXml.
void xpe::ecs::cScene::ToJson(json &root) override
void xpe::ecs::cScene::FromJson(json &root) override
xml xpe::ecs::cScene::ToXml(xml &root) override
References xpe::res::SetXmlValue.
xml xpe::ecs::cScene::FromXml(xml &root) override
References xpe::res::GetXmlValue.