xpe::render::context
void * xpe::render::context::SwapchainTargetView
void * xpe::render::context::SwapchainTextureInstance
DebuggerCallback xpe::render::context::Callback
Referenced by xpe::render::cDebugManager::Init.
bool xpe::render::context::EnableInfoLog
Referenced by xpe::core::cApp::Run.
bool xpe::render::context::EnableWarnLog
Referenced by xpe::core::cApp::Run.
bool xpe::render::context::EnableErrorLog
Referenced by xpe::core::cApp::Run.
ENGINE_API void xpe::render::context::CopyBuffer(const sBuffer &buffer, const void *data, usize dataByteSize)
References CopyBuffer, Map, Unmap.
Referenced by CopyBuffer, CSBindBuffer, xpe::render::sIndexBuffer::Flush, xpe::render::sVertexBuffer::Flush, xpe::render::sItemBuffer< T >::Flush, xpe::render::sListBuffer< T >::Flush, xpe::render::sItemBuffer< T >::FlushItem, xpe::render::sIndexBuffer::Recreate, xpe::render::sVertexBuffer::Recreate, xpe::render::sListBuffer< T >::Recreate, xpe::render::sItemBuffer< T >::sItemBuffer, xpe::render::sListBuffer< T >::sListBuffer.
ENGINE_API void xpe::render::context::CopyBufferOffset(const sBuffer &buffer, usize offset, const void *data, usize dataByteSize)
References CopyBufferOffset, Map, Unmap.
Referenced by CopyBufferOffset, CSBindBuffer, xpe::render::sListBuffer< T >::FlushItem, xpe::render::sListBuffer< T >::FlushItemAt.
ENGINE_API void xpe::render::context::MoveBuffer(const sBuffer &buffer, const void *data, usize dataByteSize)
References Map, MoveBuffer, Unmap.
Referenced by CSBindBuffer, MoveBuffer.
ENGINE_API void xpe::render::context::MoveBufferOffset(const sBuffer &buffer, usize offset, const void *data, usize dataByteSize)
References Map, MoveBufferOffset, Unmap.
Referenced by CSBindBuffer, xpe::render::sIndexBuffer::FlushIndex, xpe::render::sVertexBuffer::FlushVertex, MoveBufferOffset.
ENGINE_API void xpe::render::context::CopyTexture(const sTexture &texture, const void *data, usize dataByteSize, u32 layerIndex)
References CopyTexture, Map, Unmap, UpdateSubData.
Referenced by CopyTexture, xpe::render::sTexture::FlushLayer, FreeTextureDepthStencil.
ENGINE_API void xpe::render::context::CopyTextureOffset(const sTexture &texture, usize offset, const void *data, usize dataByteSize, u32 layerIndex)
References CopyTextureOffset, Map, Unmap, UpdateSubData.
Referenced by CopyTextureOffset, FreeTextureDepthStencil.
ENGINE_API void xpe::render::context::MoveTexture(const sTexture &texture, const void *data, usize dataByteSize, u32 layerIndex)
References Map, MoveTexture, Unmap, UpdateSubData.
Referenced by FreeTextureDepthStencil, MoveTexture.
ENGINE_API void xpe::render::context::MoveTextureOffset(const sTexture &texture, usize offset, const void *data, usize dataByteSize, u32 layerIndex)
References Map, MoveTextureOffset, Unmap, UpdateSubData.
Referenced by FreeTextureDepthStencil, MoveTextureOffset.
ENGINE_API void xpe::render::context::CreateTexture(sTexture &texture)
References CreateTexture, CreateTexture1D, CreateTexture2D, CreateTexture2DArray, CreateTexture3D, CreateTextureCube, CreateTextureDepthStencil.
Referenced by CreateTexture, xpe::render::sTexture::Flush, FreeShaderResourceView, xpe::render::sTexture::Init, xpe::render::sTexture::Resize.
ENGINE_API void xpe::render::context::FreeTexture(sTexture &texture)
References FreeShaderResourceView, FreeTexture, FreeTexture1D, FreeTexture2D, FreeTexture2DArray, FreeTexture3D, FreeTextureCube, FreeTextureDepthStencil.
Referenced by CSBindTexture, xpe::render::sTexture::Flush, xpe::render::sTexture::Free, FreeTexture, xpe::render::sTexture::Resize.
ENGINE_API void xpe::render::context::FreeRenderTarget(sRenderTarget &renderTarget)
References FreeRenderTarget, FreeRenderTargetColorViews, FreeRenderTargetDepthView.
Referenced by ClearDepthStencilTarget, FreeRenderTarget, xpe::render::sRenderTarget::~sRenderTarget.
ENGINE_API void xpe::render::context::BindRenderTarget(const vector< void * > &colorViews, void *depthView, sViewport *viewport)
References BindRenderTarget, BindViewport.
Referenced by xpe::render::sRenderTarget::Bind, BindRenderTarget, BindRenderTarget, xpe::render::cCanvas::Draw.
ENGINE_API void xpe::render::context::VSBindBuffer(const sBuffer &buffer)
References VSBindBuffer.
Referenced by xpe::render::cCameraManager::Bind, xpe::render::cInstancingShader::DrawInstanced, VSBindBuffer, VSBindBuffer, VSUnbindBuffer.
ENGINE_API void xpe::render::context::VSUnbindBuffer(const sBuffer &buffer)
References VSBindBuffer, VSUnbindBuffer.
Referenced by xpe::render::cInstancingShader::DrawInstanced, xpe::render::cCameraManager::Unbind, VSBindBuffer, VSUnbindBuffer.
ENGINE_API void xpe::render::context::PSBindBuffer(const sBuffer &buffer)
References PSBindBuffer.
Referenced by PSBindBuffer, PSBindBuffer, PSUnbindBuffer.
ENGINE_API void xpe::render::context::PSUnbindBuffer(const sBuffer &buffer)
References PSBindBuffer, PSUnbindBuffer.
Referenced by PSBindBuffer, PSUnbindBuffer.
ENGINE_API void xpe::render::context::GSBindBuffer(const sBuffer &buffer)
References GSBindBuffer.
Referenced by GSBindBuffer, GSBindBuffer, GSUnbindBuffer.
ENGINE_API void xpe::render::context::GSUnbindBuffer(const sBuffer &buffer)
References GSBindBuffer, GSUnbindBuffer.
Referenced by GSBindBuffer, GSUnbindBuffer.
ENGINE_API void xpe::render::context::CSBindBuffer(const sBuffer &buffer)
References CSBindBuffer.
Referenced by CSBindBuffer, CSBindBuffer, CSUnbindBuffer.
ENGINE_API void xpe::render::context::CSUnbindBuffer(const sBuffer &buffer)
References CSBindBuffer, CSUnbindBuffer.
Referenced by CSBindBuffer, CSUnbindBuffer.
ENGINE_API void xpe::render::context::VSBindTexture(const sTexture &texture)
References VSBindTexture.
Referenced by VSBindTexture, VSBindTexture, VSBindTexture, VSBindTextureSlot, VSUnbindTexture.
ENGINE_API void xpe::render::context::VSBindTexture(const sTexture &texture, u32 slot)
References VSBindTexture.
ENGINE_API void xpe::render::context::VSBindTextureSlot(u32 slot)
References VSBindTexture, VSBindTextureSlot.
Referenced by VSBindTexture, VSBindTextureSlot.
ENGINE_API void xpe::render::context::VSUnbindTexture(const sTexture &texture)
References VSBindTexture, VSUnbindTexture.
Referenced by VSBindTexture, VSUnbindTexture.
ENGINE_API void xpe::render::context::PSBindTexture(const sTexture &texture)
References PSBindTexture.
Referenced by xpe::render::sRenderTarget::BindColor, xpe::render::sRenderTarget::BindDepth, xpe::render::cCanvas::Draw, xpe::render::cSkyboxShader::Draw, PSBindTexture, PSBindTexture, PSBindTexture, PSBindTextureSlot, PSUnbindTexture.
ENGINE_API void xpe::render::context::PSBindTexture(const sTexture &texture, u32 slot)
References PSBindTexture.
ENGINE_API void xpe::render::context::PSBindTextureSlot(u32 slot)
References PSBindTexture, PSBindTextureSlot.
Referenced by xpe::render::cCanvas::Draw, PSBindTexture, PSBindTextureSlot.
ENGINE_API void xpe::render::context::PSUnbindTexture(const sTexture &texture)
References PSBindTexture, PSUnbindTexture.
Referenced by PSBindTexture, PSUnbindTexture.
ENGINE_API void xpe::render::context::GSBindTexture(const sTexture &texture)
References GSBindTexture.
Referenced by GSBindTexture, GSBindTexture, GSBindTexture, GSBindTextureSlot, GSUnbindTexture.
ENGINE_API void xpe::render::context::GSBindTexture(const sTexture &texture, u32 slot)
References GSBindTexture.
ENGINE_API void xpe::render::context::GSBindTextureSlot(u32 slot)
References GSBindTexture, GSBindTextureSlot.
Referenced by GSBindTexture, GSBindTextureSlot.
ENGINE_API void xpe::render::context::GSUnbindTexture(const sTexture &texture)
References GSBindTexture, GSUnbindTexture.
Referenced by GSBindTexture, GSUnbindTexture.
ENGINE_API void xpe::render::context::CSBindTexture(const sTexture &texture)
References CSBindTexture.
Referenced by CSBindTexture, CSBindTexture, CSBindTexture, CSBindTextureSlot, CSUnbindTexture.
ENGINE_API void xpe::render::context::CSBindTexture(const sTexture &texture, u32 slot)
References CSBindTexture.
ENGINE_API void xpe::render::context::CSBindTextureSlot(u32 slot)
References CSBindTexture, CSBindTextureSlot.
Referenced by CSBindTexture, CSBindTextureSlot.
ENGINE_API void xpe::render::context::CSUnbindTexture(const sTexture &texture)
References CSBindTexture, CSUnbindTexture.
Referenced by CSBindTexture, CSUnbindTexture.
ENGINE_API void xpe::render::context::VSBindSampler(const sSampler &sampler)
References VSBindSampler.
Referenced by FreeSampler, VSBindSampler, VSBindSampler, VSUnbindSampler.
ENGINE_API void xpe::render::context::VSUnbindSampler(const sSampler &sampler)
References VSBindSampler, VSUnbindSampler.
Referenced by VSBindSampler, VSUnbindSampler.
ENGINE_API void xpe::render::context::PSBindSampler(const sSampler &sampler)
References PSBindSampler.
Referenced by xpe::render::cCanvas::Draw, PSBindSampler, PSBindSampler, PSUnbindSampler, VSBindSampler.
ENGINE_API void xpe::render::context::PSUnbindSampler(const sSampler &sampler)
References PSBindSampler, PSUnbindSampler.
Referenced by PSBindSampler, PSUnbindSampler.
ENGINE_API void xpe::render::context::GSBindSampler(const sSampler &sampler)
References GSBindSampler.
Referenced by GSBindSampler, GSBindSampler, GSUnbindSampler, PSBindSampler.
ENGINE_API void xpe::render::context::GSUnbindSampler(const sSampler &sampler)
References GSBindSampler, GSUnbindSampler.
Referenced by GSBindSampler, GSUnbindSampler.
ENGINE_API void xpe::render::context::CSBindSampler(const sSampler &sampler)
References CSBindSampler.
Referenced by CSBindSampler, CSBindSampler, CSUnbindSampler, GSBindSampler.
ENGINE_API void xpe::render::context::CSUnbindSampler(const sSampler &sampler)
References CSBindSampler, CSUnbindSampler.
Referenced by CSBindSampler, CSUnbindSampler.
ENGINE_API void xpe::render::context::Init()
References Init.
Referenced by xpe::render::cRenderSystem::cRenderSystem, Init.
ENGINE_API void xpe::render::context::Free()
References Free.
Referenced by Free, xpe::render::cRenderSystem::~cRenderSystem.
ENGINE_API void xpe::render::context::CreateSwapchain(int width, int height)
References CreateSwapchain.
Referenced by CreateSwapchain.
ENGINE_API void xpe::render::context::FreeSwapchain()
References FreeSwapchain.
Referenced by FreeSwapchain.
ENGINE_API void xpe::render::context::ResizeSwapchain(sRenderTarget &presentTarget, int width, int height)
References ResizeSwapchain.
Referenced by ResizeSwapchain, xpe::render::cCanvas::WindowFrameResized.
ENGINE_API void xpe::render::context::CreateSwapchainTargetView()
References CreateSwapchainTargetView.
Referenced by CreateSwapchainTargetView.
ENGINE_API void xpe::render::context::CreateRenderTarget(sRenderTarget &renderTarget)
References CreateRenderTarget.
Referenced by CreateRenderTarget.
ENGINE_API void xpe::render::context::BindRenderTarget(const vector< void * > &colorViews, void *depthView)
References BindRenderTarget.
ENGINE_API void xpe::render::context::UnbindRenderTarget()
References UnbindRenderTarget.
Referenced by xpe::render::sRenderTarget::Unbind, UnbindRenderTarget.
ENGINE_API void xpe::render::context::ClearColorTarget(void *colorView, const glm::vec4 &color)
References ClearColorTarget.
Referenced by xpe::render::sRenderTarget::Clear, ClearColorTarget, xpe::render::cCanvas::Draw.
ENGINE_API void xpe::render::context::ClearDepthTarget(void *depthView, const f32 depth)
References ClearDepthTarget.
Referenced by xpe::render::sRenderTarget::Clear, ClearDepthTarget.
ENGINE_API void xpe::render::context::ClearStencilTarget(void *depthView, const u8 stencil)
References ClearStencilTarget.
Referenced by ClearStencilTarget.
ENGINE_API void xpe::render::context::ClearDepthStencilTarget(void *depthView, const f32 depth, const u8 stencil)
References ClearDepthStencilTarget, FreeRenderTarget.
Referenced by ClearDepthStencilTarget.
ENGINE_API void xpe::render::context::FreeRenderTargetColors(vector< sTexture * > &colors)
References FreeRenderTargetColors.
Referenced by FreeRenderTargetColors.
ENGINE_API void xpe::render::context::FreeRenderTargetColorViews(vector< void * > &colorViews)
References FreeRenderTargetColorViews.
Referenced by FreeRenderTarget, FreeRenderTargetColorViews.
ENGINE_API void xpe::render::context::FreeRenderTargetDepth(sTexture *depth)
References FreeRenderTargetDepth.
Referenced by FreeRenderTargetDepth.
ENGINE_API void xpe::render::context::FreeRenderTargetDepthView(void **depthView)
References FreeRenderTargetDepthView.
Referenced by FreeRenderTarget, FreeRenderTargetDepthView.
ENGINE_API void xpe::render::context::ResizeRenderTarget(sRenderTarget &renderTarget, int width, int height)
References ResizeRenderTarget.
Referenced by xpe::render::sRenderTarget::Resize, ResizeRenderTarget.
ENGINE_API void xpe::render::context::Present()
References Present.
Referenced by xpe::render::cCanvas::Draw, Present.
ENGINE_API void xpe::render::context::CreateShaderStage(sShaderStage &stage)
References CreateShaderStage.
Referenced by CreateShaderStage, xpe::render::cShaderManager::GetFromSrc, xpe::render::cShaderManager::ReloadStage.
ENGINE_API void xpe::render::context::FreeShaderStage(sShaderStage &stage)
References FreeShaderStage.
Referenced by FreeShaderStage, xpe::render::cShaderManager::ReloadStage.
ENGINE_API void xpe::render::context::CompileShaderStage(sShaderStage &stage)
References CompileShaderStage.
Referenced by CompileShaderStage, xpe::render::cShaderManager::GetFromSrc.
ENGINE_API void xpe::render::context::BindVSStage(const sShaderStage &stage)
References BindVSStage.
Referenced by xpe::render::cDefaultShader::Bind, BindVSStage, xpe::render::cCanvas::Draw.
ENGINE_API void xpe::render::context::BindPSStage(const sShaderStage &stage)
References BindPSStage.
Referenced by xpe::render::cDefaultShader::Bind, BindPSStage, xpe::render::cCanvas::Draw.
ENGINE_API void xpe::render::context::BindGSStage(const sShaderStage &stage)
References BindGSStage.
Referenced by xpe::render::cDefaultShader::Bind, BindGSStage.
ENGINE_API void xpe::render::context::BindCSStage(const sShaderStage &stage)
References BindCSStage.
Referenced by xpe::render::cComputeShader::Bind, BindCSStage.
ENGINE_API void xpe::render::context::UnbindVSStage(const sShaderStage &stage)
References UnbindVSStage.
Referenced by xpe::render::cDefaultShader::Unbind, UnbindVSStage.
ENGINE_API void xpe::render::context::UnbindPSStage(const sShaderStage &stage)
References UnbindPSStage.
Referenced by xpe::render::cDefaultShader::Unbind, UnbindPSStage.
ENGINE_API void xpe::render::context::UnbindGSStage(const sShaderStage &stage)
References UnbindGSStage.
Referenced by xpe::render::cDefaultShader::Unbind, UnbindGSStage.
ENGINE_API void xpe::render::context::UnbindCSStage(const sShaderStage &stage)
References UnbindCSStage.
Referenced by xpe::render::cComputeShader::Unbind, UnbindCSStage.
ENGINE_API void xpe::render::context::FreeShaderResourceView(void *viewInstance)
References CreateTexture, FreeShaderResourceView.
Referenced by FreeShaderResourceView, FreeTexture.
ENGINE_API void xpe::render::context::CreateTexture1D(sTexture &texture)
References CreateTexture1D.
Referenced by CreateTexture, CreateTexture1D.
ENGINE_API void xpe::render::context::CreateTexture2D(sTexture &texture)
References CreateTexture2D.
Referenced by CreateTexture, CreateTexture2D.
ENGINE_API void xpe::render::context::CreateTexture2DArray(sTexture &texture)
References CreateTexture2DArray.
Referenced by CreateTexture, CreateTexture2DArray.
ENGINE_API void xpe::render::context::CreateTexture3D(sTexture &texture)
References CreateTexture3D.
Referenced by CreateTexture, CreateTexture3D.
ENGINE_API void xpe::render::context::CreateTextureCube(sTexture &texture)
References CreateTextureCube.
Referenced by CreateTexture, CreateTextureCube.
ENGINE_API void xpe::render::context::CreateTextureDepthStencil(sTexture &texture)
References CreateTextureDepthStencil.
Referenced by CreateTexture, CreateTextureDepthStencil.
ENGINE_API void xpe::render::context::VSBindTexture(sTexture::eViewType viewType, u32 slot, void *viewInstance)
References VSBindTexture, VSBindTextureSlot, VSUnbindTexture.
ENGINE_API void xpe::render::context::PSBindTexture(sTexture::eViewType viewType, u32 slot, void *viewInstance)
References PSBindTexture, PSBindTextureSlot, PSUnbindTexture.
ENGINE_API void xpe::render::context::GSBindTexture(sTexture::eViewType viewType, u32 slot, void *viewInstance)
References GSBindTexture, GSBindTextureSlot, GSUnbindTexture.
ENGINE_API void xpe::render::context::CSBindTexture(sTexture::eViewType viewType, u32 slot, void *viewInstance)
References CSBindTexture, CSBindTextureSlot, CSUnbindTexture, FreeTexture.
ENGINE_API void xpe::render::context::FreeTexture1D(void *instance)
References FreeTexture1D.
Referenced by FreeTexture, FreeTexture1D.
ENGINE_API void xpe::render::context::FreeTexture2D(void *instance)
References FreeTexture2D.
Referenced by FreeTexture, FreeTexture2D.
ENGINE_API void xpe::render::context::FreeTexture2DArray(void *instance)
References FreeTexture2DArray.
Referenced by FreeTexture, FreeTexture2DArray.
ENGINE_API void xpe::render::context::FreeTexture3D(void *instance)
References FreeTexture3D.
Referenced by FreeTexture, FreeTexture3D.
ENGINE_API void xpe::render::context::FreeTextureCube(void *instance)
References FreeTextureCube.
Referenced by FreeTexture, FreeTextureCube.
ENGINE_API void xpe::render::context::FreeTextureDepthStencil(void *instance)
References CopyTexture, CopyTextureOffset, FreeTextureDepthStencil, MoveTexture, MoveTextureOffset.
Referenced by FreeTexture, FreeTextureDepthStencil.
ENGINE_API void xpe::render::context::GenerateMips(const sTexture &texture)
References GenerateMips.
Referenced by GenerateMips.
ENGINE_API void xpe::render::context::CreateSampler(sSampler &sampler)
References CreateSampler.
Referenced by CreateSampler, xpe::render::sSampler::Init.
ENGINE_API void xpe::render::context::FreeSampler(sSampler &sampler)
References FreeSampler, VSBindSampler.
Referenced by FreeSampler, xpe::render::sSampler::~sSampler.
ENGINE_API void xpe::render::context::VSBindSampler(u32 slot, void *viewInstance)
References PSBindSampler, VSBindSampler, VSUnbindSampler.
ENGINE_API void xpe::render::context::PSBindSampler(u32 slot, void *viewInstance)
References GSBindSampler, PSBindSampler, PSUnbindSampler.
ENGINE_API void xpe::render::context::GSBindSampler(u32 slot, void *viewInstance)
References CSBindSampler, GSBindSampler, GSUnbindSampler.
ENGINE_API void xpe::render::context::CSBindSampler(u32 slot, void *viewInstance)
References CSBindSampler, CSUnbindSampler.
ENGINE_API void xpe::render::context::CreateBuffer(sBuffer &buffer)
References CreateBuffer.
Referenced by CreateBuffer, xpe::render::sIndexBuffer::Recreate, xpe::render::sVertexBuffer::Recreate, xpe::render::sListBuffer< T >::Recreate, xpe::render::sIndexBuffer::sIndexBuffer, xpe::render::sIndexBuffer::sIndexBuffer, xpe::render::sItemBuffer< T >::sItemBuffer, xpe::render::sListBuffer< T >::sListBuffer, xpe::render::sVertexBuffer::sVertexBuffer, xpe::render::sVertexBuffer::sVertexBuffer.
ENGINE_API void xpe::render::context::FreeBuffer(sBuffer &buffer)
References FreeBuffer.
Referenced by FreeBuffer, xpe::render::sIndexBuffer::Recreate, xpe::render::sVertexBuffer::Recreate, xpe::render::sListBuffer< T >::Recreate, xpe::render::sIndexBuffer::~sIndexBuffer, xpe::render::sItemBuffer< T >::~sItemBuffer, xpe::render::sListBuffer< T >::~sListBuffer, xpe::render::sVertexBuffer::~sVertexBuffer.
ENGINE_API void xpe::render::context::BindVertexBuffer(const sBuffer &buffer)
References BindVertexBuffer.
Referenced by BindVertexBuffer, xpe::render::cRenderSystem::Prepare.
ENGINE_API void xpe::render::context::BindIndexBuffer(const sBuffer &buffer)
References BindIndexBuffer.
Referenced by BindIndexBuffer, xpe::render::cRenderSystem::Prepare.
ENGINE_API void xpe::render::context::VSBindBuffer(sBuffer::eViewType viewType, sBuffer::eType type, u32 slot, void *instance, void *viewInstance)
References VSBindBuffer, VSUnbindBuffer.
ENGINE_API void xpe::render::context::PSBindBuffer(sBuffer::eViewType viewType, sBuffer::eType type, u32 slot, void *instance, void *viewInstance)
References PSBindBuffer, PSUnbindBuffer.
ENGINE_API void xpe::render::context::GSBindBuffer(sBuffer::eViewType viewType, sBuffer::eType type, u32 slot, void *instance, void *viewInstance)
References GSBindBuffer, GSUnbindBuffer.
ENGINE_API void xpe::render::context::CSBindBuffer(sBuffer::eViewType viewType, sBuffer::eType type, u32 slot, void *instance, void *viewInstance)
References CopyBuffer, CopyBufferOffset, CSBindBuffer, CSUnbindBuffer, MoveBuffer, MoveBufferOffset.
ENGINE_API void * xpe::render::context::Map(const sResource &resource, u32 subresourceIndex, sResource::eMapType mapType)
References Map.
Referenced by CopyBuffer, CopyBufferOffset, CopyTexture, CopyTextureOffset, Map, MoveBuffer, MoveBufferOffset, MoveTexture, MoveTextureOffset.
ENGINE_API void xpe::render::context::Unmap(const sResource &resource)
References Unmap.
Referenced by CopyBuffer, CopyBufferOffset, CopyTexture, CopyTextureOffset, MoveBuffer, MoveBufferOffset, MoveTexture, MoveTextureOffset, Unmap.
ENGINE_API void xpe::render::context::UpdateSubData(const sResource &resource, u32 subresourceIndex, const void *data, u32 rowPitch, u32 depthPitch)
References UpdateSubData.
Referenced by CopyTexture, CopyTextureOffset, MoveTexture, MoveTextureOffset, UpdateSubData.
ENGINE_API void xpe::render::context::CreateInputLayout(sInputLayout &inputLayout)
References CreateInputLayout.
Referenced by CreateInputLayout, xpe::render::cDefaultShader::Init.
ENGINE_API void xpe::render::context::BindInputLayout(const sInputLayout &inputLayout)
References BindInputLayout.
Referenced by xpe::render::cDefaultShader::Bind, BindInputLayout.
ENGINE_API void xpe::render::context::FreeInputLayout(sInputLayout &inputLayout)
References FreeInputLayout.
Referenced by FreeInputLayout, xpe::render::cDefaultShader::~cDefaultShader.
ENGINE_API void xpe::render::context::BindPrimitiveTopology(const ePrimitiveTopology &primitiveTopology)
References BindPrimitiveTopology.
Referenced by xpe::render::cDefaultShader::Bind, BindPrimitiveTopology, xpe::render::cSkyboxShader::Draw, xpe::render::cInstancingShader::DrawInstanced.
ENGINE_API void xpe::render::context::BindViewport(sViewport *viewport)
References BindViewport.
Referenced by BindRenderTarget, BindViewport.
ENGINE_API void xpe::render::context::UnbindViewport()
References UnbindViewport.
Referenced by UnbindViewport.
ENGINE_API void xpe::render::context::CreateDepthStencilMode(sDepthStencilMode &depthStencilMode)
References CreateDepthStencilMode.
Referenced by CreateDepthStencilMode, xpe::render::cDefaultShader::Init.
ENGINE_API void xpe::render::context::BindDepthStencilMode(void *state)
References BindDepthStencilMode.
Referenced by xpe::render::cDefaultShader::Bind, BindDepthStencilMode.
ENGINE_API void xpe::render::context::FreeDepthStencilMode(sDepthStencilMode &depthStencilMode)
References FreeDepthStencilMode.
Referenced by FreeDepthStencilMode, xpe::render::cDefaultShader::~cDefaultShader.
ENGINE_API void xpe::render::context::CreateBlendMode(sBlendMode &blendMode)
References CreateBlendMode.
Referenced by CreateBlendMode, xpe::render::cDefaultShader::Init.
ENGINE_API void xpe::render::context::BindBlendMode(void *state)
References BindBlendMode.
Referenced by xpe::render::cDefaultShader::Bind, BindBlendMode.
ENGINE_API void xpe::render::context::FreeBlendMode(sBlendMode &blendMode)
References FreeBlendMode.
Referenced by FreeBlendMode, xpe::render::cDefaultShader::~cDefaultShader.
ENGINE_API void xpe::render::context::CreateRasterizer(sRasterizer &rasterizer)
References CreateRasterizer.
Referenced by CreateRasterizer, xpe::render::cDefaultShader::Init.
ENGINE_API void xpe::render::context::BindRasterizer(void *state)
References BindRasterizer.
Referenced by xpe::render::cDefaultShader::Bind, BindRasterizer.
ENGINE_API void xpe::render::context::FreeRasterizer(sRasterizer &rasterizer)
References FreeRasterizer.
Referenced by FreeRasterizer, xpe::render::cDefaultShader::~cDefaultShader.
ENGINE_API void xpe::render::context::DrawIndexed(usize indexCount, usize instanceCount=1, usize vertexOffset=0, usize indexOffset=0, usize instanceOffset=0)
References DrawIndexed.
Referenced by xpe::render::cSkyboxShader::Draw, DrawIndexed, xpe::render::cInstancingShader::DrawInstanced.
ENGINE_API void xpe::render::context::DrawVertexed(usize vertexCount, usize instanceCount=1, usize vertexOffset=0, usize instanceOffset=0)
References DrawVertexed.
Referenced by xpe::render::cInstancingShader::DrawInstanced, DrawVertexed.
ENGINE_API void xpe::render::context::DrawQuad()
References DrawQuad.
Referenced by xpe::render::cCanvas::Draw, xpe::render::cCompositeTransparentShader::Draw, xpe::render::cSsaoShader::Draw, xpe::render::cFinalShader::Draw, DrawQuad.
ENGINE_API void xpe::render::context::Dispatch(const glm::ivec3 &threadGroupCount)
References Dispatch.
Referenced by Dispatch, xpe::render::cComputeShader::Draw.
ENGINE_API void * xpe::render::context::GetDevice()
References GetDevice.
Referenced by GetDevice.
ENGINE_API void xpe::render::context::InitDebug()
References InitDebug.
Referenced by xpe::render::cDebugManager::Init, InitDebug.
ENGINE_API void xpe::render::context::FreeDebug()
References FreeDebug.
Referenced by xpe::render::cDebugManager::Free, FreeDebug.
ENGINE_API bool xpe::render::context::GetLastMessage(sDebugMessage &message)
References GetLastMessage.
Referenced by GetLastMessage, xpe::render::cDebugManager::LogLastMessage.
ENGINE_API vector< sDebugMessage > xpe::render::context::GetMessageQueue()
References GetMessageQueue.
Referenced by GetMessageQueue, xpe::render::cDebugManager::LogMessages.
ENGINE_API void xpe::render::context::ClearMessageQueue()
References ClearMessageQueue.
Referenced by ClearMessageQueue.