xpe::math
void xpe::math::clamp(T &value, const T min, const T max)
References max, min.
T xpe::math::min(const T &right, const T &left)
Referenced by clamp, xpe::render::cCamera::GetPanSpeed.
T xpe::math::max(const T &right, const T &left)
Referenced by clamp, xpe::render::cCamera::GetZoomSpeed.
xpe::math::JSON(sModelMatrix, Position, Rotation, Scale) struct ENGINE_API sViewMatrix
References xpe::core::Up.
xpe::math::JSON(sViewMatrix, Position, Front, Up) struct ENGINE_API sOrthoMatrix
References xpe::core::Left, xpe::core::Right.
xpe::math::JSON(sOrthoMatrix, Left, Right, Bottom, Top, Near, Far) struct ENGINE_API sPerspectiveMatrix