xpe::audio::context
const u32 xpe::audio::context::k_Channels
const u32 xpe::audio::context::k_NumCaptureBuffers
Referenced by xpe::audio::cAudioSystem::cAudioSystem, xpe::audio::cAudioSystem::~cAudioSystem.
const u32 xpe::audio::context::k_CaptureFrequency
Referenced by xpe::audio::cAudioSystem::cAudioSystem.
const u32 xpe::audio::context::k_CaptureBufferSize
Referenced by xpe::audio::cAudioSystem::cAudioSystem.
void* xpe::audio::context::Context
void* xpe::audio::context::PlaybackDevice
void* xpe::audio::context::RecordDevice
ENGINE_API void xpe::audio::context::InitAudio()
Referenced by xpe::audio::cAudioSystem::cAudioSystem.
ENGINE_API void xpe::audio::context::FreeAudio()
Referenced by xpe::audio::cAudioSystem::~cAudioSystem.
ENGINE_API eAudioError xpe::audio::context::GetError()
ENGINE_API void xpe::audio::context::GenSources(u32 count, u32 *sourceID)
Referenced by xpe::audio::cAudioSystem::cAudioSystem.
ENGINE_API void xpe::audio::context::GenBuffers(u32 count, u32 *bufferID)
Referenced by xpe::audio::cAudioSystem::cAudioSystem.
ENGINE_API void xpe::audio::context::DeleteSources(u32 count, u32 *sourceID)
Referenced by xpe::audio::cAudioSystem::~cAudioSystem.
ENGINE_API void xpe::audio::context::DeleteBuffers(u32 count, u32 *bufferID)
Referenced by xpe::audio::cAudioSystem::~cAudioSystem.
ENGINE_API void xpe::audio::context::PlaySource(u32 sourceID)
Referenced by xpe::audio::cAudioSystem::cAudioSystem.
ENGINE_API void xpe::audio::context::StopSource(u32 sourceID)
ENGINE_API void xpe::audio::context::bindBuffers(u32 sourceID, u32 bufferID)
ENGINE_API void xpe::audio::context::UnbindBuffers(u32 sourceID)
ENGINE_API void xpe::audio::context::UploadFileToBuffer(const sAudioFile *file, u32 bufferID)
ENGINE_API void xpe::audio::context::UpdateBuffer(const sAudioFile *file, u32 sourceID, u32 bufferID, s16 *data, s64 frames, bool processed)
ENGINE_API void xpe::audio::context::StartRecord()
Referenced by xpe::audio::cAudioManager::VoiceRecord.
ENGINE_API void xpe::audio::context::StopRecord()
Referenced by xpe::audio::cAudioManager::VoiceRecord.
ENGINE_API void xpe::audio::context::GetCaptureSamples(s32 size, s32 &samples)
ENGINE_API void xpe::audio::context::UploadSamplesToBuffer(signed char *data, s32 samples)
ENGINE_API void xpe::audio::context::UpdateBuffers(u32 source, u32 *buffer, signed char *data, s32 samples, s32 samplerate)
ENGINE_API void xpe::audio::context::AddBuffer(u32 source, u32 *buffer, signed char *data, s32 samples, s32 samplerate, u32 num)
Referenced by xpe::audio::cAudioSystem::cAudioSystem.
ENGINE_API void xpe::audio::context::SetListenerPosition(glm::vec3 position)
Referenced by xpe::audio::cAudioManager::SetListenerPosition.
ENGINE_API void xpe::audio::context::SetListenerVelocity(glm::vec3 velocity)
Referenced by xpe::audio::cAudioManager::SetListenerVelocity.
ENGINE_API void xpe::audio::context::SetListenerOrientation(glm::vec3 front, glm::vec3 up)
Referenced by xpe::audio::cAudioManager::SetListenerOrientation.
ENGINE_API void xpe::audio::context::SetListenerGain(f32 volume)
Referenced by xpe::audio::cAudioManager::SetListenerGain.
ENGINE_API void xpe::audio::context::SetListenerDopplerFactor(f32 factor)
Referenced by xpe::audio::cAudioManager::SetListenerDopplerFactor.
ENGINE_API void xpe::audio::context::SetListenerSpeedOfSound(f32 speed)
Referenced by xpe::audio::cAudioManager::SetListenerSpeedOfSound.
ENGINE_API void xpe::audio::context::SetLooping(u32 sourceID, bool Looping)
ENGINE_API void xpe::audio::context::SetPitch(u32 sourceID, f32 pitch)
ENGINE_API void xpe::audio::context::SetGain(u32 sourceID, f32 volume)
ENGINE_API void xpe::audio::context::SetPosition(u32 sourceID, glm::vec3 position)
ENGINE_API void xpe::audio::context::SetVelocity(u32 sourceID, glm::vec3 velocity)
ENGINE_API void xpe::audio::context::SetRefDistance(u32 sourceID, f32 distance)
ENGINE_API void xpe::audio::context::SetMaxDistance(u32 sourceID, f32 distance)
ENGINE_API void xpe::audio::context::SetRollOffFactor(u32 sourceID, f32 rollOffFactor)
ENGINE_API void xpe::audio::context::SetConeInnerAngle(u32 sourceID, f32 angle)
ENGINE_API void xpe::audio::context::SetConeOuterAngle(u32 sourceID, f32 angle)
ENGINE_API void xpe::audio::context::GetState(u32 sourceID, eAudioState &state)
ENGINE_API void xpe::audio::context::GetProcessed(u32 sourceID, s32 *processed)
ENGINE_API void xpe::audio::context::GetQueued(u32 sourceID, s32 *queued)
ENGINE_API int xpe::audio::context::GetFormat(const sAudioFile &file, u32 channels)
ENGINE_API u32 xpe::audio::context::GetBufferSize(u32 channels, u32 BufferSamples)
ENGINE_API void xpe::audio::context::SetCurrentFrame(SNDFILE *file, s64 frame)
ENGINE_API s64 xpe::audio::context::ReadChunk(SNDFILE *m_File, short *data, s64 num_frames)
ENGINE_API bool xpe::audio::context::isAmbisonic(const sAudioFile &file)