xpe::core
eGamepadButton
eGamepadAxis
eKey
eMouse
eCursorMode
eWindowTheme
using xpe::core::LogSinkColor = spdlog::sinks::stdout_color_sink_mt
using xpe::core::ErrorSinkColor = spdlog::sinks::stderr_color_sink_mt
using xpe::core::FileSink = spdlog::sinks::basic_file_sink_mt
using xpe::core::Sink = spdlog::sink_ptr
typedef const std::chrono::duration<double, std::milli> xpe::core::TimeMillis
using xpe::core::u8 = uint8_t
using xpe::core::s8 = int8_t
using xpe::core::u16 = uint16_t
using xpe::core::s16 = int16_t
using xpe::core::u32 = uint32_t
using xpe::core::s32 = int32_t
using xpe::core::u64 = uint64_t
using xpe::core::s64 = int64_t
using xpe::core::f32 = float
using xpe::core::f64 = double
using xpe::core::dword = u32
using xpe::core::qword = u64
using xpe::core::Boolean = u32
typedef std::basic_string<char, std::char_traits<char>, cMainAllocator<char> > xpe::core::string
typedef std::basic_string<char, std::char_traits<char>, cHotAllocator<char> > xpe::core::hstring
typedef std::basic_stringstream<char, std::char_traits<char>, cMainAllocator<char> > xpe::core::stringstream
typedef std::basic_stringstream<char, std::char_traits<char>, cHotAllocator<char> > xpe::core::hstringstream
using xpe::core::vector = std::vector<T, cMainAllocator<T>>
using xpe::core::hvector = std::vector<T, cHotAllocator<T>>
using xpe::core::array = std::array<T, Size>
using xpe::core::map = std::map<K, V, std::equal_to<K>, cMainAllocator<std::pair<K, V>>>
using xpe::core::hmap = std::map<K, V, std::equal_to<K>, cHotAllocator<std::pair<K, V>>>
using xpe::core::set = std::set<K, Comparator, cMainAllocator<K>>
using xpe::core::hset = std::set<K, Comparator, cHotAllocator<K>>
using xpe::core::unordered_set = std::unordered_set<K, std::hash<K>, std::equal_to<K>, cMainAllocator<K>>
using xpe::core::hunordered_set = std::unordered_set<K, std::hash<K>, std::equal_to<K>, cHotAllocator<K>>
using xpe::core::unordered_map = std::unordered_map<K, V, std::hash<K>, std::equal_to<K>, cMainAllocator<std::pair<K, V>>>
using xpe::core::hunordered_map = std::unordered_map<K, V, std::hash<K>, std::equal_to<K>, cHotAllocator<std::pair<K, V>>>
ratio const eKey key const eKey key const eKey key const eMouse mouse const eMouse mouse const eMouse mouse const double const double y const double xpe::core::x
Referenced by xpe::render::sAtlas::AddCell, xpe::core::cInputManager::CaptureCursor, xpe::render::cOrthoCamera::CursorMoved, xpe::render::cCamera::GetPanSpeed, xpe::physics::QuatToEuler, xpe::render::sAtlas::RemoveCell, xpe::core::cWindowManager::SetPos, xpe::render::sSphere::sSphere.
int int y int int h int xpe::core::w
Referenced by xpe::physics::QuatToEuler, xpe::core::cWindowManager::SetSize.
ratio const eKey key const eKey key const eKey key const eMouse mouse const eMouse mouse const eMouse mouse const double const double y const double const double y const u32 charUnicode const u32 xpe::core::charUnicode
ratio const eKey key const eKey key const eKey key const eMouse mouse const eMouse mouse const eMouse mouse const double const double y const double const double y const u32 charUnicode const u32 const int mods const string const string &filepath const string const string &filepath const string const string &filepath const string const string &filepath const string & xpe::core::watchpath
GLFWwindow* xpe::core::s_Window
std::shared_ptr<spdlog::logger> xpe::core::s_Logger
std::shared_ptr<spdlog::logger> xpe::core::s_Tracer
std::shared_ptr<spdlog::logger> xpe::core::s_MemLogger
const char* xpe::core::s_LogPattern
const char* xpe::core::s_TracePattern
GLFWwindow* xpe::core::s_WindowHandle
GLFWmonitor* xpe::core::s_PrimaryMonitor
std::unordered_map<GLFWmonitor*, const GLFWvidmode*> xpe::core::s_MonitorTable
const std::unordered_map<eCursorMode, int> xpe::core::k_CursorModeTable
const std::unordered_map<eWindowTheme, u8> xpe::core::k_WindowThemeTable
ENGINE_API void * xpe::core::align16_malloc(usize size)
References main_alloc.
Referenced by xpe::physics::cPhysicsAllocator::allocate.
ENGINE_API void xpe::core::align16_free(void *address)
References main_free.
Referenced by xpe::physics::cPhysicsAllocator::deallocate.
bool xpe::core::operator==(const cHotAllocator< T > &, const cHotAllocator< U > &)
bool xpe::core::operator!=(const cHotAllocator< T > &, const cHotAllocator< U > &)
bool xpe::core::operator==(const cMainAllocator< T > &, const cMainAllocator< U > &)
bool xpe::core::operator!=(const cMainAllocator< T > &, const cMainAllocator< U > &)
xpe::core::event_begin(WindowClosed) event_end(WindowClosed) event_begin(WindowMoved
int int y xpe::core::event_end(WindowMoved, x, y) event_begin(WindowResized
int int y int int h xpe::core::event_end(WindowResized, w, h) event_begin(WindowFrameResized
int int y int int h int int h xpe::core::event_end(WindowFrameResized, w, h) enum eWindowFrameResizedPriority
xpe::core::event_begin(WindowRatioChanged, float ratio) event_end(WindowRatioChanged
ratio xpe::core::event_begin(WindowFocused) event_end(WindowFocused) event_begin(WindowFocusLost) event_end(WindowFocusLost) event_begin(KeyPressed
ratio const eKey key xpe::core::event_end(KeyPressed, key) event_begin(KeyReleased
ratio const eKey key const eKey key xpe::core::event_end(KeyReleased, key) event_begin(KeyHold
ratio const eKey key const eKey key const eKey key xpe::core::event_end(KeyHold, key) event_begin(MousePressed
ratio const eKey key const eKey key const eKey key const eMouse mouse xpe::core::event_end(MousePressed, mouse) event_begin(MouseReleased
ratio const eKey key const eKey key const eKey key const eMouse mouse const eMouse mouse xpe::core::event_end(MouseReleased, mouse) event_begin(MouseHold
ratio const eKey key const eKey key const eKey key const eMouse mouse const eMouse mouse const eMouse mouse xpe::core::event_end(MouseHold, mouse) event_begin(CursorMoved
ratio const eKey key const eKey key const eKey key const eMouse mouse const eMouse mouse const eMouse mouse const double const double y xpe::core::event_end(CursorMoved, x, y) event_begin(CursorEntered) event_end(CursorEntered) event_begin(CursorLeft) event_end(CursorLeft) event_begin(ScrollChanged
ratio const eKey key const eKey key const eKey key const eMouse mouse const eMouse mouse const eMouse mouse const double const double y const double const double y xpe::core::event_end(ScrollChanged, x, y) event_begin(CharTyped
ratio const eKey key const eKey key const eKey key const eMouse mouse const eMouse mouse const eMouse mouse const double const double y const double const double y const u32 charUnicode xpe::core::event_end(CharTyped, charUnicode) event_begin(CharModsTyped
ratio const eKey key const eKey key const eKey key const eMouse mouse const eMouse mouse const eMouse mouse const double const double y const double const double y const u32 charUnicode const u32 const int mods xpe::core::event_end(CharModsTyped, charUnicode, mods) event_begin(FileAdded
ratio const eKey key const eKey key const eKey key const eMouse mouse const eMouse mouse const eMouse mouse const double const double y const double const double y const u32 charUnicode const u32 const int mods const string const string &filepath xpe::core::event_end(FileAdded, watchpath, filepath) event_begin(FileDeleted
ratio const eKey key const eKey key const eKey key const eMouse mouse const eMouse mouse const eMouse mouse const double const double y const double const double y const u32 charUnicode const u32 const int mods const string const string &filepath const string const string &filepath xpe::core::event_end(FileDeleted, watchpath, filepath) event_begin(FileModified
ratio const eKey key const eKey key const eKey key const eMouse mouse const eMouse mouse const eMouse mouse const double const double y const double const double y const u32 charUnicode const u32 const int mods const string const string &filepath const string const string &filepath const string const string &filepath xpe::core::event_end(FileModified, watchpath, filepath) event_begin(FileNewName
ratio const eKey key const eKey key const eKey key const eMouse mouse const eMouse mouse const eMouse mouse const double const double y const double const double y const u32 charUnicode const u32 const int mods const string const string &filepath const string const string &filepath const string const string &filepath const string const string &filepath xpe::core::event_end(FileNewName, watchpath, filepath) event_begin(FileOldName
ratio const eKey key const eKey key const eKey key const eMouse mouse const eMouse mouse const eMouse mouse const double const double y const double const double y const u32 charUnicode const u32 const int mods const string const string &filepath const string const string &filepath const string const string &filepath const string const string &filepath const string const string &filepath xpe::core::event_end(FileOldName, watchpath, filepath) event_begin(SampleCountChanged
static std::shared_ptr< spdlog::logger > xpe::core::CreateLogger(const char *logName, const char *filepath, const char *pattern, int backtrace)
xpe::core::JSON_ENUM(eGamepadButton, { { eGamepadButton::Pad_A, "Pad_A" }, { eGamepadButton::Pad_B, "Pad_B" }, { eGamepadButton::Pad_X, "Pad_X" }, { eGamepadButton::Pad_Y, "Pad_Y" }, { eGamepadButton::Pad_LeftBumper, "Pad_LeftBumper" }, { eGamepadButton::Pad_RightBumper, "Pad_RightBumper" }, { eGamepadButton::Pad_Back, "Pad_Back" }, { eGamepadButton::Pad_Start, "Pad_Start" }, { eGamepadButton::Pad_Guide, "Pad_Guide" }, { eGamepadButton::Pad_LeftThumb, "Pad_LeftThumb" }, { eGamepadButton::Pad_RightThumb, "Pad_RightThumb" }, { eGamepadButton::Pad_Up, "Pad_Up" }, { eGamepadButton::Pad_Right, "Pad_Right" }, { eGamepadButton::Pad_Down, "Pad_Down" }, { eGamepadButton::Pad_Left, "Pad_Left" }, { eGamepadButton::Pad_Last, "Pad_Last" }, { eGamepadButton::Pad_Cross, "Pad_Cross" }, { eGamepadButton::Pad_Circle, "Pad_Circle" }, { eGamepadButton::Pad_Square, "Pad_Square" }, { eGamepadButton::Pad_Triangle, "Pad_Triangle" }, }) JSON_ENUM(eGamepadAxis
References Pad_A, Pad_B, Pad_Back, Pad_Circle, Pad_Cross, Pad_Down, Pad_Guide, Pad_Last, Pad_Left, Pad_LeftBumper, Pad_LeftThumb, Pad_Right, Pad_RightBumper, Pad_RightThumb, Pad_Square, Pad_Start, Pad_Triangle, Pad_Up, Pad_X, Pad_Y.
xpe::core::XML_ENUM(eGamepadButton, { { eGamepadButton::Pad_A, "Pad_A" }, { eGamepadButton::Pad_B, "Pad_B" }, { eGamepadButton::Pad_X, "Pad_X" }, { eGamepadButton::Pad_Y, "Pad_Y" }, { eGamepadButton::Pad_LeftBumper, "Pad_LeftBumper" }, { eGamepadButton::Pad_RightBumper, "Pad_RightBumper" }, { eGamepadButton::Pad_Back, "Pad_Back" }, { eGamepadButton::Pad_Start, "Pad_Start" }, { eGamepadButton::Pad_Guide, "Pad_Guide" }, { eGamepadButton::Pad_LeftThumb, "Pad_LeftThumb" }, { eGamepadButton::Pad_RightThumb, "Pad_RightThumb" }, { eGamepadButton::Pad_Up, "Pad_Up" }, { eGamepadButton::Pad_Right, "Pad_Right" }, { eGamepadButton::Pad_Down, "Pad_Down" }, { eGamepadButton::Pad_Left, "Pad_Left" }, { eGamepadButton::Pad_Last, "Pad_Last" }, { eGamepadButton::Pad_Cross, "Pad_Cross" }, { eGamepadButton::Pad_Circle, "Pad_Circle" }, { eGamepadButton::Pad_Square, "Pad_Square" }, { eGamepadButton::Pad_Triangle, "Pad_Triangle" }, }) XML_ENUM(eGamepadAxis
References Pad_A, Pad_B, Pad_Back, Pad_Circle, Pad_Cross, Pad_Down, Pad_Guide, Pad_Last, Pad_Left, Pad_LeftBumper, Pad_LeftThumb, Pad_Right, Pad_RightBumper, Pad_RightThumb, Pad_Square, Pad_Start, Pad_Triangle, Pad_Up, Pad_X, Pad_Y.
ENGINE_API u64 xpe::core::Hash(const string &str)
Referenced by xpe::render::cShader::cShader, xpe::render::cShaderManager::GetFromSrc, xpe::render::cShaderManager::GetShader, xpe::render::cShaderManager::SetShaderAfter.
ENGINE_API u64 xpe::core::Hash(const hstring &str)