xpe::render::sItemBuffer
T xpe::render::sItemBuffer< T >::Item
Referenced by xpe::render::cOrthoCamera::Flush, xpe::render::cCameraManager::GetExposure, xpe::render::cCameraManager::GetGamma, xpe::render::cCameraManager::GetViewport, xpe::render::cCameraManager::GetViewProjection, xpe::render::cCameraManager::SetExposure, xpe::render::cCameraManager::SetGamma, xpe::render::cCameraManager::SetViewport.
xpe::render::sItemBuffer< T >::sItemBuffer()=default
xpe::render::sItemBuffer< T >::sItemBuffer(u32 slot, sBuffer::eSubType subtype=sBuffer::eSubType::NONE, sBuffer::eViewType viewtype=sBuffer::eViewType::NONE)
References xpe::render::context::CopyBuffer, xpe::render::context::CreateBuffer, xpe::render::sBuffer::ITEM, xpe::core::T.
xpe::render::sItemBuffer< T >::~sItemBuffer()
References xpe::render::context::FreeBuffer.
void xpe::render::sItemBuffer< T >::Flush()
References xpe::render::context::CopyBuffer.
Referenced by xpe::render::cOrthoCamera::Flush, xpe::render::cCameraManager::Flush, xpe::render::cShadowManager::Flush, xpe::render::cCameraManager::SetExposure, xpe::render::cCameraManager::SetGamma, xpe::render::cCameraManager::SetViewport, xpe::render::cOrthoCamera::WindowResized.
void xpe::render::sItemBuffer< T >::FlushItem(const T &item)
References xpe::render::context::CopyBuffer.