xpe::render::sTextureLayer
eTextureFormat xpe::render::sTextureLayer::Format
Referenced by CopyFrom, GenerateMipsFloat, GenerateMipsU8, ResizePixelsFloat, ResizePixelsU8.
s32 xpe::render::sTextureLayer::Width
Referenced by CopyFrom, ResizeFloat, ResizeU8.
s32 xpe::render::sTextureLayer::Height
Referenced by CopyFrom, ResizeFloat, ResizeU8.
void* xpe::render::sTextureLayer::Pixels
Referenced by CopyFrom, xpe::render::sTexture::CreateLayer, Free, GenerateMips, GenerateMipsFloat, GenerateMipsU8, ResizeFloat, ResizeU8.
vector<sMip> xpe::render::sTextureLayer::Mips
Referenced by FreeMips, GenerateMipsFloat, GenerateMipsU8, ResizeFloat, ResizeU8.
xpe::render::sTextureLayer::sTextureLayer()=default
xpe::render::sTextureLayer::sTextureLayer(eTextureFormat format, s32 width, s32 height, void *pixels)
void xpe::render::sTextureLayer::Free()
References FreeMips, main_free, Pixels.
void xpe::render::sTextureLayer::CopyFrom(const sTextureLayer &other)
References Format, Height, xpe::render::sTexture::k_BppTable, main_alloc, main_free, Pixels, Width.
Referenced by Clone.
sTextureLayer xpe::render::sTextureLayer::Clone() const
References CopyFrom.
Referenced by xpe::render::sAtlas::AddCell.
void xpe::render::sTextureLayer::GenerateMips(const eTextureFormat &format, int width, int height)
References GenerateMipsFloat, GenerateMipsU8, Pixels, xpe::render::R32, xpe::render::R32_TYPELESS, xpe::render::R8, xpe::render::RG32, xpe::render::RG8, xpe::render::RGB32, xpe::render::RGB8, xpe::render::RGBA32, xpe::render::RGBA8, xpe::render::SRGBA8.
void xpe::render::sTextureLayer::GenerateMipsU8(int width, int height)
References Format, Mips, Pixels, ResizePixelsU8.
Referenced by GenerateMips, ResizeU8.
void xpe::render::sTextureLayer::GenerateMipsFloat(int width, int height)
References Format, Mips, Pixels, ResizePixelsFloat.
Referenced by GenerateMips, ResizeFloat.
void xpe::render::sTextureLayer::FreeMips()
References main_free, Mips.
Referenced by Free, ResizeFloat, ResizeU8.
void xpe::render::sTextureLayer::Resize(const eTextureFormat &format, s32 width, s32 height)
References xpe::render::R32, xpe::render::R8, ResizeFloat, ResizeU8, xpe::render::RG32, xpe::render::RG8, xpe::render::RGB32, xpe::render::RGB8, xpe::render::RGBA32, xpe::render::RGBA8, xpe::render::SRGBA8.
Referenced by xpe::render::sAtlas::AddCell.
void xpe::render::sTextureLayer::ResizeU8(s32 width, s32 height)
References FreeMips, GenerateMipsU8, Height, Mips, Pixels, ResizePixelsU8, Width.
Referenced by Resize.
void xpe::render::sTextureLayer::ResizeFloat(s32 width, s32 height)
References FreeMips, GenerateMipsFloat, Height, Mips, Pixels, ResizePixelsFloat, Width.
Referenced by Resize.
void * xpe::render::sTextureLayer::ResizePixelsU8(const void *inputPixels, int inputWidth, int inputHeight, int outputWidth, int outputHeight)
References Format, xpe::render::sTexture::k_ChannelTable, main_allocT.
Referenced by GenerateMipsU8, ResizeU8.
void * xpe::render::sTextureLayer::ResizePixelsFloat(const void *inputPixels, int inputWidth, int inputHeight, int outputWidth, int outputHeight)
References Format, xpe::render::sTexture::k_ChannelTable, main_allocT.
Referenced by GenerateMipsFloat, ResizeFloat.