xpe::render::sIndexBuffer
vector<u32> xpe::render::sIndexBuffer::List
Referenced by AddIndices, Flush, FlushIndex, FlushIndices, Recreate, Reserve, Resize, sIndexBuffer, sIndexBuffer.
xpe::render::sIndexBuffer::sIndexBuffer(const usize indexCount=0, sBuffer::eSubType subtype=sBuffer::eSubType::NONE, sBuffer::eViewType viewtype=sBuffer::eViewType::NONE)
References xpe::render::context::CreateBuffer, xpe::render::sBuffer::INDEX, xpe::render::sBuffer::InitialData, List, xpe::render::sBuffer::NumElements, xpe::render::sBuffer::StructureSize, xpe::render::sBuffer::SubType, xpe::render::sBuffer::Type, xpe::render::sResource::ViewType.
xpe::render::sIndexBuffer::sIndexBuffer(const vector< u32 > &indexArray, sBuffer::eSubType subtype=sBuffer::eSubType::NONE, sBuffer::eViewType viewtype=sBuffer::eViewType::NONE)
References xpe::render::context::CreateBuffer, Flush, xpe::render::sBuffer::INDEX, xpe::render::sBuffer::InitialData, List, xpe::render::sBuffer::NumElements, xpe::render::sBuffer::StructureSize, xpe::render::sBuffer::SubType, xpe::render::sBuffer::Type, xpe::render::sResource::ViewType.
xpe::render::sIndexBuffer::~sIndexBuffer()
References xpe::render::context::FreeBuffer.
void xpe::render::sIndexBuffer::Flush()
References xpe::render::context::CopyBuffer, xpe::render::sBuffer::GetByteSize, List, xpe::render::sBuffer::NumElements, Recreate.
Referenced by xpe::render::cGeometryManager::AddGeometry, FlushIndices, sIndexBuffer.
void xpe::render::sIndexBuffer::FlushIndices(const vector< u32 > &indices)
References Flush, xpe::render::sBuffer::GetByteSize, List, Resize.
void xpe::render::sIndexBuffer::FlushIndex(u32 i, u32 index)
References List, xpe::render::context::MoveBufferOffset, Resize, xpe::render::sBuffer::StructureSize.
void xpe::render::sIndexBuffer::Resize(const usize count)
References List.
Referenced by FlushIndex, FlushIndices.
void xpe::render::sIndexBuffer::Reserve(const usize count)
References List.
void xpe::render::sIndexBuffer::Recreate(const usize count)
References xpe::render::context::CopyBuffer, xpe::render::context::CreateBuffer, xpe::render::context::FreeBuffer, xpe::render::sBuffer::GetByteSize, xpe::render::sBuffer::InitialData, List, xpe::render::sBuffer::NumElements, xpe::render::sBuffer::StructureSize.
Referenced by Flush.
usize xpe::render::sIndexBuffer::AddIndices(const vector< u32 > &indices)
References List.
Referenced by xpe::render::cGeometryManager::AddGeometry.
u32 * xpe::render::sIndexBuffer::GetIndex(const u32 i)
usize xpe::render::sIndexBuffer::Count()