xpe::render::sTexture
eType
eUsage
const std::unordered_map< eTextureFormat, int > xpe::render::sTexture::k_ChannelTable
Referenced by xpe::render::sAtlas::AddCell, xpe::render::sAtlas::RemoveCell, xpe::render::sTextureLayer::ResizePixelsFloat, xpe::render::sTextureLayer::ResizePixelsU8.
const std::unordered_map< eTextureFormat, int > xpe::render::sTexture::k_BppTable
Referenced by xpe::render::sAtlas::AddCell, xpe::render::sTextureLayer::CopyFrom, CreateLayer, Flip, FlushLayer, xpe::render::sAtlas::RemoveCell.
eType xpe::render::sTexture::Type
Referenced by xpe::render::cWidgetManager::Init.
eUsage xpe::render::sTexture::Usage
Referenced by xpe::render::cWidgetManager::Init.
s32 xpe::render::sTexture::Width
Referenced by CreateLayer, Flip, FlushLayer, GenerateMips, xpe::render::cWidgetManager::Init, Resize, ResizePixels.
s32 xpe::render::sTexture::Height
Referenced by CreateLayer, Flip, FlushLayer, GenerateMips, xpe::render::cWidgetManager::Init, Resize, ResizePixels.
s32 xpe::render::sTexture::Depth
s32 xpe::render::sTexture::Channels
Referenced by xpe::render::sAtlas::AddCell, xpe::render::cWidgetManager::Init, xpe::render::sAtlas::RemoveCell.
eTextureFormat xpe::render::sTexture::Format
Referenced by xpe::render::sAtlas::AddCell, CreateLayer, Flip, FlushLayer, GenerateMips, xpe::render::cWidgetManager::Init, xpe::render::sAtlas::RemoveCell, ResizePixels.
u32 xpe::render::sTexture::SampleCount
bool xpe::render::sTexture::EnableRenderTarget
u32 xpe::render::sTexture::Slot
Referenced by xpe::render::cWidgetManager::Init.
u32 xpe::render::sTexture::MostDetailedMip
bool xpe::render::sTexture::InitializeData
Referenced by xpe::render::cWidgetManager::Init.
vector<sTextureLayer> xpe::render::sTexture::Layers
Referenced by xpe::render::sAtlas::AddCell, xpe::render::sAtlas::AddLayer, xpe::render::cMaterialManager::Clear, Flip, FlushLayer, GenerateMips, GetMipLevels, xpe::render::sAtlas::RemoveCell, RemoveLayerAt, ~sTexture.
bool xpe::render::sTexture::m_Resizable
xpe::render::sTexture::sTexture()
References xpe::render::sResource::SRV, xpe::render::sResource::ViewType.
xpe::render::sTexture::~sTexture()
References Free, Layers.
void xpe::render::sTexture::Init()
References xpe::render::context::CreateTexture.
Referenced by xpe::render::cWidgetManager::Init.
void xpe::render::sTexture::Free()
References xpe::render::context::FreeTexture, RemoveWindowFrameResized.
Referenced by ~sTexture.
sTextureLayer xpe::render::sTexture::CreateLayer() const
References Format, Height, k_BppTable, main_alloc, xpe::render::sTextureLayer::Pixels, Width.
Referenced by xpe::render::sAtlas::AddLayer.
void xpe::render::sTexture::RemoveLayerAt(u32 index)
References Layers.
u32 xpe::render::sTexture::GetMipLevels() const
References Layers.
void xpe::render::sTexture::WindowFrameResized(s32 width, s32 height)
References Resize.
void xpe::render::sTexture::Resize(s32 width, s32 height)
References xpe::render::context::CreateTexture, xpe::render::context::FreeTexture, Height, Width.
Referenced by xpe::render::cRenderSystem::WindowFrameResized, WindowFrameResized.
void xpe::render::sTexture::ResizePixels(s32 width, s32 height)
References Format, Height, xpe::render::R32, xpe::render::R8, xpe::render::RG32, xpe::render::RG8, xpe::render::RGB32, xpe::render::RGB8, xpe::render::RGBA32, xpe::render::RGBA8, xpe::render::SRGBA8, Width.
void xpe::render::sTexture::Flip()
References Format, Height, k_BppTable, Layers, Width.
void xpe::render::sTexture::GenerateMips()
References Format, Height, Layers, Width.
void xpe::render::sTexture::FlushLayer(u32 index)
References xpe::render::context::CopyTexture, Format, Height, k_BppTable, Layers, Width.
void xpe::render::sTexture::Flush()
References xpe::render::context::CreateTexture, xpe::render::context::FreeTexture.
Referenced by xpe::render::cMaterialManager::Clear.
void xpe::render::sTexture::SetResizable(bool resizable)
References AddWindowFrameResized, RemoveWindowFrameResized.
bool xpe::render::sTexture::IsResizable() const
u32 xpe::render::sTexture::GetMipsLevels(s32 width)
void xpe::render::sTexture::ResizeTextureU8(s32 width, s32 height)
void xpe::render::sTexture::ResizeTextureFloat(s32 width, s32 height)