xpe::render::sRenderTarget
vector<void*> xpe::render::sRenderTarget::ColorViews
Referenced by Bind, Clear, xpe::render::cCanvas::Draw, sRenderTarget, sRenderTarget, sRenderTarget.
void* xpe::render::sRenderTarget::DepthStencilView
Referenced by Bind, Clear, xpe::render::cCanvas::Draw, sRenderTarget, sRenderTarget.
vector<sTexture*> xpe::render::sRenderTarget::Colors
Referenced by BindColor, xpe::render::cShadowManager::Free, ResizeColors, sRenderTarget, sRenderTarget.
sTexture* xpe::render::sRenderTarget::DepthStencil
Referenced by BindDepth, xpe::render::cShadowManager::Free, sRenderTarget, sRenderTarget, xpe::render::cRenderSystem::WindowFrameResized.
sViewport* xpe::render::sRenderTarget::Viewport
Referenced by xpe::render::cCanvas::Draw, sRenderTarget, sRenderTarget, sRenderTarget, sRenderTarget.
vector<glm::vec4> xpe::render::sRenderTarget::ClearColors
Referenced by Clear, xpe::render::cSsaoShader::cSsaoShader, xpe::render::cShadowManager::Init.
float xpe::render::sRenderTarget::ClearDepth
Referenced by Clear, xpe::render::cSsaoShader::cSsaoShader, xpe::render::cShadowManager::Init.
bool xpe::render::sRenderTarget::m_Resizable
xpe::render::sRenderTarget::sRenderTarget(const vector< sTexture * > &colors, sViewport *viewport)
References Colors, ColorViews, Viewport.
xpe::render::sRenderTarget::sRenderTarget(const sTexture *depthStencil, sViewport *viewport)
References DepthStencil, DepthStencilView, Viewport.
xpe::render::sRenderTarget::sRenderTarget(const vector< sTexture * > &colors, const sTexture *depthStencil, sViewport *viewport)
References Colors, ColorViews, DepthStencil, DepthStencilView, Viewport.
xpe::render::sRenderTarget::sRenderTarget(const vector< void * > &colorViews, sViewport *viewport)
References ColorViews, Viewport.
xpe::render::sRenderTarget::~sRenderTarget()
References xpe::render::context::FreeRenderTarget, RemoveWindowFrameResized.
void xpe::render::sRenderTarget::Resize(s32 width, s32 height)
References xpe::render::context::ResizeRenderTarget.
Referenced by xpe::render::cRenderSystem::WindowFrameResized, WindowFrameResized.
void xpe::render::sRenderTarget::ResizeColors(s32 width, s32 height)
References Colors.
Referenced by xpe::render::cRenderSystem::WindowFrameResized.
void xpe::render::sRenderTarget::Bind()
References xpe::render::context::BindRenderTarget, ColorViews, DepthStencilView.
Referenced by xpe::render::cDefaultShader::Bind.
void xpe::render::sRenderTarget::BindColor(u32 index)
References Colors, xpe::render::context::PSBindTexture.
void xpe::render::sRenderTarget::BindDepth()
References DepthStencil, xpe::render::context::PSBindTexture.
void xpe::render::sRenderTarget::Unbind()
References xpe::render::context::UnbindRenderTarget.
Referenced by xpe::render::cDefaultShader::Unbind.
void xpe::render::sRenderTarget::WindowFrameResized(s32 width, s32 height)
References Resize.
void xpe::render::sRenderTarget::Clear()
References ClearColors, xpe::render::context::ClearColorTarget, ClearDepth, xpe::render::context::ClearDepthTarget, ColorViews, DepthStencilView, K_DEPTH_INVALID.
Referenced by xpe::core::cApp::Render.
void xpe::render::sRenderTarget::SetResizable(bool resizable)
References AddWindowFrameResized, RemoveWindowFrameResized.
Referenced by xpe::render::cSsaoShader::cSsaoShader, xpe::render::cShadowManager::Init.
bool xpe::render::sRenderTarget::IsResizable() const
void xpe::render::sRenderTarget::Init()