xpe::render::sShaderStage
eType
u64 xpe::render::sShaderStage::ID
eType xpe::render::sShaderStage::Type
sBlob xpe::render::sShaderStage::Blob
Referenced by xpe::render::cDefaultShader::Init.
uword xpe::render::sShaderStage::Flag
bool xpe::render::sShaderStage::Compiled
string xpe::render::sShaderStage::Profile
string xpe::render::sShaderStage::EntryPoint
string xpe::render::sShaderStage::Source
vector<sBuffer*> xpe::render::sShaderStage::Buffers
vector<sTexture*> xpe::render::sShaderStage::Textures
vector<sSampler*> xpe::render::sShaderStage::Samplers
xpe::render::sShaderStage::sShaderStage()=default
xpe::render::sShaderStage::sShaderStage(u64 id, eType type)
void xpe::render::sShaderStage::SetBuffer(sBuffer *buffer, u32 slot=K_SLOT_DEFAULT)
References K_SLOT_DEFAULT.
Referenced by xpe::render::cDirectionalShadowShader::cDirectionalShadowShader, xpe::render::cFinalShader::cFinalShader, xpe::render::cOpaqueShader::cOpaqueShader, xpe::render::cPointShadowShader::cPointShadowShader, xpe::render::cSkyboxShader::cSkyboxShader, xpe::render::cSpotShadowShader::cSpotShadowShader, xpe::render::cSsaoShader::cSsaoShader, xpe::render::cTextShader::cTextShader, xpe::render::cTransparentShader::cTransparentShader, xpe::render::cWidgetShader::cWidgetShader.
void xpe::render::sShaderStage::SetTexture(sTexture *texture, u32 slot=K_SLOT_DEFAULT)
References K_SLOT_DEFAULT.
Referenced by xpe::render::cCompositeTransparentShader::cCompositeTransparentShader, xpe::render::cFinalShader::cFinalShader, xpe::render::cOpaqueShader::cOpaqueShader, xpe::render::cSsaoShader::cSsaoShader, xpe::render::cTransparentShader::cTransparentShader, xpe::render::cWidgetShader::cWidgetShader.
void xpe::render::sShaderStage::SetSampler(sSampler *sampler, u32 slot=K_SLOT_DEFAULT)
References K_SLOT_DEFAULT.
Referenced by xpe::render::cOpaqueShader::cOpaqueShader, xpe::render::cSkyboxShader::cSkyboxShader, xpe::render::cTextShader::cTextShader, xpe::render::cTransparentShader::cTransparentShader, xpe::render::cWidgetShader::cWidgetShader.