xpe::render::sVertexBuffer
vector<sVertex> xpe::render::sVertexBuffer::List
Referenced by AddVertices, Clear, Flush, FlushVertex, FlushVertices, Recreate, Reserve, Resize, sVertexBuffer, sVertexBuffer.
xpe::render::sVertexBuffer::sVertexBuffer(const usize vertexCount=0, sBuffer::eSubType subtype=sBuffer::eSubType::NONE, sBuffer::eViewType viewtype=sBuffer::eViewType::NONE)
References xpe::render::context::CreateBuffer, xpe::render::sBuffer::InitialData, List, xpe::render::sBuffer::NumElements, xpe::render::sBuffer::StructureSize, xpe::render::sBuffer::SubType, xpe::render::sBuffer::Type, xpe::render::sBuffer::VERTEX, xpe::render::sResource::ViewType.
xpe::render::sVertexBuffer::sVertexBuffer(const vector< sVertex > &vertices, sBuffer::eSubType subtype=sBuffer::eSubType::NONE, sBuffer::eViewType viewtype=sBuffer::eViewType::NONE)
References xpe::render::context::CreateBuffer, Flush, xpe::render::sBuffer::InitialData, List, xpe::render::sBuffer::NumElements, xpe::render::sBuffer::StructureSize, xpe::render::sBuffer::SubType, xpe::render::sBuffer::Type, xpe::render::sBuffer::VERTEX, xpe::render::sResource::ViewType.
xpe::render::sVertexBuffer::~sVertexBuffer()
References xpe::render::context::FreeBuffer.
void xpe::render::sVertexBuffer::Flush()
References xpe::render::context::CopyBuffer, xpe::render::sBuffer::GetByteSize, List, xpe::render::sBuffer::NumElements, Recreate.
Referenced by xpe::render::cGeometryManager::AddGeometry, FlushVertices, sVertexBuffer.
void xpe::render::sVertexBuffer::FlushVertex(u32 index, const sVertex &item)
References List, xpe::render::context::MoveBufferOffset, Resize, xpe::render::sBuffer::StructureSize.
void xpe::render::sVertexBuffer::FlushVertices(const vector< sVertex > &vertices)
References Flush, xpe::render::sBuffer::GetByteSize, List, Resize.
void xpe::render::sVertexBuffer::Resize(const usize count)
References List.
Referenced by FlushVertex, FlushVertices.
void xpe::render::sVertexBuffer::Reserve(const usize count)
References List.
void xpe::render::sVertexBuffer::Recreate(const usize count)
References xpe::render::context::CopyBuffer, xpe::render::context::CreateBuffer, xpe::render::context::FreeBuffer, xpe::render::sBuffer::GetByteSize, xpe::render::sBuffer::InitialData, List, xpe::render::sBuffer::NumElements, xpe::render::sBuffer::StructureSize.
Referenced by Flush.
void xpe::render::sVertexBuffer::Clear()
References List.
usize xpe::render::sVertexBuffer::AddVertices(const vector< sVertex > &vertices)
References List.
Referenced by xpe::render::cGeometryManager::AddGeometry.
sVertex * xpe::render::sVertexBuffer::GetVertex(const u32 index)
usize xpe::render::sVertexBuffer::Count()