.TH "engine/src/anim/anim_system.cpp" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
engine/src/anim/anim_system.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <anim/anim_system\&.hpp>\fP
.br
\fR#include <anim/skeleton_manager\&.hpp>\fP
.br
\fR#include <ecs/components\&.hpp>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBxpe\fP"
.br
.ti -1c
.RI "namespace \fBxpe::anim\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
