.TH "engine/src/anim/anim.hpp" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
engine/src/anim/anim.hpp
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBxpe::anim::sKeyPosition\fP"
.br
.ti -1c
.RI "struct \fBxpe::anim::sKeyRotate\fP"
.br
.ti -1c
.RI "struct \fBxpe::anim::sKeyScale\fP"
.br
.ti -1c
.RI "struct \fBxpe::anim::sAnimationNode\fP"
.br
.ti -1c
.RI "struct \fBxpe::anim::sAnimation\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBxpe\fP"
.br
.ti -1c
.RI "namespace \fBxpe::anim\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
