.TH "engine/src/core/app.cpp" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
engine/src/core/app.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <core/app\&.hpp>\fP
.br
\fR#include <rendering/core/debugger\&.hpp>\fP
.br
\fR#include <rendering/render_system\&.hpp>\fP
.br
\fR#include <rendering/canvas\&.hpp>\fP
.br
\fR#include <rendering/bindings\&.hpp>\fP
.br
\fR#include <rendering/shaders\&.hpp>\fP
.br
\fR#include <anim/anim_system\&.hpp>\fP
.br
\fR#include <audio/audio_system\&.hpp>\fP
.br
\fR#include <physics/physics_manager\&.hpp>\fP
.br
\fR#include <physics/physics_system\&.hpp>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBxpe\fP"
.br
.ti -1c
.RI "namespace \fBxpe::core\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
