.TH "engine/src/rendering/buffers.hpp" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
engine/src/rendering/buffers.hpp
.SH SYNOPSIS
.br
.PP
\fR#include <rendering/core/context\&.hpp>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBxpe::render::sIndexBuffer\fP"
.br
.ti -1c
.RI "struct \fBxpe::render::sVertexBuffer\fP"
.br
.ti -1c
.RI "struct \fBxpe::render::sItemBuffer< T >\fP"
.br
.ti -1c
.RI "class \fBxpe::render::sListBuffer< T >\fP"
.br
.ti -1c
.RI "struct \fBxpe::render::sCameraData\fP"
.br
.ti -1c
.RI "struct \fBxpe::render::sCameraBuffer\fP"
.br
.ti -1c
.RI "struct \fBxpe::render::sRenderInstance\fP"
.br
.ti -1c
.RI "struct \fBxpe::render::sInstanceBuffer\fP"
.br
.ti -1c
.RI "struct \fBxpe::render::sDirectLightData\fP"
.br
.ti -1c
.RI "struct \fBxpe::render::sDirectLightBuffer\fP"
.br
.ti -1c
.RI "struct \fBxpe::render::sPointLightData\fP"
.br
.ti -1c
.RI "struct \fBxpe::render::sPointLightBuffer\fP"
.br
.ti -1c
.RI "struct \fBxpe::render::sSpotLightData\fP"
.br
.ti -1c
.RI "struct \fBxpe::render::sSpotLightBuffer\fP"
.br
.ti -1c
.RI "struct \fBxpe::render::sMaterialData\fP"
.br
.ti -1c
.RI "struct \fBxpe::render::sMaterialDataBuffer\fP"
.br
.ti -1c
.RI "struct \fBxpe::render::sShadowPcf\fP"
.br
.ti -1c
.RI "struct \fBxpe::render::sShadowPcfBuffer\fP"
.br
.ti -1c
.RI "struct \fBxpe::render::sSkeletonData\fP"
.br
.ti -1c
.RI "struct \fBxpe::render::sSkeletonBuffer\fP"
.br
.ti -1c
.RI "struct \fBxpe::render::sSsaoData\fP"
.br
.ti -1c
.RI "struct \fBxpe::render::sSsaoBuffer\fP"
.br
.ti -1c
.RI "struct \fBxpe::render::sWidgetData\fP"
.br
.ti -1c
.RI "struct \fBxpe::render::sWidgetBuffer\fP"
.br
.ti -1c
.RI "struct \fBxpe::render::sChar\fP"
.br
.ti -1c
.RI "struct \fBxpe::render::sCharBuffer\fP"
.br
.ti -1c
.RI "struct \fBxpe::render::sText\fP"
.br
.ti -1c
.RI "struct \fBxpe::render::sTextBuffer\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBxpe\fP"
.br
.ti -1c
.RI "namespace \fBxpe::render\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
