.TH "engine/src Directory Reference" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
engine/src Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBanim\fP"
.br
.ti -1c
.RI "directory \fBaudio\fP"
.br
.ti -1c
.RI "directory \fBcore\fP"
.br
.ti -1c
.RI "directory \fBecs\fP"
.br
.ti -1c
.RI "directory \fBmath\fP"
.br
.ti -1c
.RI "directory \fBphysics\fP"
.br
.ti -1c
.RI "directory \fBplatform\fP"
.br
.ti -1c
.RI "directory \fBrendering\fP"
.br
.ti -1c
.RI "directory \fBres\fP"
.br
.ti -1c
.RI "directory \fBstl\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBlauncher\&.hpp\fP"
.br
.ti -1c
.RI "file \fBpch\&.hpp\fP"
.br
.in -1c
