.TH "engine/src/rendering/geometry Directory Reference" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
engine/src/rendering/geometry Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBgeometries\&.cpp\fP"
.br
.ti -1c
.RI "file \fBgeometries\&.hpp\fP"
.br
.ti -1c
.RI "file \fBgeometry\&.hpp\fP"
.br
.ti -1c
.RI "file \fBgeometry_manager\&.cpp\fP"
.br
.ti -1c
.RI "file \fBgeometry_manager\&.hpp\fP"
.br
.in -1c
