.TH "engine/src/anim Directory Reference" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
engine/src/anim Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBanim\&.hpp\fP"
.br
.ti -1c
.RI "file \fBanim_system\&.cpp\fP"
.br
.ti -1c
.RI "file \fBanim_system\&.hpp\fP"
.br
.ti -1c
.RI "file \fBskeleton\&.hpp\fP"
.br
.ti -1c
.RI "file \fBskeleton_manager\&.cpp\fP"
.br
.ti -1c
.RI "file \fBskeleton_manager\&.hpp\fP"
.br
.in -1c
