.TH "engine/src/audio Directory Reference" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
engine/src/audio Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBcore\fP"
.br
.ti -1c
.RI "directory \fBopenal\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBaudio_manager\&.cpp\fP"
.br
.ti -1c
.RI "file \fBaudio_manager\&.hpp\fP"
.br
.ti -1c
.RI "file \fBaudio_system\&.cpp\fP"
.br
.ti -1c
.RI "file \fBaudio_system\&.hpp\fP"
.br
.in -1c
