.TH "engine/src/math Directory Reference" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
engine/src/math Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBmath\&.hpp\fP"
.br
.ti -1c
.RI "file \fBmath_manager\&.cpp\fP"
.br
.ti -1c
.RI "file \fBmath_manager\&.hpp\fP"
.br
.ti -1c
.RI "file \fBmatrices\&.hpp\fP"
.br
.ti -1c
.RI "file \fBray\&.hpp\fP"
.br
.ti -1c
.RI "file \fBtransform\&.hpp\fP"
.br
.in -1c
