.TH "engine/src/rendering/material Directory Reference" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
engine/src/rendering/material Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBmaterial\&.cpp\fP"
.br
.ti -1c
.RI "file \fBmaterial\&.hpp\fP"
.br
.ti -1c
.RI "file \fBmaterial_manager\&.cpp\fP"
.br
.ti -1c
.RI "file \fBmaterial_manager\&.hpp\fP"
.br
.in -1c
