.TH "engine/src/rendering Directory Reference" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
engine/src/rendering Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBcore\fP"
.br
.ti -1c
.RI "directory \fBdx11\fP"
.br
.ti -1c
.RI "directory \fBfont\fP"
.br
.ti -1c
.RI "directory \fBgeometry\fP"
.br
.ti -1c
.RI "directory \fBmaterial\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBbindings\&.cpp\fP"
.br
.ti -1c
.RI "file \fBbindings\&.hpp\fP"
.br
.ti -1c
.RI "file \fBbuffers\&.cpp\fP"
.br
.ti -1c
.RI "file \fBbuffers\&.hpp\fP"
.br
.ti -1c
.RI "file \fBcamera\&.cpp\fP"
.br
.ti -1c
.RI "file \fBcamera\&.hpp\fP"
.br
.ti -1c
.RI "file \fBcamera_manager\&.cpp\fP"
.br
.ti -1c
.RI "file \fBcamera_manager\&.hpp\fP"
.br
.ti -1c
.RI "file \fBcanvas\&.cpp\fP"
.br
.ti -1c
.RI "file \fBcanvas\&.hpp\fP"
.br
.ti -1c
.RI "file \fBrender_system\&.cpp\fP"
.br
.ti -1c
.RI "file \fBrender_system\&.hpp\fP"
.br
.ti -1c
.RI "file \fBshaders\&.cpp\fP"
.br
.ti -1c
.RI "file \fBshaders\&.hpp\fP"
.br
.ti -1c
.RI "file \fBshadow_manager\&.cpp\fP"
.br
.ti -1c
.RI "file \fBshadow_manager\&.hpp\fP"
.br
.ti -1c
.RI "file \fBskybox_manager\&.cpp\fP"
.br
.ti -1c
.RI "file \fBskybox_manager\&.hpp\fP"
.br
.ti -1c
.RI "file \fBwidget_manager\&.cpp\fP"
.br
.ti -1c
.RI "file \fBwidget_manager\&.hpp\fP"
.br
.in -1c
