.TH "engine/src/core/codes_mouse.hpp" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
engine/src/core/codes_mouse.hpp
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBxpe::core::sMouseState\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBxpe\fP"
.br
.ti -1c
.RI "namespace \fBxpe::core\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBxpe::core::eMouse\fP : u8 { \fBxpe::core::NoneButton\fP = 16, \fBxpe::core::Button0\fP = 0, \fBxpe::core::Button1\fP = 1, \fBxpe::core::Button2\fP = 2, \fBxpe::core::Button3\fP = 3, \fBxpe::core::Button4\fP = 4, \fBxpe::core::Button5\fP = 5, \fBxpe::core::Button6\fP = 6, \fBxpe::core::Button7\fP = 7, \fBxpe::core::ButtonLast\fP = Button7, \fBxpe::core::ButtonLeft\fP = Button0, \fBxpe::core::ButtonRight\fP = Button1, \fBxpe::core::ButtonMiddle\fP = Button2 }"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
