.TH "engine/src/ecs/components.hpp" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
engine/src/ecs/components.hpp
.SH SYNOPSIS
.br
.PP
\fR#include <rendering/geometry/geometries\&.hpp>\fP
.br
\fR#include <rendering/material/material\&.hpp>\fP
.br
\fR#include <rendering/buffers\&.hpp>\fP
.br
\fR#include <rendering/font/font\&.hpp>\fP
.br
\fR#include <rendering/widget_manager\&.hpp>\fP
.br
\fR#include <anim/skeleton\&.hpp>\fP
.br
\fR#include <audio/core/context\&.hpp>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBxpe::ecs::CSpace2D\fP"
.br
.ti -1c
.RI "struct \fBxpe::ecs::CSpace3D\fP"
.br
.ti -1c
.RI "struct \fBxpe::ecs::CTag\fP"
.br
.ti -1c
.RI "struct \fBxpe::ecs::CTransform\fP"
.br
.ti -1c
.RI "struct \fBxpe::ecs::CVisible\fP"
.br
.ti -1c
.RI "struct \fBxpe::ecs::COpaque\fP"
.br
.ti -1c
.RI "struct \fBxpe::ecs::CTransparent\fP"
.br
.ti -1c
.RI "struct \fBxpe::ecs::CHasShadow\fP"
.br
.ti -1c
.RI "struct \fBxpe::ecs::CCamera\fP"
.br
.ti -1c
.RI "struct \fBxpe::ecs::CPerspectiveCamera\fP"
.br
.ti -1c
.RI "struct \fBxpe::ecs::COrthoCamera\fP"
.br
.ti -1c
.RI "struct \fBxpe::ecs::CMaterial\fP"
.br
.ti -1c
.RI "struct \fBxpe::ecs::CDirectionalLight\fP"
.br
.ti -1c
.RI "struct \fBxpe::ecs::CPointLight\fP"
.br
.ti -1c
.RI "struct \fBxpe::ecs::CSpotLight\fP"
.br
.ti -1c
.RI "struct \fBxpe::ecs::CGeometry\fP"
.br
.ti -1c
.RI "struct \fBxpe::ecs::CGeometryInfo\fP"
.br
.ti -1c
.RI "struct \fBxpe::ecs::CSkeleton\fP"
.br
.ti -1c
.RI "struct \fBxpe::ecs::CSkeletonInfo\fP"
.br
.ti -1c
.RI "struct \fBxpe::ecs::CAnimation\fP"
.br
.ti -1c
.RI "struct \fBxpe::ecs::CAudio\fP"
.br
.ti -1c
.RI "struct \fBxpe::ecs::CStreamAudio\fP"
.br
.ti -1c
.RI "struct \fBxpe::ecs::CVoice\fP"
.br
.ti -1c
.RI "struct \fBxpe::ecs::CPhysicsActor\fP"
.br
.ti -1c
.RI "struct \fBxpe::ecs::CLabel\fP"
.br
.ti -1c
.RI "struct \fBxpe::ecs::CContainer\fP"
.br
.ti -1c
.RI "struct \fBxpe::ecs::CButton\fP"
.br
.ti -1c
.RI "struct \fBxpe::ecs::CField\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBxpe\fP"
.br
.ti -1c
.RI "namespace \fBxpe::physics\fP"
.br
.ti -1c
.RI "namespace \fBxpe::ecs\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
