.TH "engine/src/rendering/core/core.hpp" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
engine/src/rendering/core/core.hpp
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBxpe::render::sResource\fP"
.br
.ti -1c
.RI "struct \fBxpe::render::sBuffer\fP"
.br
.ti -1c
.RI "struct \fBxpe::render::sBlob\fP"
.br
.ti -1c
.RI "struct \fBxpe::render::sViewport\fP"
.br
.ti -1c
.RI "struct \fBxpe::render::sVertexFormat\fP"
.br
.ti -1c
.RI "struct \fBxpe::render::sVertexFormat::sAttribute\fP"
.br
.ti -1c
.RI "struct \fBxpe::render::sAttributes\fP"
.br
.ti -1c
.RI "struct \fBxpe::render::sVertex\fP"
.br
.ti -1c
.RI "struct \fBxpe::render::sStencilTest\fP"
.br
.ti -1c
.RI "struct \fBxpe::render::sDepthStencilMode\fP"
.br
.ti -1c
.RI "struct \fBxpe::render::sBlendTarget\fP"
.br
.ti -1c
.RI "struct \fBxpe::render::sBlendMode\fP"
.br
.ti -1c
.RI "struct \fBxpe::render::sRasterizer\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBxpe\fP"
.br
.ti -1c
.RI "namespace \fBxpe::render\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum class \fBxpe::render::ePrimitiveTopology\fP { \fBxpe::render::TRIANGLE_LIST\fP, \fBxpe::render::TRIANGLE_STRIP\fP, \fBxpe::render::POINT_LIST\fP, \fBxpe::render::LINE_LIST\fP, \fBxpe::render::LINE_STRIP\fP, \fBxpe::render::DEFAULT\fP = TRIANGLE_LIST }"
.br
.ti -1c
.RI "enum class \fBxpe::render::eDepthWriteMask\fP { \fBxpe::render::ZERO\fP = 0, \fBxpe::render::ALL\fP = 1 }"
.br
.ti -1c
.RI "enum class \fBxpe::render::eDepthStencilFunc\fP { \fBxpe::render::NEVER\fP = 1, \fBxpe::render::LESS\fP = 2, \fBxpe::render::EQUAL\fP = 3, \fBxpe::render::LESS_EQUAL\fP = 4, \fBxpe::render::GREATER\fP = 5, \fBxpe::render::NOT_EQUAL\fP = 6, \fBxpe::render::GREATER_EQUAL\fP = 7, \fBxpe::render::ALWAYS\fP = 8 }"
.br
.ti -1c
.RI "enum class \fBxpe::render::eDepthStencilOp\fP { \fBxpe::render::KEEP\fP = 1, \fBxpe::render::ZERO\fP = 2, \fBxpe::render::REPLACE\fP = 3, \fBxpe::render::INCR_SAT\fP = 4, \fBxpe::render::DECR_SAT\fP = 5, \fBxpe::render::INVERT\fP = 6, \fBxpe::render::INCR\fP = 7, \fBxpe::render::DECR\fP = 8 }"
.br
.ti -1c
.RI "enum class \fBxpe::render::eBlend\fP { \fBxpe::render::ZERO\fP = 1, \fBxpe::render::ONE\fP = 2, \fBxpe::render::SRC_COLOR\fP = 3, \fBxpe::render::INV_SRC_COLOR\fP = 4, \fBxpe::render::SRC_ALPHA\fP = 5, \fBxpe::render::INV_SRC_ALPHA\fP = 6, \fBxpe::render::DEST_ALPHA\fP = 7, \fBxpe::render::INV_DEST_ALPHA\fP = 8, \fBxpe::render::DEST_COLOR\fP = 9, \fBxpe::render::INV_DEST_COLOR\fP = 10, \fBxpe::render::SRC_ALPHA_SAT\fP = 11, \fBxpe::render::BLEND_FACTOR\fP = 14, \fBxpe::render::INV_BLEND_FACTOR\fP = 15, \fBxpe::render::SRC1_COLOR\fP = 16, \fBxpe::render::INV_SRC1_COLOR\fP = 17, \fBxpe::render::SRC1_ALPHA\fP = 18, \fBxpe::render::INV_SRC1_ALPHA\fP = 19 }"
.br
.ti -1c
.RI "enum class \fBxpe::render::eBlendOp\fP { \fBxpe::render::ADD\fP = 1, \fBxpe::render::SUBTRACT\fP = 2, \fBxpe::render::REV_SUBTRACT\fP = 3, \fBxpe::render::MIN\fP = 4, \fBxpe::render::MAX\fP = 5 }"
.br
.ti -1c
.RI "enum \fBxpe::render::eColorWriteEnableMask\fP : u8 { \fBxpe::render::RED\fP = 1, \fBxpe::render::GREEN\fP = 2, \fBxpe::render::BLUE\fP = 4, \fBxpe::render::ALPHA\fP = 8, \fBxpe::render::ALL\fP = (((RED | GREEN) | BLUE) | ALPHA) }"
.br
.ti -1c
.RI "enum class \fBxpe::render::eFillMode\fP { \fBxpe::render::WIREFRAME\fP, \fBxpe::render::SOLID\fP, \fBxpe::render::DEFAULT\fP = SOLID }"
.br
.ti -1c
.RI "enum class \fBxpe::render::eCullMode\fP { \fBxpe::render::NONE\fP, \fBxpe::render::FRONT\fP, \fBxpe::render::BACK\fP, \fBxpe::render::DEFAULT\fP = NONE }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBxpe::render::JSON\fP (\fBsVertex\fP, Position, UV, Normal, Tangent, BoneIDs, BoneWeights) \fBstruct\fP \fBENGINE_API\fP \fBsInputLayout\fP \fBfinal\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
