.TH "engine/src/rendering/core/debugger.cpp" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
engine/src/rendering/core/debugger.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <rendering/core/debugger\&.hpp>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBxpe\fP"
.br
.ti -1c
.RI "namespace \fBxpe::render\fP"
.br
.ti -1c
.RI "namespace \fBxpe::render::context\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBDebuggerCallback\fP \fBxpe::render::context::Callback\fP = \fBnullptr\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBxpe::render::context::EnableInfoLog\fP = \fBfalse\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBxpe::render::context::EnableWarnLog\fP = \fBfalse\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBxpe::render::context::EnableErrorLog\fP = \fBtrue\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
