.TH "engine/src/ecs/ecs.hpp" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
engine/src/ecs/ecs.hpp
.SH SYNOPSIS
.br
.PP
\fR#include <entt/entity/registry\&.hpp>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBxpe::ecs::cScene\fP"
.br
.ti -1c
.RI "class \fBxpe::ecs::cEntity\fP"
.br
.ti -1c
.RI "class \fBxpe::ecs::cSystem\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBphysx\fP"
.br
.ti -1c
.RI "namespace \fBxpe\fP"
.br
.ti -1c
.RI "namespace \fBxpe::ecs\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "\fBtypedef\fP entt::entity \fBxpe::ecs::EntityID\fP"
.br
.ti -1c
.RI "\fBtypedef\fP \fBusize\fP \fBxpe::ecs::ComponentID\fP"
.br
.ti -1c
.RI "\fBusing\fP \fBxpe::ecs::cRegistry\fP = entt::basic_registry<\fBEntityID\fP, \fBcMainAllocator\fP<\fBEntityID\fP>>"
.br
.ti -1c
.RI "template<\fBtypename\fP \fBT\fP > \fBusing\fP \fBxpe::ecs::cStorage\fP = entt::basic_storage<\fBT\fP, \fBEntityID\fP, \fBcMainAllocator\fP<\fBEntityID\fP>>"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBconstexpr\fP \fBEntityID\fP \fBxpe::ecs::EntityNull\fP = entt::null"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
