.TH "engine/src/core/events.hpp" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
engine/src/core/events.hpp
.SH SYNOPSIS
.br
.PP
\fR#include <core/event\&.hpp>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBxpe\fP"
.br
.ti -1c
.RI "namespace \fBxpe::core\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBxpe::core::event_begin\fP (\fBWindowClosed\fP) \fBevent_end\fP(\fBWindowClosed\fP) event_begin(\fBWindowMoved\fP"
.br
.ti -1c
.RI "\fBint\fP \fBint\fP \fBy\fP \fBxpe::core::event_end\fP (\fBWindowMoved\fP, \fBx\fP, \fBy\fP) \fBevent_begin\fP(WindowResized"
.br
.ti -1c
.RI "\fBint\fP \fBint\fP \fBy\fP \fBint\fP \fBint\fP \fBh\fP \fBxpe::core::event_end\fP (WindowResized, \fBw\fP, \fBh\fP) \fBevent_begin\fP(WindowFrameResized"
.br
.ti -1c
.RI "\fBint\fP \fBint\fP \fBy\fP \fBint\fP \fBint\fP \fBh\fP \fBint\fP \fBint\fP \fBh\fP \fBxpe::core::event_end\fP (WindowFrameResized, \fBw\fP, \fBh\fP) \fBenum\fP \fBeWindowFrameResizedPriority\fP"
.br
.ti -1c
.RI "\fBxpe::core::event_begin\fP (\fBWindowRatioChanged\fP, \fBfloat\fP \fBratio\fP) \fBevent_end\fP(\fBWindowRatioChanged\fP"
.br
.ti -1c
.RI "\fBratio\fP \fBxpe::core::event_begin\fP (\fBWindowFocused\fP) \fBevent_end\fP(\fBWindowFocused\fP) event_begin(\fBWindowFocusLost\fP) \fBevent_end\fP(\fBWindowFocusLost\fP) event_begin(KeyPressed"
.br
.ti -1c
.RI "\fBratio\fP \fBconst\fP \fBeKey\fP \fBkey\fP \fBxpe::core::event_end\fP (KeyPressed, \fBkey\fP) \fBevent_begin\fP(KeyReleased"
.br
.ti -1c
.RI "\fBratio\fP \fBconst\fP \fBeKey\fP \fBkey\fP \fBconst\fP \fBeKey\fP \fBkey\fP \fBxpe::core::event_end\fP (KeyReleased, \fBkey\fP) \fBevent_begin\fP(KeyHold"
.br
.ti -1c
.RI "\fBratio\fP \fBconst\fP \fBeKey\fP \fBkey\fP \fBconst\fP \fBeKey\fP \fBkey\fP \fBconst\fP \fBeKey\fP \fBkey\fP \fBxpe::core::event_end\fP (KeyHold, \fBkey\fP) \fBevent_begin\fP(MousePressed"
.br
.ti -1c
.RI "\fBratio\fP \fBconst\fP \fBeKey\fP \fBkey\fP \fBconst\fP \fBeKey\fP \fBkey\fP \fBconst\fP \fBeKey\fP \fBkey\fP \fBconst\fP \fBeMouse\fP \fBmouse\fP \fBxpe::core::event_end\fP (MousePressed, \fBmouse\fP) \fBevent_begin\fP(MouseReleased"
.br
.ti -1c
.RI "\fBratio\fP \fBconst\fP \fBeKey\fP \fBkey\fP \fBconst\fP \fBeKey\fP \fBkey\fP \fBconst\fP \fBeKey\fP \fBkey\fP \fBconst\fP \fBeMouse\fP \fBmouse\fP \fBconst\fP \fBeMouse\fP \fBmouse\fP \fBxpe::core::event_end\fP (MouseReleased, \fBmouse\fP) \fBevent_begin\fP(MouseHold"
.br
.ti -1c
.RI "\fBratio\fP \fBconst\fP \fBeKey\fP \fBkey\fP \fBconst\fP \fBeKey\fP \fBkey\fP \fBconst\fP \fBeKey\fP \fBkey\fP \fBconst\fP \fBeMouse\fP \fBmouse\fP \fBconst\fP \fBeMouse\fP \fBmouse\fP \fBconst\fP \fBeMouse\fP \fBmouse\fP \fBxpe::core::event_end\fP (MouseHold, \fBmouse\fP) \fBevent_begin\fP(CursorMoved"
.br
.ti -1c
.RI "\fBratio\fP \fBconst\fP \fBeKey\fP \fBkey\fP \fBconst\fP \fBeKey\fP \fBkey\fP \fBconst\fP \fBeKey\fP \fBkey\fP \fBconst\fP \fBeMouse\fP \fBmouse\fP \fBconst\fP \fBeMouse\fP \fBmouse\fP \fBconst\fP \fBeMouse\fP \fBmouse\fP \fBconst\fP \fBdouble\fP \fBconst\fP \fBdouble\fP \fBy\fP \fBxpe::core::event_end\fP (CursorMoved, \fBx\fP, \fBy\fP) \fBevent_begin\fP(\fBCursorEntered\fP) event_end(\fBCursorEntered\fP) \fBevent_begin\fP(\fBCursorLeft\fP) event_end(\fBCursorLeft\fP) \fBevent_begin\fP(ScrollChanged"
.br
.ti -1c
.RI "\fBratio\fP \fBconst\fP \fBeKey\fP \fBkey\fP \fBconst\fP \fBeKey\fP \fBkey\fP \fBconst\fP \fBeKey\fP \fBkey\fP \fBconst\fP \fBeMouse\fP \fBmouse\fP \fBconst\fP \fBeMouse\fP \fBmouse\fP \fBconst\fP \fBeMouse\fP \fBmouse\fP \fBconst\fP \fBdouble\fP \fBconst\fP \fBdouble\fP \fBy\fP \fBconst\fP \fBdouble\fP \fBconst\fP \fBdouble\fP \fBy\fP \fBxpe::core::event_end\fP (ScrollChanged, \fBx\fP, \fBy\fP) \fBevent_begin\fP(\fBCharTyped\fP"
.br
.ti -1c
.RI "\fBratio\fP \fBconst\fP \fBeKey\fP \fBkey\fP \fBconst\fP \fBeKey\fP \fBkey\fP \fBconst\fP \fBeKey\fP \fBkey\fP \fBconst\fP \fBeMouse\fP \fBmouse\fP \fBconst\fP \fBeMouse\fP \fBmouse\fP \fBconst\fP \fBeMouse\fP \fBmouse\fP \fBconst\fP \fBdouble\fP \fBconst\fP \fBdouble\fP \fBy\fP \fBconst\fP \fBdouble\fP \fBconst\fP \fBdouble\fP \fBy\fP \fBconst\fP \fBu32\fP \fBcharUnicode\fP \fBxpe::core::event_end\fP (\fBCharTyped\fP, \fBcharUnicode\fP) \fBevent_begin\fP(\fBCharModsTyped\fP"
.br
.ti -1c
.RI "\fBratio\fP \fBconst\fP \fBeKey\fP \fBkey\fP \fBconst\fP \fBeKey\fP \fBkey\fP \fBconst\fP \fBeKey\fP \fBkey\fP \fBconst\fP \fBeMouse\fP \fBmouse\fP \fBconst\fP \fBeMouse\fP \fBmouse\fP \fBconst\fP \fBeMouse\fP \fBmouse\fP \fBconst\fP \fBdouble\fP \fBconst\fP \fBdouble\fP \fBy\fP \fBconst\fP \fBdouble\fP \fBconst\fP \fBdouble\fP \fBy\fP \fBconst\fP \fBu32\fP \fBcharUnicode\fP \fBconst\fP \fBu32\fP \fBconst\fP \fBint\fP \fBmods\fP \fBxpe::core::event_end\fP (\fBCharModsTyped\fP, \fBcharUnicode\fP, \fBmods\fP) \fBevent_begin\fP(\fBFileAdded\fP"
.br
.ti -1c
.RI "\fBratio\fP \fBconst\fP \fBeKey\fP \fBkey\fP \fBconst\fP \fBeKey\fP \fBkey\fP \fBconst\fP \fBeKey\fP \fBkey\fP \fBconst\fP \fBeMouse\fP \fBmouse\fP \fBconst\fP \fBeMouse\fP \fBmouse\fP \fBconst\fP \fBeMouse\fP \fBmouse\fP \fBconst\fP \fBdouble\fP \fBconst\fP \fBdouble\fP \fBy\fP \fBconst\fP \fBdouble\fP \fBconst\fP \fBdouble\fP \fBy\fP \fBconst\fP \fBu32\fP \fBcharUnicode\fP \fBconst\fP \fBu32\fP \fBconst\fP \fBint\fP \fBmods\fP \fBconst\fP \fBstring\fP \fBconst\fP \fBstring\fP &\fBfilepath\fP \fBxpe::core::event_end\fP (\fBFileAdded\fP, \fBwatchpath\fP, \fBfilepath\fP) \fBevent_begin\fP(\fBFileDeleted\fP"
.br
.ti -1c
.RI "\fBratio\fP \fBconst\fP \fBeKey\fP \fBkey\fP \fBconst\fP \fBeKey\fP \fBkey\fP \fBconst\fP \fBeKey\fP \fBkey\fP \fBconst\fP \fBeMouse\fP \fBmouse\fP \fBconst\fP \fBeMouse\fP \fBmouse\fP \fBconst\fP \fBeMouse\fP \fBmouse\fP \fBconst\fP \fBdouble\fP \fBconst\fP \fBdouble\fP \fBy\fP \fBconst\fP \fBdouble\fP \fBconst\fP \fBdouble\fP \fBy\fP \fBconst\fP \fBu32\fP \fBcharUnicode\fP \fBconst\fP \fBu32\fP \fBconst\fP \fBint\fP \fBmods\fP \fBconst\fP \fBstring\fP \fBconst\fP \fBstring\fP &\fBfilepath\fP \fBconst\fP \fBstring\fP \fBconst\fP \fBstring\fP &\fBfilepath\fP \fBxpe::core::event_end\fP (\fBFileDeleted\fP, \fBwatchpath\fP, \fBfilepath\fP) \fBevent_begin\fP(\fBFileModified\fP"
.br
.ti -1c
.RI "\fBratio\fP \fBconst\fP \fBeKey\fP \fBkey\fP \fBconst\fP \fBeKey\fP \fBkey\fP \fBconst\fP \fBeKey\fP \fBkey\fP \fBconst\fP \fBeMouse\fP \fBmouse\fP \fBconst\fP \fBeMouse\fP \fBmouse\fP \fBconst\fP \fBeMouse\fP \fBmouse\fP \fBconst\fP \fBdouble\fP \fBconst\fP \fBdouble\fP \fBy\fP \fBconst\fP \fBdouble\fP \fBconst\fP \fBdouble\fP \fBy\fP \fBconst\fP \fBu32\fP \fBcharUnicode\fP \fBconst\fP \fBu32\fP \fBconst\fP \fBint\fP \fBmods\fP \fBconst\fP \fBstring\fP \fBconst\fP \fBstring\fP &\fBfilepath\fP \fBconst\fP \fBstring\fP \fBconst\fP \fBstring\fP &\fBfilepath\fP \fBconst\fP \fBstring\fP \fBconst\fP \fBstring\fP &\fBfilepath\fP \fBxpe::core::event_end\fP (\fBFileModified\fP, \fBwatchpath\fP, \fBfilepath\fP) \fBevent_begin\fP(\fBFileNewName\fP"
.br
.ti -1c
.RI "\fBratio\fP \fBconst\fP \fBeKey\fP \fBkey\fP \fBconst\fP \fBeKey\fP \fBkey\fP \fBconst\fP \fBeKey\fP \fBkey\fP \fBconst\fP \fBeMouse\fP \fBmouse\fP \fBconst\fP \fBeMouse\fP \fBmouse\fP \fBconst\fP \fBeMouse\fP \fBmouse\fP \fBconst\fP \fBdouble\fP \fBconst\fP \fBdouble\fP \fBy\fP \fBconst\fP \fBdouble\fP \fBconst\fP \fBdouble\fP \fBy\fP \fBconst\fP \fBu32\fP \fBcharUnicode\fP \fBconst\fP \fBu32\fP \fBconst\fP \fBint\fP \fBmods\fP \fBconst\fP \fBstring\fP \fBconst\fP \fBstring\fP &\fBfilepath\fP \fBconst\fP \fBstring\fP \fBconst\fP \fBstring\fP &\fBfilepath\fP \fBconst\fP \fBstring\fP \fBconst\fP \fBstring\fP &\fBfilepath\fP \fBconst\fP \fBstring\fP \fBconst\fP \fBstring\fP &\fBfilepath\fP \fBxpe::core::event_end\fP (\fBFileNewName\fP, \fBwatchpath\fP, \fBfilepath\fP) \fBevent_begin\fP(\fBFileOldName\fP"
.br
.ti -1c
.RI "\fBratio\fP \fBconst\fP \fBeKey\fP \fBkey\fP \fBconst\fP \fBeKey\fP \fBkey\fP \fBconst\fP \fBeKey\fP \fBkey\fP \fBconst\fP \fBeMouse\fP \fBmouse\fP \fBconst\fP \fBeMouse\fP \fBmouse\fP \fBconst\fP \fBeMouse\fP \fBmouse\fP \fBconst\fP \fBdouble\fP \fBconst\fP \fBdouble\fP \fBy\fP \fBconst\fP \fBdouble\fP \fBconst\fP \fBdouble\fP \fBy\fP \fBconst\fP \fBu32\fP \fBcharUnicode\fP \fBconst\fP \fBu32\fP \fBconst\fP \fBint\fP \fBmods\fP \fBconst\fP \fBstring\fP \fBconst\fP \fBstring\fP &\fBfilepath\fP \fBconst\fP \fBstring\fP \fBconst\fP \fBstring\fP &\fBfilepath\fP \fBconst\fP \fBstring\fP \fBconst\fP \fBstring\fP &\fBfilepath\fP \fBconst\fP \fBstring\fP \fBconst\fP \fBstring\fP &\fBfilepath\fP \fBconst\fP \fBstring\fP \fBconst\fP \fBstring\fP &\fBfilepath\fP \fBxpe::core::event_end\fP (\fBFileOldName\fP, \fBwatchpath\fP, \fBfilepath\fP) \fBevent_begin\fP(\fBSampleCountChanged\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBint\fP \fBxpe::core::x\fP"
.br
.ti -1c
.RI "\fBint\fP \fBint\fP \fBy\fP \fBint\fP \fBxpe::core::w\fP"
.br
.ti -1c
.RI "\fBratio\fP \fBconst\fP \fBeKey\fP \fBkey\fP \fBconst\fP \fBeKey\fP \fBkey\fP \fBconst\fP \fBeKey\fP \fBkey\fP \fBconst\fP \fBeMouse\fP \fBmouse\fP \fBconst\fP \fBeMouse\fP \fBmouse\fP \fBconst\fP \fBeMouse\fP \fBmouse\fP \fBconst\fP \fBdouble\fP \fBconst\fP \fBdouble\fP \fBy\fP \fBconst\fP \fBdouble\fP \fBconst\fP \fBdouble\fP \fBy\fP \fBconst\fP \fBu32\fP charUnicode \fBconst\fP \fBu32\fP \fBxpe::core::charUnicode\fP"
.br
.ti -1c
.RI "\fBratio\fP \fBconst\fP \fBeKey\fP \fBkey\fP \fBconst\fP \fBeKey\fP \fBkey\fP \fBconst\fP \fBeKey\fP \fBkey\fP \fBconst\fP \fBeMouse\fP \fBmouse\fP \fBconst\fP \fBeMouse\fP \fBmouse\fP \fBconst\fP \fBeMouse\fP \fBmouse\fP \fBconst\fP \fBdouble\fP \fBconst\fP \fBdouble\fP \fBy\fP \fBconst\fP \fBdouble\fP \fBconst\fP \fBdouble\fP \fBy\fP \fBconst\fP \fBu32\fP \fBcharUnicode\fP \fBconst\fP \fBu32\fP \fBconst\fP \fBint\fP \fBmods\fP \fBconst\fP \fBstring\fP & \fBxpe::core::watchpath\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
