.TH "engine/src/rendering/font/font.hpp" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
engine/src/rendering/font/font.hpp
.SH SYNOPSIS
.br
.PP
\fR#include <rendering/core/texture\&.hpp>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBxpe::render::sFont\fP"
.br
.ti -1c
.RI "struct \fBxpe::render::sFont::sGlyph\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBxpe\fP"
.br
.ti -1c
.RI "namespace \fBxpe::render\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBxpe::render::JSON\fP (\fBsFont::sGlyph\fP, Char, Width, Height, \fBLeft\fP, Top, AdvanceX, AdvanceY, AtlasXOffset, AtlasYOffset) JSON(\fBsFont\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBxpe::render::GlyphCount\fP"
.br
.ti -1c
.RI "\fBxpe::render::GlyphSize\fP"
.br
.ti -1c
.RI "\fBxpe::render::NewLineOffset\fP"
.br
.ti -1c
.RI "\fBxpe::render::WhitespaceOffset\fP"
.br
.ti -1c
.RI "\fBxpe::render::MaxGlyphHeight\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
