.TH "engine/src/rendering/geometry/geometries.hpp" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
engine/src/rendering/geometry/geometries.hpp
.SH SYNOPSIS
.br
.PP
\fR#include <rendering/geometry/geometry\&.hpp>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBxpe::render::sTriangle\fP"
.br
.ti -1c
.RI "struct \fBxpe::render::sLine\fP"
.br
.ti -1c
.RI "struct \fBxpe::render::sQuad\fP"
.br
.ti -1c
.RI "struct \fBxpe::render::sCube\fP"
.br
.ti -1c
.RI "struct \fBxpe::render::sPlane\fP"
.br
.ti -1c
.RI "struct \fBxpe::render::sSphere\fP"
.br
.ti -1c
.RI "struct \fBxpe::render::sModel\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBxpe\fP"
.br
.ti -1c
.RI "namespace \fBxpe::render\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBxpe::render::JSON_ENUM\fP (\fBePrimitiveTopology\fP, { { \fBePrimitiveTopology::DEFAULT\fP, 'DEFAULT' }, { \fBePrimitiveTopology::TRIANGLE_LIST\fP, 'TRIANGLE_LIST' }, { \fBePrimitiveTopology::TRIANGLE_STRIP\fP, 'TRIANGLE_STRIP' }, { \fBePrimitiveTopology::POINT_LIST\fP, 'POINT_LIST' }, { \fBePrimitiveTopology::LINE_LIST\fP, 'LINE_LIST' }, { \fBePrimitiveTopology::LINE_STRIP\fP, 'LINE_STRIP' }, }) \fBJSON\fP(\fBsGeometry\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBxpe::render::PrimitiveTopology\fP"
.br
.ti -1c
.RI "\fBxpe::render::Vertices\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
