.TH "glm" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
glm
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBto_json\fP (\fBjson\fP &j, const glm::mat2 &m)"
.br
.ti -1c
.RI "void \fBfrom_json\fP (const \fBjson\fP &j, glm::mat2 &m)"
.br
.ti -1c
.RI "void \fBto_json\fP (\fBjson\fP &j, const glm::mat3 &m)"
.br
.ti -1c
.RI "void \fBfrom_json\fP (const \fBjson\fP &j, glm::mat3 &m)"
.br
.ti -1c
.RI "void \fBto_json\fP (\fBjson\fP &j, const glm::mat4 &m)"
.br
.ti -1c
.RI "void \fBfrom_json\fP (const \fBjson\fP &j, glm::mat4 &m)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void glm::from_json (const \fBjson\fP & j, glm::mat2 & m)"

.SS "void glm::from_json (const \fBjson\fP & j, glm::mat3 & m)"

.SS "void glm::from_json (const \fBjson\fP & j, glm::mat4 & m)"

.SS "void glm::to_json (\fBjson\fP & j, const glm::mat2 & m)"

.SS "void glm::to_json (\fBjson\fP & j, const glm::mat3 & m)"

.SS "void glm::to_json (\fBjson\fP & j, const glm::mat4 & m)"

.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
