.TH "engine/src/res/json.cpp" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
engine/src/res/json.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <res/json\&.hpp>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBxpe\fP"
.br
.ti -1c
.RI "namespace \fBxpe::res\fP"
.br
.ti -1c
.RI "namespace \fBglm\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBbool\fP \fBxpe::res::ReadJsonFile\fP (\fBconst\fP \fBchar\fP *\fBfilepath\fP, \fBcJson\fP &\fBobject\fP)"
.br
.ti -1c
.RI "\fBbool\fP \fBxpe::res::WriteJsonFile\fP (\fBconst\fP \fBchar\fP *\fBfilepath\fP, \fBcJson\fP &\fBobject\fP)"
.br
.ti -1c
.RI "void \fBglm::to_json\fP (\fBjson\fP &j, const glm::mat2 &m)"
.br
.ti -1c
.RI "void \fBglm::from_json\fP (const \fBjson\fP &j, glm::mat2 &m)"
.br
.ti -1c
.RI "void \fBglm::to_json\fP (\fBjson\fP &j, const glm::mat3 &m)"
.br
.ti -1c
.RI "void \fBglm::from_json\fP (const \fBjson\fP &j, glm::mat3 &m)"
.br
.ti -1c
.RI "void \fBglm::to_json\fP (\fBjson\fP &j, const glm::mat4 &m)"
.br
.ti -1c
.RI "void \fBglm::from_json\fP (const \fBjson\fP &j, glm::mat4 &m)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
