.TH "engine/src/launcher.hpp" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
engine/src/launcher.hpp
.SH SYNOPSIS
.br
.PP
\fR#include <core/app\&.hpp>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBint\fP \fBmain\fP (\fBint\fP \fBargc\fP, \fBchar\fP **\fBargv\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBint\fP main (\fBint\fP argc, \fBchar\fP ** argv)"

.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
