.TH "engine/src/core/log_manager.hpp" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
engine/src/core/log_manager.hpp
.SH SYNOPSIS
.br
.PP
\fR#include <spdlog/spdlog\&.h>\fP
.br
\fR#include <spdlog/sinks/basic_file_sink\&.h>\fP
.br
\fR#include <spdlog/sinks/stdout_color_sinks\&.h>\fP
.br
\fR#include <spdlog/async\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBxpe::core::sLoggerDescriptor\fP"
.br
.ti -1c
.RI "class \fBxpe::core::cLogManager\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBxpe\fP"
.br
.ti -1c
.RI "namespace \fBxpe::core\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBInitLogger\fP(desc)"
.br
.ti -1c
.RI "#define \fBFreeLogger\fP()"
.br
.ti -1c
.RI "#define \fBLogTrace\fP(\&.\&.\&.)"
.br
.ti -1c
.RI "#define \fBLogVerbose\fP(\&.\&.\&.)"
.br
.ti -1c
.RI "#define \fBLogInfo\fP(\&.\&.\&.)"
.br
.ti -1c
.RI "#define \fBLogWarning\fP(\&.\&.\&.)"
.br
.ti -1c
.RI "#define \fBLogError\fP(\&.\&.\&.)"
.br
.ti -1c
.RI "#define \fBLogMemory\fP(\&.\&.\&.)"
.br
.ti -1c
.RI "#define \fBDumpTraceError\fP(\&.\&.\&.)"
.br
.ti -1c
.RI "#define \fBLogTime\fP(time)"
.br
.ti -1c
.RI "#define \fBLogGLM\fP(name,  v)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define DumpTraceError( \&.\&.\&.)"

.SS "#define FreeLogger()"

.SS "#define InitLogger(desc)"

.SS "#define LogError( \&.\&.\&.)"

.SS "#define LogGLM(name, v)"

.SS "#define LogInfo( \&.\&.\&.)"

.SS "#define LogMemory( \&.\&.\&.)"

.SS "#define LogTime(time)"

.SS "#define LogTrace( \&.\&.\&.)"

.SS "#define LogVerbose( \&.\&.\&.)"

.SS "#define LogWarning( \&.\&.\&.)"

.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
