.TH "engine/src/core/macro_constants.hpp" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
engine/src/core/macro_constants.hpp
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBK_DEPTH_INVALID\fP   \-1\&.0f"
.br
.ti -1c
.RI "#define \fBK_PI\fP   3\&.14159265359f"
.br
.ti -1c
.RI "#define \fBK_MEMORY_KB\fP   1024"
.br
.ti -1c
.RI "#define \fBK_MEMORY_MB\fP   (1024 * \fBK_MEMORY_KB\fP)"
.br
.ti -1c
.RI "#define \fBK_MEMORY_GB\fP   (1024 * \fBK_MEMORY_MB\fP)"
.br
.ti -1c
.RI "#define \fBK_PROFILE_VERTEX\fP   'vs_5_0'"
.br
.ti -1c
.RI "#define \fBK_PROFILE_PIXEL\fP   'ps_5_0'"
.br
.ti -1c
.RI "#define \fBK_PROFILE_GEOMETRY\fP   'gs_5_0'"
.br
.ti -1c
.RI "#define \fBK_PROFILE_COMPUTE\fP   'cs_5_0'"
.br
.ti -1c
.RI "#define \fBK_ENTRY_POINT_VERTEX\fP   'vs_main'"
.br
.ti -1c
.RI "#define \fBK_ENTRY_POINT_PIXEL\fP   'ps_main'"
.br
.ti -1c
.RI "#define \fBK_ENTRY_POINT_GEOMETRY\fP   'gs_main'"
.br
.ti -1c
.RI "#define \fBK_ENTRY_POINT_COMPUTE\fP   'cs_main'"
.br
.ti -1c
.RI "#define \fBK_SLOT_DEFAULT\fP   UINT32_MAX"
.br
.ti -1c
.RI "#define \fBK_SLOT_WIDGETS\fP   0"
.br
.ti -1c
.RI "#define \fBK_SLOT_CHARS\fP   0"
.br
.ti -1c
.RI "#define \fBK_SLOT_TEXTS\fP   1"
.br
.ti -1c
.RI "#define \fBK_SLOT_WIDGET_SAMPLER\fP   0"
.br
.ti -1c
.RI "#define \fBK_SLOT_WIDGET_ATLAS\fP   0"
.br
.ti -1c
.RI "#define \fBK_SLOT_FONT_SAMPLER\fP   0"
.br
.ti -1c
.RI "#define \fBK_SLOT_FONT_ATLAS\fP   0"
.br
.ti -1c
.RI "#define \fBK_SLOT_INSTANCES\fP   0"
.br
.ti -1c
.RI "#define \fBK_SLOT_SKELETONS\fP   1"
.br
.ti -1c
.RI "#define \fBK_SLOT_MATERIAL_SAMPLER\fP   0"
.br
.ti -1c
.RI "#define \fBK_SLOT_MATERIALS\fP   0"
.br
.ti -1c
.RI "#define \fBK_SLOT_ALBEDO\fP   1"
.br
.ti -1c
.RI "#define \fBK_SLOT_BUMPING\fP   2"
.br
.ti -1c
.RI "#define \fBK_SLOT_PARALLAX\fP   3"
.br
.ti -1c
.RI "#define \fBK_SLOT_METALLIC\fP   4"
.br
.ti -1c
.RI "#define \fBK_SLOT_ROUGHNESS\fP   5"
.br
.ti -1c
.RI "#define \fBK_SLOT_AO\fP   6"
.br
.ti -1c
.RI "#define \fBK_SLOT_EMISSION\fP   7"
.br
.ti -1c
.RI "#define \fBK_SLOT_DIRECT_LIGHTS\fP   8"
.br
.ti -1c
.RI "#define \fBK_SLOT_POINT_LIGHTS\fP   9"
.br
.ti -1c
.RI "#define \fBK_SLOT_SPOT_LIGHTS\fP   10"
.br
.ti -1c
.RI "#define \fBK_SLOT_SHADOW_ATLAS\fP   11"
.br
.ti -1c
.RI "#define \fBK_SLOT_SHADOW_SAMPLER\fP   1"
.br
.ti -1c
.RI "#define \fBK_SLOT_SHADOW_PCF\fP   0"
.br
.ti -1c
.RI "#define \fBK_SLOT_CAMERA\fP   0"
.br
.ti -1c
.RI "#define \fBK_SLOT_SSAO\fP   0"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define K_DEPTH_INVALID   \-1\&.0f"

.SS "#define K_ENTRY_POINT_COMPUTE   'cs_main'"

.SS "#define K_ENTRY_POINT_GEOMETRY   'gs_main'"

.SS "#define K_ENTRY_POINT_PIXEL   'ps_main'"

.SS "#define K_ENTRY_POINT_VERTEX   'vs_main'"

.SS "#define K_MEMORY_GB   (1024 * \fBK_MEMORY_MB\fP)"

.SS "#define K_MEMORY_KB   1024"

.SS "#define K_MEMORY_MB   (1024 * \fBK_MEMORY_KB\fP)"

.SS "#define K_PI   3\&.14159265359f"

.SS "#define K_PROFILE_COMPUTE   'cs_5_0'"

.SS "#define K_PROFILE_GEOMETRY   'gs_5_0'"

.SS "#define K_PROFILE_PIXEL   'ps_5_0'"

.SS "#define K_PROFILE_VERTEX   'vs_5_0'"

.SS "#define K_SLOT_ALBEDO   1"

.SS "#define K_SLOT_AO   6"

.SS "#define K_SLOT_BUMPING   2"

.SS "#define K_SLOT_CAMERA   0"

.SS "#define K_SLOT_CHARS   0"

.SS "#define K_SLOT_DEFAULT   UINT32_MAX"

.SS "#define K_SLOT_DIRECT_LIGHTS   8"

.SS "#define K_SLOT_EMISSION   7"

.SS "#define K_SLOT_FONT_ATLAS   0"

.SS "#define K_SLOT_FONT_SAMPLER   0"

.SS "#define K_SLOT_INSTANCES   0"

.SS "#define K_SLOT_MATERIAL_SAMPLER   0"

.SS "#define K_SLOT_MATERIALS   0"

.SS "#define K_SLOT_METALLIC   4"

.SS "#define K_SLOT_PARALLAX   3"

.SS "#define K_SLOT_POINT_LIGHTS   9"

.SS "#define K_SLOT_ROUGHNESS   5"

.SS "#define K_SLOT_SHADOW_ATLAS   11"

.SS "#define K_SLOT_SHADOW_PCF   0"

.SS "#define K_SLOT_SHADOW_SAMPLER   1"

.SS "#define K_SLOT_SKELETONS   1"

.SS "#define K_SLOT_SPOT_LIGHTS   10"

.SS "#define K_SLOT_SSAO   0"

.SS "#define K_SLOT_TEXTS   1"

.SS "#define K_SLOT_WIDGET_ATLAS   0"

.SS "#define K_SLOT_WIDGET_SAMPLER   0"

.SS "#define K_SLOT_WIDGETS   0"

.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
