.TH "engine/src/core/macro_build.hpp" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
engine/src/core/macro_build.hpp
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBENGINE_API\fP"
.br
.ti -1c
.RI "#define \fBGAME_API\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define ENGINE_API"

.SS "#define GAME_API"

.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
