.TH "engine/src/math/math.hpp" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
engine/src/math/math.hpp
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBxpe\fP"
.br
.ti -1c
.RI "namespace \fBxpe::math\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<\fBtypename\fP \fBT\fP > \fBvoid\fP \fBxpe::math::clamp\fP (\fBT\fP &\fBvalue\fP, \fBconst\fP \fBT\fP \fBmin\fP, \fBconst\fP \fBT\fP \fBmax\fP)"
.br
.ti -1c
.RI "template<\fBtypename\fP \fBT\fP > \fBT\fP \fBxpe::math::min\fP (\fBconst\fP \fBT\fP &\fBright\fP, \fBconst\fP \fBT\fP &\fBleft\fP)"
.br
.ti -1c
.RI "template<\fBtypename\fP \fBT\fP > \fBT\fP \fBxpe::math::max\fP (\fBconst\fP \fBT\fP &\fBright\fP, \fBconst\fP \fBT\fP &\fBleft\fP)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
