.TH "engine/src/math/matrices.hpp" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
engine/src/math/matrices.hpp
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBxpe::math::sModelMatrix\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBxpe\fP"
.br
.ti -1c
.RI "namespace \fBxpe::math\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBxpe::math::JSON\fP (\fBsModelMatrix\fP, Position, Rotation, Scale) \fBstruct\fP \fBENGINE_API\fP \fBsViewMatrix\fP"
.br
.ti -1c
.RI "\fBxpe::math::JSON\fP (\fBsViewMatrix\fP, Position, Front, \fBUp\fP) \fBstruct\fP \fBENGINE_API\fP sOrthoMatrix"
.br
.ti -1c
.RI "\fBxpe::math::JSON\fP (sOrthoMatrix, \fBLeft\fP, \fBRight\fP, \fBBottom\fP, Top, Near, Far) \fBstruct\fP \fBENGINE_API\fP sPerspectiveMatrix"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
