.TH "engine/src/pch.hpp" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
engine/src/pch.hpp
.SH SYNOPSIS
.br
.PP
\fR#include <core/macro_platform\&.hpp>\fP
.br
\fR#include <core/macro_build\&.hpp>\fP
.br
\fR#include <core/macro_constants\&.hpp>\fP
.br
\fR#include <core/macro_debugbreak\&.hpp>\fP
.br
\fR#include <random>\fP
.br
\fR#include <string>\fP
.br
\fR#include <algorithm>\fP
.br
\fR#include <functional>\fP
.br
\fR#include <array>\fP
.br
\fR#include <vector>\fP
.br
\fR#include <thread>\fP
.br
\fR#include <future>\fP
.br
\fR#include <map>\fP
.br
\fR#include <unordered_map>\fP
.br
\fR#include <unordered_set>\fP
.br
\fR#include <set>\fP
.br
\fR#include <queue>\fP
.br
\fR#include <memory>\fP
.br
\fR#include <mutex>\fP
.br
\fR#include <filesystem>\fP
.br
\fR#include <fstream>\fP
.br
\fR#include <sstream>\fP
.br
\fR#include <cstdint>\fP
.br
\fR#include <cassert>\fP
.br
\fR#include <cstdarg>\fP
.br
\fR#include <ctime>\fP
.br
\fR#include <utility>\fP
.br
\fR#include <chrono>\fP
.br
\fR#include <iostream>\fP
.br
\fR#include <regex>\fP
.br
\fR#include <atomic>\fP
.br
\fR#include <condition_variable>\fP
.br
\fR#include <glm\&.hpp>\fP
.br
\fR#include <gtx/quaternion\&.hpp>\fP
.br
\fR#include <gtc/type_ptr\&.hpp>\fP
.br
\fR#include <gtc/matrix_transform\&.hpp>\fP
.br
\fR#include <gtx/matrix_transform_2d\&.hpp>\fP
.br
\fR#include <gtx/string_cast\&.hpp>\fP
.br
\fR#include <core/types\&.hpp>\fP
.br
\fR#include <core/memory_manager\&.hpp>\fP
.br
\fR#include <core/allocators\&.hpp>\fP
.br
\fR#include <core/smart_pointers\&.hpp>\fP
.br
\fR#include <core/codes_keyboard\&.hpp>\fP
.br
\fR#include <core/codes_mouse\&.hpp>\fP
.br
\fR#include <core/codes_gamepad\&.hpp>\fP
.br
\fR#include <res/json\&.hpp>\fP
.br
\fR#include <res/xml\&.hpp>\fP
.br
\fR#include <core/app_config\&.hpp>\fP
.br
\fR#include <core/hardware_manager\&.hpp>\fP
.br
\fR#include <stl/stl\&.hpp>\fP
.br
\fR#include <stl/ring_buffer\&.hpp>\fP
.br
\fR#include <core/time_manager\&.hpp>\fP
.br
\fR#include <core/log_manager\&.hpp>\fP
.br
\fR#include <core/thread\&.hpp>\fP
.br
\fR#include <core/task_manager\&.hpp>\fP
.br
\fR#include <core/event_manager\&.hpp>\fP
.br
\fR#include <core/observers\&.hpp>\fP
.br
\fR#include <core/file_manager\&.hpp>\fP
.br
\fR#include <core/window_manager\&.hpp>\fP
.br
\fR#include <core/input_manager\&.hpp>\fP
.br
\fR#include <physics/physics_manager\&.hpp>\fP
.br
\fR#include <math/math_manager\&.hpp>\fP
.br
\fR#include <ecs/ecs\&.hpp>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBK_SLOT_SSAO\fP   0"
.br
.ti -1c
.RI "#\fBdefine\fP \fB_ENFORCE_MATCHING_ALLOCATORS\fP   0"
.br
.ti -1c
.RI "#\fBdefine\fP \fBGLM_ENABLE_EXPERIMENTAL\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#\fBdefine\fP _ENFORCE_MATCHING_ALLOCATORS   0"

.SS "#\fBdefine\fP GLM_ENABLE_EXPERIMENTAL"

.SS "#define K_SLOT_SSAO   0"

.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
