.TH "engine/src/physics/physics_manager.hpp" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
engine/src/physics/physics_manager.hpp
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBxpe::physics::sSphereShapeDescriptor\fP"
.br
.ti -1c
.RI "struct \fBxpe::physics::sCapsuleShapeDescriptor\fP"
.br
.ti -1c
.RI "struct \fBxpe::physics::sBoxShapeDescriptor\fP"
.br
.ti -1c
.RI "struct \fBxpe::physics::sPlaneShapeDescriptor\fP"
.br
.ti -1c
.RI "struct \fBxpe::physics::sActor\fP"
.br
.ti -1c
.RI "struct \fBxpe::physics::sRagdoll\fP"
.br
.ti -1c
.RI "class \fBxpe::physics::cPhysicsManager\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBphysx\fP"
.br
.ti -1c
.RI "namespace \fBxpe\fP"
.br
.ti -1c
.RI "namespace \fBxpe::core\fP"
.br
.ti -1c
.RI "namespace \fBxpe::ecs\fP"
.br
.ti -1c
.RI "namespace \fBxpe::render\fP"
.br
.ti -1c
.RI "namespace \fBxpe::math\fP"
.br
.ti -1c
.RI "namespace \fBxpe::physics\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum class \fBxpe::physics::eShapeType\fP { \fBxpe::physics::NONE\fP = 0, \fBxpe::physics::SPHERE\fP = 1, \fBxpe::physics::CAPSULE\fP = 2, \fBxpe::physics::BOX\fP = 3, \fBxpe::physics::PLANE\fP = 4 }"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
