.TH "engine/src/physics/physics_manager.cpp" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
engine/src/physics/physics_manager.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <PxPhysics\&.h>\fP
.br
\fR#include <physics/physics_manager\&.hpp>\fP
.br
\fR#include <physics/allocators\&.hpp>\fP
.br
\fR#include <physics/callbacks\&.hpp>\fP
.br
\fR#include <ecs/components\&.hpp>\fP
.br
\fR#include <gtx/quaternion\&.hpp>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBxpe\fP"
.br
.ti -1c
.RI "namespace \fBxpe::physics\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBPxFilterFlags\fP \fBxpe::physics::FilterShader\fP (\fBPxFilterObjectAttributes\fP \fBattributes0\fP, \fBPxFilterData\fP \fBfilterData0\fP, \fBPxFilterObjectAttributes\fP \fBattributes1\fP, \fBPxFilterData\fP \fBfilterData1\fP, \fBPxPairFlags\fP &\fBpairFlags\fP, \fBconst\fP \fBvoid\fP *\fBconstantBlock\fP, \fBPxU32\fP \fBconstantBlockSize\fP)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
