.TH "engine/src/rendering/shaders.hpp" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
engine/src/rendering/shaders.hpp
.SH SYNOPSIS
.br
.PP
\fR#include <rendering/core/shader\&.hpp>\fP
.br
\fR#include <rendering/buffers\&.hpp>\fP
.br
\fR#include <rendering/geometry/geometry\&.hpp>\fP
.br
\fR#include <rendering/font/font\&.hpp>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBxpe::render::cInstancingShader\fP"
.br
.ti -1c
.RI "class \fBxpe::render::cOpaqueShader\fP"
.br
.ti -1c
.RI "class \fBxpe::render::cTransparentShader\fP"
.br
.ti -1c
.RI "class \fBxpe::render::cShadowShader\fP"
.br
.ti -1c
.RI "class \fBxpe::render::cDirectionalShadowShader\fP"
.br
.ti -1c
.RI "class \fBxpe::render::cPointShadowShader\fP"
.br
.ti -1c
.RI "class \fBxpe::render::cSpotShadowShader\fP"
.br
.ti -1c
.RI "class \fBxpe::render::cSkyboxShader\fP"
.br
.ti -1c
.RI "class \fBxpe::render::cCompositeTransparentShader\fP"
.br
.ti -1c
.RI "class \fBxpe::render::cSsaoShader\fP"
.br
.ti -1c
.RI "class \fBxpe::render::cFinalShader\fP"
.br
.ti -1c
.RI "class \fBxpe::render::cWidgetShader\fP"
.br
.ti -1c
.RI "class \fBxpe::render::cTextShader\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBxpe\fP"
.br
.ti -1c
.RI "namespace \fBxpe::render\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
