.TH "engine/src/rendering/core/shader.hpp" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
engine/src/rendering/core/shader.hpp
.SH SYNOPSIS
.br
.PP
\fR#include <rendering/core/render_target\&.hpp>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBxpe::render::sShaderStage\fP"
.br
.ti -1c
.RI "class \fBxpe::render::cShader\fP"
.br
.ti -1c
.RI "class \fBxpe::render::cDefaultShader\fP"
.br
.ti -1c
.RI "class \fBxpe::render::cComputeShader\fP"
.br
.ti -1c
.RI "class \fBxpe::render::cShaderManager\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBxpe\fP"
.br
.ti -1c
.RI "namespace \fBxpe::render\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
