.TH "engine/src/rendering/shadow_manager.cpp" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
engine/src/rendering/shadow_manager.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <rendering/shadow_manager\&.hpp>\fP
.br
\fR#include <rendering/bindings\&.hpp>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBxpe\fP"
.br
.ti -1c
.RI "namespace \fBxpe::render\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
