.TH "engine/src/anim/skeleton.hpp" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
engine/src/anim/skeleton.hpp
.SH SYNOPSIS
.br
.PP
\fR#include <anim/anim\&.hpp>\fP
.br
\fR#include <rendering/geometry/geometry\&.hpp>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBxpe::anim::sBone\fP"
.br
.ti -1c
.RI "struct \fBxpe::anim::sSkeleton\fP"
.br
.ti -1c
.RI "struct \fBxpe::anim::sSkeletonInfo\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBxpe\fP"
.br
.ti -1c
.RI "namespace \fBxpe::anim\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
