.TH "engine/src/audio/core/sndfile_context.cpp" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
engine/src/audio/core/sndfile_context.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <audio/core/sndfile_context\&.hpp>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBxpe\fP"
.br
.ti -1c
.RI "namespace \fBxpe::audio\fP"
.br
.ti -1c
.RI "namespace \fBxpe::audio::context\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBvoid\fP \fBxpe::audio::context::SetCurrentFrame\fP (\fBSNDFILE\fP *\fBfile\fP, \fBs64\fP \fBframe\fP)"
.br
.ti -1c
.RI "\fBs64\fP \fBxpe::audio::context::ReadChunk\fP (\fBSNDFILE\fP *\fBm_File\fP, \fBshort\fP *\fBdata\fP, \fBs64\fP \fBnum_frames\fP)"
.br
.ti -1c
.RI "\fBbool\fP \fBxpe::audio::context::isAmbisonic\fP (\fBconst\fP \fBsAudioFile\fP &\fBfile\fP)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
