.TH "engine/src/core/task_manager.hpp" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
engine/src/core/task_manager.hpp
.SH SYNOPSIS
.br
.PP
\fR#include <PxPhysicsAPI\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBxpe::core::sTask\fP"
.br
.ti -1c
.RI "struct \fBxpe::core::sTaskQueue\fP"
.br
.ti -1c
.RI "class \fBxpe::core::cTaskDispatcher\fP"
.br
.ti -1c
.RI "class \fBxpe::core::cSimulationDispatcher\fP"
.br
.ti -1c
.RI "class \fBxpe::core::cTaskManager\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBxpe\fP"
.br
.ti -1c
.RI "namespace \fBxpe::core\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
