.TH "engine/src/rendering/core/texture.hpp" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
engine/src/rendering/core/texture.hpp
.SH SYNOPSIS
.br
.PP
\fR#include <rendering/core/core\&.hpp>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBxpe::render::sMip\fP"
.br
.ti -1c
.RI "struct \fBxpe::render::sTextureLayer\fP"
.br
.ti -1c
.RI "struct \fBxpe::render::sTexture\fP"
.br
.ti -1c
.RI "struct \fBxpe::render::sAtlas\fP"
.br
.ti -1c
.RI "struct \fBxpe::render::sAtlas::sCell\fP"
.br
.ti -1c
.RI "struct \fBxpe::render::sAtlas::sLocation\fP"
.br
.ti -1c
.RI "struct \fBxpe::render::sSampler\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBxpe\fP"
.br
.ti -1c
.RI "namespace \fBxpe::render\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum class \fBxpe::render::eTextureFormat\fP { \fBxpe::render::R8\fP, \fBxpe::render::R16\fP, \fBxpe::render::R32\fP, \fBxpe::render::R32_TYPELESS\fP, \fBxpe::render::RG8\fP, \fBxpe::render::RG16\fP, \fBxpe::render::RG32\fP, \fBxpe::render::RGB8\fP, \fBxpe::render::RGB16\fP, \fBxpe::render::RGB32\fP, \fBxpe::render::RGBA8\fP, \fBxpe::render::RGBA16\fP, \fBxpe::render::RGBA32\fP, \fBxpe::render::SRGBA8\fP, \fBxpe::render::DEFAULT\fP = RGBA8, \fBxpe::render::HDR\fP = RGBA32 }"
.br
.ti -1c
.RI "enum class \fBxpe::render::eFileFormat\fP { \fBxpe::render::PNG\fP, \fBxpe::render::JPG\fP, \fBxpe::render::TGA\fP, \fBxpe::render::HDR\fP, \fBxpe::render::BMP\fP }"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
