.TH "engine/src/core/time_manager.hpp" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
engine/src/core/time_manager.hpp
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBxpe::core::cTime\fP"
.br
.ti -1c
.RI "class \fBxpe::core::cTimeManager\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBxpe\fP"
.br
.ti -1c
.RI "namespace \fBxpe::core\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBLogTime\fP(t)"
.br
.ti -1c
.RI "#define \fBLogCpuTime\fP(t)"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "\fBtypedef\fP \fBconst\fP std::chrono::duration< \fBdouble\fP, std::milli > \fBxpe::core::TimeMillis\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define LogCpuTime(t)"

.SS "#define LogTime(t)"

.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
