.TH "engine/src/core/window_manager.hpp" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
engine/src/core/window_manager.hpp
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBxpe::core::sWindowDescriptor\fP"
.br
.ti -1c
.RI "struct \fBxpe::core::sWindow\fP"
.br
.ti -1c
.RI "class \fBxpe::core::cWindowManager\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBxpe\fP"
.br
.ti -1c
.RI "namespace \fBxpe::core\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum class \fBxpe::core::eCursorMode\fP { \fBxpe::core::NORMAL\fP, \fBxpe::core::HIDE\fP, \fBxpe::core::DISABLE\fP, \fBxpe::core::CAPTURED\fP, \fBxpe::core::DEFAULT\fP = NORMAL }"
.br
.ti -1c
.RI "enum class \fBxpe::core::eWindowTheme\fP { \fBxpe::core::LIGHT\fP, \fBxpe::core::DARK\fP, \fBxpe::core::DEFAULT\fP = LIGHT }"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
