.TH "xpe" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xpe
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBanim\fP"
.br
.ti -1c
.RI "namespace \fBaudio\fP"
.br
.ti -1c
.RI "namespace \fBcore\fP"
.br
.ti -1c
.RI "namespace \fBecs\fP"
.br
.ti -1c
.RI "namespace \fBmath\fP"
.br
.ti -1c
.RI "namespace \fBphysics\fP"
.br
.ti -1c
.RI "namespace \fBrender\fP"
.br
.ti -1c
.RI "namespace \fBres\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
