.TH "xpe::anim::sKeyScale" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xpe::anim::sKeyScale
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <anim\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsKeyScale\fP ()=\fBdefault\fP"
.br
.ti -1c
.RI "\fBsKeyScale\fP (\fBfloat\fP \fBtimestamp\fP, \fBconst\fP glm::vec3 &\fBscale\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBfloat\fP \fBTimestamp\fP"
.br
.ti -1c
.RI "glm::vec3 \fBScale\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "xpe::anim::sKeyScale::sKeyScale ()\fR [default]\fP"

.SS "xpe::anim::sKeyScale::sKeyScale (\fBfloat\fP timestamp, \fBconst\fP glm::vec3 & scale)\fR [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "glm::vec3 xpe::anim::sKeyScale::Scale"

.SS "\fBfloat\fP xpe::anim::sKeyScale::Timestamp"


.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
