.TH "xpe::render::sVertexFormat::sAttribute" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xpe::render::sVertexFormat::sAttribute
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <core\&.hpp>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum class \fBeType\fP { \fBFLOAT\fP, \fBBOOL\fP, \fBINT\fP, \fBUINT\fP, \fBVEC2_FLOAT\fP, \fBVEC2_UINT\fP, \fBVEC2_INT\fP, \fBVEC2_TYPELESS\fP, \fBVEC3_FLOAT\fP, \fBVEC3_UINT\fP, \fBVEC3_INT\fP, \fBVEC3_TYPELESS\fP, \fBVEC4_FLOAT\fP, \fBVEC4_UINT\fP, \fBVEC4_INT\fP, \fBVEC4_TYPELESS\fP, \fBMAT2X2\fP, \fBMAT3X3\fP, \fBMAT4X4\fP }"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBu32\fP \fBLocation\fP = 0"
.br
.ti -1c
.RI "\fBconst\fP \fBchar\fP * \fBName\fP = \fBnullptr\fP"
.br
.ti -1c
.RI "\fBeType\fP \fBFormat\fP"
.br
.ti -1c
.RI "\fBu8\fP \fBByteSize\fP = 0"
.br
.in -1c
.SH "Member Enumeration Documentation"
.PP 
.SS "\fBenum\fP \fBclass\fP \fBxpe::render::sVertexFormat::sAttribute::eType\fP\fR [strong]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIFLOAT \fP\fP
.TP
\fB\fIBOOL \fP\fP
.TP
\fB\fIINT \fP\fP
.TP
\fB\fIUINT \fP\fP
.TP
\fB\fIVEC2_FLOAT \fP\fP
.TP
\fB\fIVEC2_UINT \fP\fP
.TP
\fB\fIVEC2_INT \fP\fP
.TP
\fB\fIVEC2_TYPELESS \fP\fP
.TP
\fB\fIVEC3_FLOAT \fP\fP
.TP
\fB\fIVEC3_UINT \fP\fP
.TP
\fB\fIVEC3_INT \fP\fP
.TP
\fB\fIVEC3_TYPELESS \fP\fP
.TP
\fB\fIVEC4_FLOAT \fP\fP
.TP
\fB\fIVEC4_UINT \fP\fP
.TP
\fB\fIVEC4_INT \fP\fP
.TP
\fB\fIVEC4_TYPELESS \fP\fP
.TP
\fB\fIMAT2X2 \fP\fP
.TP
\fB\fIMAT3X3 \fP\fP
.TP
\fB\fIMAT4X4 \fP\fP
.SH "Member Data Documentation"
.PP 
.SS "\fBu8\fP xpe::render::sVertexFormat::sAttribute::ByteSize = 0"

.SS "\fBeType\fP xpe::render::sVertexFormat::sAttribute::Format"

.SS "\fBu32\fP xpe::render::sVertexFormat::sAttribute::Location = 0"

.SS "\fBconst\fP \fBchar\fP* xpe::render::sVertexFormat::sAttribute::Name = \fBnullptr\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
