.TH "xpe::render::sText" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xpe::render::sText
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <buffers\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "glm::mat4 \fBModelMatrix\fP"
.br
.ti -1c
.RI "glm::mat4 \fBProjection\fP"
.br
.ti -1c
.RI "glm::vec4 \fBColor\fP = { 1, 1, 1, 1 }"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "glm::vec4 xpe::render::sText::Color = { 1, 1, 1, 1 }"

.SS "glm::mat4 xpe::render::sText::ModelMatrix"

.SS "glm::mat4 xpe::render::sText::Projection"


.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
