.TH "xpe::core::sWindow" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xpe::core::sWindow
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <window_manager\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBvoid\fP * \fBInstance\fP = \fBnullptr\fP"
.br
.ti -1c
.RI "\fBvoid\fP * \fBWin32Instance\fP = \fBnullptr\fP"
.br
.ti -1c
.RI "\fBsWindowDescriptor\fP \fBDescriptor\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBsWindowDescriptor\fP xpe::core::sWindow::Descriptor"

.SS "\fBvoid\fP* xpe::core::sWindow::Instance = \fBnullptr\fP"

.SS "\fBvoid\fP* xpe::core::sWindow::Win32Instance = \fBnullptr\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
