.TH "xpe::ecs::CPointLight" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xpe::ecs::CPointLight
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <components\&.hpp>\fP
.PP
Inherits \fBxpe::res::cJson\fP, and \fBxpe::render::sPointLightData\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCPointLight\fP (\fBconst\fP glm::vec3 &\fBposition\fP, \fBconst\fP glm::vec3 &\fBcolor\fP)"
.br
.in -1c

Public Member Functions inherited from \fBxpe::res::cJson\fP
.in +1c
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBToJson\fP (\fBjson\fP &\fBroot\fP)=0"
.br
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBFromJson\fP (\fBjson\fP &\fBroot\fP)=0"
.br
.in -1c
.SS "Additional Inherited Members"


Public Attributes inherited from \fBxpe::render::sPointLightData\fP
.in +1c
.ti -1c
.RI "glm::vec3 \fBPosition\fP = { 0, 0, 0 }"
.br
.ti -1c
.RI "glm::vec3 \fBColor\fP = { 1, 1, 1 }"
.br
.ti -1c
.RI "\fBfloat\fP \fBConstant\fP = 1\&.0f"
.br
.ti -1c
.RI "\fBfloat\fP \fBLinear\fP = 0\&.09\fBf\fP"
.br
.ti -1c
.RI "\fBfloat\fP \fBQuadratic\fP = 0\&.032\fBf\fP"
.br
.ti -1c
.RI "glm::mat4 \fBViewProjection\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "xpe::ecs::CPointLight::CPointLight (\fBconst\fP glm::vec3 & position, \fBconst\fP glm::vec3 & color)\fR [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
