.TH "xpe::anim::sAnimation" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xpe::anim::sAnimation
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <anim\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBbool\fP \fBPlay\fP"
.br
.ti -1c
.RI "\fBfloat\fP \fBDuration\fP"
.br
.ti -1c
.RI "\fBint\fP \fBTicksPerSecond\fP"
.br
.ti -1c
.RI "\fBsAnimationNode\fP \fBRoot\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBfloat\fP xpe::anim::sAnimation::Duration"

.SS "\fBbool\fP xpe::anim::sAnimation::Play"

.SS "\fBsAnimationNode\fP xpe::anim::sAnimation::Root"

.SS "\fBint\fP xpe::anim::sAnimation::TicksPerSecond"


.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
