.TH "xpe::core::cThread" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xpe::core::cThread
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <thread\&.hpp>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBePriority\fP { \fBLOWEST\fP, \fBNORMAL\fP, \fBHIGHEST\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBcThread\fP (\fBu32\fP \fBid\fP, std::thread &\fBthread\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBSetFormat\fP (\fBconst\fP \fBchar\fP *\fBname\fP, \fBePriority\fP \fBpriority\fP)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "\fBstatic\fP \fBvoid\fP \fBCurrentSleep\fP (\fBu32\fP \fBmillis\fP)"
.br
.ti -1c
.RI "\fBstatic\fP \fBu32\fP \fBCurrentID\fP ()"
.br
.in -1c
.SH "Member Enumeration Documentation"
.PP 
.SS "\fBenum\fP \fBxpe::core::cThread::ePriority\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fILOWEST \fP\fP
.TP
\fB\fINORMAL \fP\fP
.TP
\fB\fIHIGHEST \fP\fP
.SH "Constructor & Destructor Documentation"
.PP 
.SS "xpe::core::cThread::cThread (\fBu32\fP id, std::thread & thread)"

.SH "Member Function Documentation"
.PP 
.SS "\fBu32\fP xpe::core::cThread::CurrentID ()\fR [static]\fP"

.SS "\fBvoid\fP xpe::core::cThread::CurrentSleep (\fBu32\fP millis)\fR [static]\fP"

.SS "\fBvoid\fP xpe::core::cThread::SetFormat (\fBconst\fP \fBchar\fP * name, \fBePriority\fP priority)"


.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
