.TH "xpe::ecs::cScene" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xpe::ecs::cScene
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <ecs\&.hpp>\fP
.PP
Inherits \fBxpe::core::cObject\fP, \fBxpe::res::cJson\fP, and \fBxpe::res::cXml\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBvoid\fP \fBSetTag\fP (\fBconst\fP \fBstring\fP &\fBtag\fP)"
.br
.ti -1c
.RI "\fBconst\fP \fBstring\fP & \fBGetTag\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBEntityID\fP \fBCreateEntity\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBRemoveEntity\fP (\fBEntityID\fP \fBentityId\fP)"
.br
.ti -1c
.RI "\fBbool\fP \fBIsValidEntity\fP (\fBEntityID\fP \fBentityId\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBClearEntities\fP ()"
.br
.ti -1c
.RI "template<\fBtypename\fP \fBT\fP , typename\&.\&.\&. Args> \fBT\fP & \fBAddComponent\fP (\fBEntityID\fP \fBentityId\fP, \fBArgs\fP &&\&.\&.\&. \fBargs\fP)"
.br
.ti -1c
.RI "template<\fBtypename\fP \fBT\fP > \fBvoid\fP \fBRemoveComponent\fP (\fBEntityID\fP \fBentityId\fP)"
.br
.ti -1c
.RI "template<\fBtypename\fP \fBT\fP > \fBT\fP & \fBGetComponent\fP (\fBEntityID\fP \fBentityId\fP)"
.br
.ti -1c
.RI "template<typename\&.\&.\&. T> \fBbool\fP \fBHasAnyComponent\fP (\fBEntityID\fP \fBentityId\fP)"
.br
.ti -1c
.RI "template<typename\&.\&.\&. T> \fBbool\fP \fBHasAllComponent\fP (\fBEntityID\fP \fBentityId\fP)"
.br
.ti -1c
.RI "template<typename\&.\&.\&. T> \fBvoid\fP \fBClearComponents\fP ()"
.br
.ti -1c
.RI "template<typename\&.\&.\&. T> \fBauto\fP \fBGetComponents\fP ()"
.br
.ti -1c
.RI "\fBunordered_map\fP< \fBComponentID\fP, \fBcJson\fP * > & \fBGetJsons\fP (\fBEntityID\fP \fBentityId\fP)"
.br
.ti -1c
.RI "\fBunordered_map\fP< \fBComponentID\fP, \fBcXml\fP * > & \fBGetXmls\fP (\fBEntityID\fP \fBentityId\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBToJson\fP (\fBjson\fP &\fBroot\fP) \fBoverride\fP"
.br
.ti -1c
.RI "\fBvoid\fP \fBFromJson\fP (\fBjson\fP &\fBroot\fP) \fBoverride\fP"
.br
.ti -1c
.RI "\fBxml\fP \fBToXml\fP (\fBxml\fP &\fBroot\fP) \fBoverride\fP"
.br
.ti -1c
.RI "\fBxml\fP \fBFromXml\fP (\fBxml\fP &\fBroot\fP) \fBoverride\fP"
.br
.in -1c

Public Member Functions inherited from \fBxpe::core::cObject\fP
.in +1c
.ti -1c
.RI "\fBvoid\fP * \fBoperator new\fP (\fBusize\fP \fBbyteSize\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBoperator delete\fP (\fBvoid\fP *\fBaddress\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "physx::PxScene * \fBPhysicsScene\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "template<\fBtypename\fP \fBT\fP , typename\&.\&.\&. Args> \fBT\fP & xpe::ecs::cScene::AddComponent (\fBEntityID\fP entityId, \fBArgs\fP &&\&.\&.\&. args)"

.SS "template<typename\&.\&.\&. T> \fBvoid\fP xpe::ecs::cScene::ClearComponents ()"

.SS "\fBvoid\fP xpe::ecs::cScene::ClearEntities ()"

.SS "\fBEntityID\fP xpe::ecs::cScene::CreateEntity ()"

.SS "\fBvoid\fP xpe::ecs::cScene::FromJson (\fBjson\fP & root)\fR [override]\fP, \fR [virtual]\fP"

.PP
Implements \fBxpe::res::cJson\fP\&.
.SS "\fBxml\fP xpe::ecs::cScene::FromXml (\fBxml\fP & root)\fR [override]\fP, \fR [virtual]\fP"

.PP
Implements \fBxpe::res::cXml\fP\&.
.SS "template<\fBtypename\fP \fBT\fP > \fBT\fP & xpe::ecs::cScene::GetComponent (\fBEntityID\fP entityId)"

.SS "template<typename\&.\&.\&. T> \fBauto\fP xpe::ecs::cScene::GetComponents ()"

.SS "\fBunordered_map\fP< \fBComponentID\fP, \fBcJson\fP * > & xpe::ecs::cScene::GetJsons (\fBEntityID\fP entityId)"

.SS "\fBconst\fP \fBstring\fP & xpe::ecs::cScene::GetTag () const\fR [inline]\fP"

.SS "\fBunordered_map\fP< \fBComponentID\fP, \fBcXml\fP * > & xpe::ecs::cScene::GetXmls (\fBEntityID\fP entityId)"

.SS "template<typename\&.\&.\&. T> \fBbool\fP xpe::ecs::cScene::HasAllComponent (\fBEntityID\fP entityId)"

.SS "template<typename\&.\&.\&. T> \fBbool\fP xpe::ecs::cScene::HasAnyComponent (\fBEntityID\fP entityId)"

.SS "\fBbool\fP xpe::ecs::cScene::IsValidEntity (\fBEntityID\fP entityId)"

.SS "template<\fBtypename\fP \fBT\fP > \fBvoid\fP xpe::ecs::cScene::RemoveComponent (\fBEntityID\fP entityId)"

.SS "\fBvoid\fP xpe::ecs::cScene::RemoveEntity (\fBEntityID\fP entityId)"

.SS "\fBvoid\fP xpe::ecs::cScene::SetTag (\fBconst\fP \fBstring\fP & tag)\fR [inline]\fP"

.SS "\fBvoid\fP xpe::ecs::cScene::ToJson (\fBjson\fP & root)\fR [override]\fP, \fR [virtual]\fP"

.PP
Implements \fBxpe::res::cJson\fP\&.
.SS "\fBxml\fP xpe::ecs::cScene::ToXml (\fBxml\fP & root)\fR [override]\fP, \fR [virtual]\fP"

.PP
Implements \fBxpe::res::cXml\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "physx::PxScene* xpe::ecs::cScene::PhysicsScene"


.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
