.TH "xpe::render::sSpotLightData" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xpe::render::sSpotLightData
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <buffers\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "glm::vec3 \fBPosition\fP = { 0, 0, 0 }"
.br
.ti -1c
.RI "glm::vec3 \fBDirection\fP = { 1, 1, 1 }"
.br
.ti -1c
.RI "glm::vec3 \fBColor\fP = { 1, 1, 1 }"
.br
.ti -1c
.RI "\fBfloat\fP \fBCutoff\fP = 1"
.br
.ti -1c
.RI "\fBfloat\fP \fBOuter\fP = 1"
.br
.ti -1c
.RI "glm::mat4 \fBViewProjection\fP"
.br
.ti -1c
.RI "\fBfloat\fP \fBNear\fP = 0"
.br
.ti -1c
.RI "\fBfloat\fP \fBFar\fP = 1"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "glm::vec3 xpe::render::sSpotLightData::Color = { 1, 1, 1 }"

.SS "\fBfloat\fP xpe::render::sSpotLightData::Cutoff = 1"

.SS "glm::vec3 xpe::render::sSpotLightData::Direction = { 1, 1, 1 }"

.SS "\fBfloat\fP xpe::render::sSpotLightData::Far = 1"

.SS "\fBfloat\fP xpe::render::sSpotLightData::Near = 0"

.SS "\fBfloat\fP xpe::render::sSpotLightData::Outer = 1"

.SS "glm::vec3 xpe::render::sSpotLightData::Position = { 0, 0, 0 }"

.SS "glm::mat4 xpe::render::sSpotLightData::ViewProjection"


.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
