.TH "xpe::core::sWindowDescriptor" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xpe::core::sWindowDescriptor
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <window_manager\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBconst\fP \fBchar\fP * \fBTitle\fP"
.br
.ti -1c
.RI "\fBs32\fP \fBWidth\fP"
.br
.ti -1c
.RI "\fBs32\fP \fBHeight\fP"
.br
.ti -1c
.RI "\fBs32\fP \fBFrameWidth\fP"
.br
.ti -1c
.RI "\fBs32\fP \fBFrameHeight\fP"
.br
.ti -1c
.RI "\fBs32\fP \fBX\fP"
.br
.ti -1c
.RI "\fBs32\fP \fBY\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBVSync\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBFullscreen\fP = \fBfalse\fP"
.br
.ti -1c
.RI "\fBfloat\fP \fBGamma\fP = 2\&.2\fBf\fP"
.br
.ti -1c
.RI "\fBfloat\fP \fBExposure\fP = 1\&.0f"
.br
.ti -1c
.RI "\fBeCursorMode\fP \fBCursorMode\fP = \fBeCursorMode::DEFAULT\fP"
.br
.ti -1c
.RI "\fBeWindowTheme\fP \fBTheme\fP = \fBeWindowTheme::DEFAULT\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBeCursorMode\fP xpe::core::sWindowDescriptor::CursorMode = \fBeCursorMode::DEFAULT\fP"

.SS "\fBfloat\fP xpe::core::sWindowDescriptor::Exposure = 1\&.0f"

.SS "\fBs32\fP xpe::core::sWindowDescriptor::FrameHeight"

.SS "\fBs32\fP xpe::core::sWindowDescriptor::FrameWidth"

.SS "\fBbool\fP xpe::core::sWindowDescriptor::Fullscreen = \fBfalse\fP"

.SS "\fBfloat\fP xpe::core::sWindowDescriptor::Gamma = 2\&.2\fBf\fP"

.SS "\fBs32\fP xpe::core::sWindowDescriptor::Height"

.SS "\fBeWindowTheme\fP xpe::core::sWindowDescriptor::Theme = \fBeWindowTheme::DEFAULT\fP"

.SS "\fBconst\fP \fBchar\fP* xpe::core::sWindowDescriptor::Title"

.SS "\fBbool\fP xpe::core::sWindowDescriptor::VSync"

.SS "\fBs32\fP xpe::core::sWindowDescriptor::Width"

.SS "\fBs32\fP xpe::core::sWindowDescriptor::X"

.SS "\fBs32\fP xpe::core::sWindowDescriptor::Y"


.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
