.TH "xpe::render::cShaderManager" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xpe::render::cShaderManager
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <shader\&.hpp>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "\fBstatic\fP \fBvoid\fP \fBInit\fP ()"
.br
.ti -1c
.RI "\fBstatic\fP \fBvoid\fP \fBFree\fP ()"
.br
.ti -1c
.RI "\fBstatic\fP \fBsShaderStage\fP * \fBGetFromFile\fP (\fBconst\fP \fBsShaderStage::eType\fP &\fBtype\fP, \fBconst\fP \fBchar\fP *\fBfilepath\fP)"
.br
.ti -1c
.RI "\fBstatic\fP \fBsShaderStage\fP * \fBGetFromSrc\fP (\fBconst\fP \fBsShaderStage::eType\fP &\fBtype\fP, \fBconst\fP \fBstring\fP &\fBid\fP, \fBconst\fP \fBstring\fP &\fBsrc\fP)"
.br
.ti -1c
.RI "\fBstatic\fP \fBvoid\fP \fBSetShader\fP (\fBcShader\fP *\fBshader\fP)"
.br
.ti -1c
.RI "\fBstatic\fP \fBvoid\fP \fBSetShaderAfter\fP (\fBcShader\fP *\fBshader\fP, \fBconst\fP \fBstring\fP &\fBname\fP)"
.br
.ti -1c
.RI "\fBstatic\fP \fBcShader\fP * \fBGetShaders\fP (\fBcShader::eCategory\fP \fBcategory\fP)"
.br
.ti -1c
.RI "\fBstatic\fP \fBcShader\fP * \fBGetShader\fP (\fBconst\fP \fBstring\fP &\fBname\fP)"
.br
.ti -1c
.RI "\fBstatic\fP \fBvoid\fP \fBReloadStage\fP (\fBconst\fP \fBchar\fP *\fBfilepath\fP)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "\fBvoid\fP xpe::render::cShaderManager::Free ()\fR [static]\fP"

.SS "\fBsShaderStage\fP * xpe::render::cShaderManager::GetFromFile (\fBconst\fP \fBsShaderStage::eType\fP & type, \fBconst\fP \fBchar\fP * filepath)\fR [static]\fP"

.SS "\fBsShaderStage\fP * xpe::render::cShaderManager::GetFromSrc (\fBconst\fP \fBsShaderStage::eType\fP & type, \fBconst\fP \fBstring\fP & id, \fBconst\fP \fBstring\fP & src)\fR [static]\fP"

.SS "\fBcShader\fP * xpe::render::cShaderManager::GetShader (\fBconst\fP \fBstring\fP & name)\fR [static]\fP"

.SS "\fBcShader\fP * xpe::render::cShaderManager::GetShaders (\fBcShader::eCategory\fP category)\fR [static]\fP"

.SS "\fBvoid\fP xpe::render::cShaderManager::Init ()\fR [static]\fP"

.SS "\fBvoid\fP xpe::render::cShaderManager::ReloadStage (\fBconst\fP \fBchar\fP * filepath)\fR [static]\fP"

.SS "\fBvoid\fP xpe::render::cShaderManager::SetShader (\fBcShader\fP * shader)\fR [static]\fP"

.SS "\fBvoid\fP xpe::render::cShaderManager::SetShaderAfter (\fBcShader\fP * shader, \fBconst\fP \fBstring\fP & name)\fR [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
