.TH "xpe::audio::cAudioManager" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xpe::audio::cAudioManager
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <audio_manager\&.hpp>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "\fBstatic\fP \fBvoid\fP \fBSetListenerPosition\fP (glm::vec3 \fBposition\fP)"
.br
.ti -1c
.RI "\fBstatic\fP \fBvoid\fP \fBSetListenerVelocity\fP (glm::vec3 \fBvelocity\fP)"
.br
.ti -1c
.RI "\fBstatic\fP \fBvoid\fP \fBSetListenerOrientation\fP (\fBf32\fP \fBpitch\fP, \fBf32\fP \fByaw\fP, \fBf32\fP \fBroll\fP, glm::vec3 \fBup\fP)"
.br
.ti -1c
.RI "\fBstatic\fP \fBvoid\fP \fBSetListenerGain\fP (\fBf32\fP \fBvolume\fP)"
.br
.ti -1c
.RI "\fBstatic\fP \fBvoid\fP \fBSetListenerDopplerFactor\fP (\fBf32\fP \fBfactor\fP)"
.br
.ti -1c
.RI "\fBstatic\fP \fBvoid\fP \fBSetListenerSpeedOfSound\fP (\fBf32\fP \fBseed\fP)"
.br
.ti -1c
.RI "\fBstatic\fP \fBvoid\fP \fBVoiceRecord\fP ()"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "\fBclass\fP \fBcAudioSystem\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "\fBvoid\fP xpe::audio::cAudioManager::SetListenerDopplerFactor (\fBf32\fP factor)\fR [static]\fP"

.SS "\fBvoid\fP xpe::audio::cAudioManager::SetListenerGain (\fBf32\fP volume)\fR [static]\fP"

.SS "\fBvoid\fP xpe::audio::cAudioManager::SetListenerOrientation (\fBf32\fP pitch, \fBf32\fP yaw, \fBf32\fP roll, glm::vec3 up)\fR [static]\fP"

.SS "\fBvoid\fP xpe::audio::cAudioManager::SetListenerPosition (glm::vec3 position)\fR [static]\fP"

.SS "\fBvoid\fP xpe::audio::cAudioManager::SetListenerSpeedOfSound (\fBf32\fP seed)\fR [static]\fP"

.SS "\fBvoid\fP xpe::audio::cAudioManager::SetListenerVelocity (glm::vec3 velocity)\fR [static]\fP"

.SS "\fBvoid\fP xpe::audio::cAudioManager::VoiceRecord ()\fR [static]\fP"

.SH "Friends And Related Symbol Documentation"
.PP 
.SS "\fBfriend\fP \fBclass\fP \fBcAudioSystem\fP\fR [friend]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
