.TH "xpe::render::sWidget" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xpe::render::sWidget
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <widget_manager\&.hpp>\fP
.PP
Inherits \fBxpe::res::cXml\fP\&.
.PP
Inherited by \fBxpe::ecs::CButton\fP, \fBxpe::ecs::CContainer\fP, \fBxpe::ecs::CField\fP, and \fBxpe::ecs::CLabel\fP\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "glm::mat4 \fBProjection\fP = glm::mat4(1)"
.br
.in -1c

Public Attributes inherited from \fBxpe::res::cXml\fP
.in +1c
.ti -1c
.RI "\fBxpe::core::vector\fP< \fBcXml\fP * > \fBXmlChildren\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Public Member Functions inherited from \fBxpe::res::cXml\fP
.in +1c
.ti -1c
.RI "\fBvirtual\fP \fBxml\fP \fBToXml\fP (\fBxml\fP &\fBroot\fP)=0"
.br
.ti -1c
.RI "\fBvirtual\fP \fBxml\fP \fBFromXml\fP (\fBxml\fP &\fBroot\fP)=0"
.br
.ti -1c
.RI "\fBbool\fP \fBLoadFile\fP (\fBconst\fP \fBchar\fP *\fBfilepath\fP)"
.br
.ti -1c
.RI "\fBbool\fP \fBSaveFile\fP (\fBconst\fP \fBchar\fP *\fBfilepath\fP)"
.br
.in -1c

Protected Attributes inherited from \fBxpe::res::cXml\fP
.in +1c
.ti -1c
.RI "pugi::xml_document \fBm_Doc\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "glm::mat4 xpe::render::sWidget::Projection = glm::mat4(1)"


.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
