.TH "xpe::render::sDebugMessage" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xpe::render::sDebugMessage
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <debugger\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBint\fP \fBID\fP = 0"
.br
.ti -1c
.RI "\fBhstring\fP \fBDescription\fP = ''"
.br
.ti -1c
.RI "\fBeDebugType\fP \fBType\fP = \fBeDebugType::D_NO_TYPE\fP"
.br
.ti -1c
.RI "\fBeDebugCategory\fP \fBCategory\fP = \fBeDebugCategory::D_NO_CATEGORY\fP"
.br
.ti -1c
.RI "\fBeDebugSeverity\fP \fBSeverity\fP = \fBeDebugSeverity::D_NO_SEVERITY\fP"
.br
.ti -1c
.RI "\fBeDebugErrorType\fP \fBErrorType\fP = \fBeDebugErrorType::D_NO_ERROR_TYPE\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBeDebugCategory\fP xpe::render::sDebugMessage::Category = \fBeDebugCategory::D_NO_CATEGORY\fP"

.SS "\fBhstring\fP xpe::render::sDebugMessage::Description = ''"

.SS "\fBeDebugErrorType\fP xpe::render::sDebugMessage::ErrorType = \fBeDebugErrorType::D_NO_ERROR_TYPE\fP"

.SS "\fBint\fP xpe::render::sDebugMessage::ID = 0"

.SS "\fBeDebugSeverity\fP xpe::render::sDebugMessage::Severity = \fBeDebugSeverity::D_NO_SEVERITY\fP"

.SS "\fBeDebugType\fP xpe::render::sDebugMessage::Type = \fBeDebugType::D_NO_TYPE\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
