.TH "xpe::ecs::CSpace2D" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xpe::ecs::CSpace2D
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <components\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBu8\fP \fB_pad0\fP = 0"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBu8\fP xpe::ecs::CSpace2D::_pad0 = 0"


.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
