.TH "xpe::render::RenderTargets" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xpe::render::RenderTargets
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <bindings\&.hpp>\fP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "\fBstatic\fP \fBsRenderTarget\fP * \fBScene\fP = \fBnullptr\fP"
.br
.ti -1c
.RI "\fBstatic\fP \fBsRenderTarget\fP * \fBOpaque\fP = \fBnullptr\fP"
.br
.ti -1c
.RI "\fBstatic\fP \fBsRenderTarget\fP * \fBTransparent\fP = \fBnullptr\fP"
.br
.ti -1c
.RI "\fBstatic\fP \fBsRenderTarget\fP * \fBUI\fP = \fBnullptr\fP"
.br
.ti -1c
.RI "\fBstatic\fP \fBsRenderTarget\fP * \fBFinal\fP = \fBnullptr\fP"
.br
.ti -1c
.RI "\fBstatic\fP \fBsRenderTarget\fP * \fBShadow\fP = \fBnullptr\fP"
.br
.ti -1c
.RI "\fBstatic\fP \fBsRenderTarget\fP * \fBSSAO\fP = \fBnullptr\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBsRenderTarget\fP * xpe::render::RenderTargets::Final = \fBnullptr\fP\fR [static]\fP"

.SS "\fBsRenderTarget\fP * xpe::render::RenderTargets::Opaque = \fBnullptr\fP\fR [static]\fP"

.SS "\fBsRenderTarget\fP * xpe::render::RenderTargets::Scene = \fBnullptr\fP\fR [static]\fP"

.SS "\fBsRenderTarget\fP * xpe::render::RenderTargets::Shadow = \fBnullptr\fP\fR [static]\fP"

.SS "\fBsRenderTarget\fP * xpe::render::RenderTargets::SSAO = \fBnullptr\fP\fR [static]\fP"

.SS "\fBsRenderTarget\fP * xpe::render::RenderTargets::Transparent = \fBnullptr\fP\fR [static]\fP"

.SS "\fBsRenderTarget\fP * xpe::render::RenderTargets::UI = \fBnullptr\fP\fR [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
