.TH "xpe::math::sTransform" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xpe::math::sTransform
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <transform\&.hpp>\fP
.PP
Inherits \fBxpe::math::sModelMatrix\fP\&.
.PP
Inherited by \fBxpe::ecs::CTransform\fP\&.
.SS "Additional Inherited Members"


Public Attributes inherited from \fBxpe::math::sModelMatrix\fP
.in +1c
.ti -1c
.RI "glm::vec3 \fBPosition\fP = { 0, 0, 0 }"
.br
.ti -1c
.RI "glm::vec3 \fBRotation\fP = { 0, 0, 0 }"
.br
.ti -1c
.RI "glm::vec3 \fBScale\fP = { 1, 1, 1 }"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
