.TH "xpe::anim::sKeyRotate" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xpe::anim::sKeyRotate
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <anim\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsKeyRotate\fP ()=\fBdefault\fP"
.br
.ti -1c
.RI "\fBsKeyRotate\fP (\fBfloat\fP \fBtimestamp\fP, \fBconst\fP glm::quat &\fBorientation\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBfloat\fP \fBTimestamp\fP"
.br
.ti -1c
.RI "glm::quat \fBOrientation\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "xpe::anim::sKeyRotate::sKeyRotate ()\fR [default]\fP"

.SS "xpe::anim::sKeyRotate::sKeyRotate (\fBfloat\fP timestamp, \fBconst\fP glm::quat & orientation)\fR [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "glm::quat xpe::anim::sKeyRotate::Orientation"

.SS "\fBfloat\fP xpe::anim::sKeyRotate::Timestamp"


.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
