.TH "xpe::render::sGeometry" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xpe::render::sGeometry
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <geometry\&.hpp>\fP
.PP
Inherited by \fBxpe::ecs::CGeometry\fP, \fBxpe::render::sCube\fP, \fBxpe::render::sLine\fP, \fBxpe::render::sModel\fP, \fBxpe::render::sPlane\fP, \fBxpe::render::sQuad\fP, \fBxpe::render::sSphere\fP, and \fBxpe::render::sTriangle\fP\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBePrimitiveTopology\fP \fBPrimitiveTopology\fP = \fBePrimitiveTopology::DEFAULT\fP"
.br
.ti -1c
.RI "\fBvector\fP< \fBsVertex\fP > \fBVertices\fP"
.br
.ti -1c
.RI "\fBvector\fP< \fBu32\fP > \fBIndices\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBvector\fP<\fBu32\fP> xpe::render::sGeometry::Indices"

.SS "\fBePrimitiveTopology\fP xpe::render::sGeometry::PrimitiveTopology = \fBePrimitiveTopology::DEFAULT\fP"

.SS "\fBvector\fP<\fBsVertex\fP> xpe::render::sGeometry::Vertices"


.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
