.TH "xpe::math" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xpe::math
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBcMathManager\fP"
.br
.ti -1c
.RI "struct \fBsModelMatrix\fP"
.br
.ti -1c
.RI "struct \fBsRay\fP"
.br
.ti -1c
.RI "struct \fBsTransform\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<\fBtypename\fP \fBT\fP > \fBvoid\fP \fBclamp\fP (\fBT\fP &\fBvalue\fP, \fBconst\fP \fBT\fP \fBmin\fP, \fBconst\fP \fBT\fP \fBmax\fP)"
.br
.ti -1c
.RI "template<\fBtypename\fP \fBT\fP > \fBT\fP \fBmin\fP (\fBconst\fP \fBT\fP &\fBright\fP, \fBconst\fP \fBT\fP &\fBleft\fP)"
.br
.ti -1c
.RI "template<\fBtypename\fP \fBT\fP > \fBT\fP \fBmax\fP (\fBconst\fP \fBT\fP &\fBright\fP, \fBconst\fP \fBT\fP &\fBleft\fP)"
.br
.ti -1c
.RI "\fBJSON\fP (\fBsModelMatrix\fP, Position, Rotation, Scale) \fBstruct\fP \fBENGINE_API\fP \fBsViewMatrix\fP"
.br
.ti -1c
.RI "\fBJSON\fP (\fBsViewMatrix\fP, Position, Front, \fBUp\fP) \fBstruct\fP \fBENGINE_API\fP sOrthoMatrix"
.br
.ti -1c
.RI "\fBJSON\fP (sOrthoMatrix, \fBLeft\fP, \fBRight\fP, \fBBottom\fP, Top, Near, Far) \fBstruct\fP \fBENGINE_API\fP sPerspectiveMatrix"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "template<\fBtypename\fP \fBT\fP > \fBvoid\fP xpe::math::clamp (\fBT\fP & value, \fBconst\fP \fBT\fP min, \fBconst\fP \fBT\fP max)"

.SS "xpe::math::JSON (\fBsModelMatrix\fP, Position, Rotation, Scale)"

.SS "xpe::math::JSON (sOrthoMatrix, \fBLeft\fP, \fBRight\fP, \fBBottom\fP, Top, Near, Far)"

.SS "xpe::math::JSON (\fBsViewMatrix\fP, Position, Front, \fBUp\fP)"

.SS "template<\fBtypename\fP \fBT\fP > \fBT\fP xpe::math::max (\fBconst\fP \fBT\fP & right, \fBconst\fP \fBT\fP & left)"

.SS "template<\fBtypename\fP \fBT\fP > \fBT\fP xpe::math::min (\fBconst\fP \fBT\fP & right, \fBconst\fP \fBT\fP & left)"

.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
