.TH "xpe::anim::sKeyPosition" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xpe::anim::sKeyPosition
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <anim\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsKeyPosition\fP ()=\fBdefault\fP"
.br
.ti -1c
.RI "\fBsKeyPosition\fP (\fBfloat\fP \fBtimestamp\fP, \fBconst\fP glm::vec3 &\fBposition\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBfloat\fP \fBTimestamp\fP"
.br
.ti -1c
.RI "glm::vec3 \fBPosition\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "xpe::anim::sKeyPosition::sKeyPosition ()\fR [default]\fP"

.SS "xpe::anim::sKeyPosition::sKeyPosition (\fBfloat\fP timestamp, \fBconst\fP glm::vec3 & position)\fR [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "glm::vec3 xpe::anim::sKeyPosition::Position"

.SS "\fBfloat\fP xpe::anim::sKeyPosition::Timestamp"


.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
