.TH "xpe::core::sCpuStats" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xpe::core::sCpuStats
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <hardware_manager\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBu32\fP \fBCores\fP = 1"
.br
.ti -1c
.RI "\fBu32\fP \fBThreads\fP = 1"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBu32\fP xpe::core::sCpuStats::Cores = 1"

.SS "\fBu32\fP xpe::core::sCpuStats::Threads = 1"


.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
