.TH "xpe::physics::cPhysicsSystem" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xpe::physics::cPhysicsSystem
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <physics_system\&.hpp>\fP
.PP
Inherits \fBxpe::ecs::cSystem\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBvoid\fP \fBUpdate\fP (\fBcScene\fP *\fBscene\fP, \fBconst\fP \fBcTime\fP &\fBdt\fP) \fBoverride\fP \fBfinal\fP"
.br
.in -1c

Public Member Functions inherited from \fBxpe::core::cObject\fP
.in +1c
.ti -1c
.RI "\fBvoid\fP * \fBoperator new\fP (\fBusize\fP \fBbyteSize\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBoperator delete\fP (\fBvoid\fP *\fBaddress\fP)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "\fBvoid\fP xpe::physics::cPhysicsSystem::Update (\fBcScene\fP * scene, \fBconst\fP \fBcTime\fP & dt)\fR [final]\fP, \fR [override]\fP, \fR [virtual]\fP"

.PP
Implements \fBxpe::ecs::cSystem\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
