.TH "xpe::ecs::CDirectionalLight" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xpe::ecs::CDirectionalLight
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <components\&.hpp>\fP
.PP
Inherits \fBxpe::res::cJson\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCDirectionalLight\fP (\fBconst\fP glm::vec3 &\fBposition\fP, \fBconst\fP glm::vec3 &\fBcolor\fP)"
.br
.in -1c

Public Member Functions inherited from \fBxpe::res::cJson\fP
.in +1c
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBToJson\fP (\fBjson\fP &\fBroot\fP)=0"
.br
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBFromJson\fP (\fBjson\fP &\fBroot\fP)=0"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "glm::vec3 \fBColor\fP = { 1, 1, 1 }"
.br
.ti -1c
.RI "sOrthoMatrix \fBProjection\fP"
.br
.ti -1c
.RI "\fBsViewMatrix\fP \fBView\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "xpe::ecs::CDirectionalLight::CDirectionalLight (\fBconst\fP glm::vec3 & position, \fBconst\fP glm::vec3 & color)\fR [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "glm::vec3 xpe::ecs::CDirectionalLight::Color = { 1, 1, 1 }"

.SS "sOrthoMatrix xpe::ecs::CDirectionalLight::Projection"

.SS "\fBsViewMatrix\fP xpe::ecs::CDirectionalLight::View"


.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
