.TH "xpe::physics::sBoxShapeDescriptor" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xpe::physics::sBoxShapeDescriptor
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <physics_manager\&.hpp>\fP
.PP
Inherits sShapeDescriptor\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsBoxShapeDescriptor\fP ()=\fBdelete\fP"
.br
.ti -1c
.RI "\fBsBoxShapeDescriptor\fP (\fBconst\fP glm::vec3 &\fBhalfExtents\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "glm::vec3 \fBHalfExtents\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "xpe::physics::sBoxShapeDescriptor::sBoxShapeDescriptor ()\fR [delete]\fP"

.SS "xpe::physics::sBoxShapeDescriptor::sBoxShapeDescriptor (\fBconst\fP glm::vec3 & halfExtents)\fR [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "glm::vec3 xpe::physics::sBoxShapeDescriptor::HalfExtents"


.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
