.TH "xpe::core::sObserverWindowRatio" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xpe::core::sObserverWindowRatio
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <observers\&.hpp>\fP
.PP
Inherits \fBxpe::core::sObserver< float >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsObserverWindowRatio\fP (\fBfloat\fP \fBratio\fP)"
.br
.in -1c

Public Member Functions inherited from \fBxpe::core::sObserver< float >\fP
.in +1c
.ti -1c
.RI "\fBsObserver\fP (\fBconst\fP \fBfloat\fP &\fBvalue\fP, \fBconst\fP std::function< \fBvoid\fP(\fBfloat\fP)> \fBonChanged\fP={})"
.br
.ti -1c
.RI "\fBsObserver\fP & \fBoperator=\fP (\fBconst\fP \fBfloat\fP &\fBother\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBoperator()\fP ()"
.br
.ti -1c
.RI "\fBoperator float\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBoperator==\fP (\fBconst\fP \fBfloat\fP &\fBother\fP)"
.br
.ti -1c
.RI "\fBbool\fP \fBoperator==\fP (\fBu32\fP \fBother\fP)"
.br
.ti -1c
.RI "\fBbool\fP \fBoperator==\fP (\fBint\fP \fBother\fP)"
.br
.ti -1c
.RI "\fBbool\fP \fBoperator!=\fP (\fBconst\fP \fBfloat\fP &\fBother\fP)"
.br
.ti -1c
.RI "\fBbool\fP \fBoperator!=\fP (\fBu32\fP \fBother\fP)"
.br
.ti -1c
.RI "\fBbool\fP \fBoperator!=\fP (\fBint\fP \fBother\fP)"
.br
.ti -1c
.RI "\fBbool\fP \fBoperator>\fP (\fBconst\fP \fBfloat\fP &\fBother\fP)"
.br
.ti -1c
.RI "\fBbool\fP \fBoperator>\fP (\fBu32\fP \fBother\fP)"
.br
.ti -1c
.RI "\fBbool\fP \fBoperator>\fP (\fBint\fP \fBother\fP)"
.br
.ti -1c
.RI "\fBbool\fP \fBoperator<\fP (\fBconst\fP \fBfloat\fP &\fBother\fP)"
.br
.ti -1c
.RI "\fBbool\fP \fBoperator<\fP (\fBu32\fP \fBother\fP)"
.br
.ti -1c
.RI "\fBbool\fP \fBoperator<\fP (\fBint\fP \fBother\fP)"
.br
.ti -1c
.RI "\fBbool\fP \fBoperator<=\fP (\fBconst\fP \fBfloat\fP &\fBother\fP)"
.br
.ti -1c
.RI "\fBbool\fP \fBoperator<=\fP (\fBu32\fP \fBother\fP)"
.br
.ti -1c
.RI "\fBbool\fP \fBoperator<=\fP (\fBint\fP \fBother\fP)"
.br
.ti -1c
.RI "\fBbool\fP \fBoperator>=\fP (\fBconst\fP \fBfloat\fP &\fBother\fP)"
.br
.ti -1c
.RI "\fBbool\fP \fBoperator>=\fP (\fBu32\fP \fBother\fP)"
.br
.ti -1c
.RI "\fBbool\fP \fBoperator>=\fP (\fBint\fP \fBother\fP)"
.br
.in -1c
.SS "Additional Inherited Members"


Public Attributes inherited from \fBxpe::core::sObserver< float >\fP
.in +1c
.ti -1c
.RI "\fBfloat\fP \fBValue\fP"
.br
.in -1c

Protected Attributes inherited from \fBxpe::core::sObserver< float >\fP
.in +1c
.ti -1c
.RI "std::function< \fBvoid\fP(\fBfloat\fP)> \fBm_OnChanged\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "xpe::core::sObserverWindowRatio::sObserverWindowRatio (\fBfloat\fP ratio)"


.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
