.TH "xpe::physics" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xpe::physics
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBcPhysicsAllocator\fP"
.br
.ti -1c
.RI "class \fBcPhysicsErrorCallback\fP"
.br
.ti -1c
.RI "class \fBcPhysicsManager\fP"
.br
.ti -1c
.RI "class \fBcPhysicsSimulationEventCallback\fP"
.br
.ti -1c
.RI "class \fBcPhysicsSystem\fP"
.br
.ti -1c
.RI "struct \fBsActor\fP"
.br
.ti -1c
.RI "struct \fBsBoxShapeDescriptor\fP"
.br
.ti -1c
.RI "struct \fBsCapsuleShapeDescriptor\fP"
.br
.ti -1c
.RI "struct \fBsPlaneShapeDescriptor\fP"
.br
.ti -1c
.RI "struct \fBsRagdoll\fP"
.br
.ti -1c
.RI "struct \fBsSphereShapeDescriptor\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum class \fBeShapeType\fP { \fBNONE\fP = 0, \fBSPHERE\fP = 1, \fBCAPSULE\fP = 2, \fBBOX\fP = 3, \fBPLANE\fP = 4 }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBPxFilterFlags\fP \fBFilterShader\fP (\fBPxFilterObjectAttributes\fP \fBattributes0\fP, \fBPxFilterData\fP \fBfilterData0\fP, \fBPxFilterObjectAttributes\fP \fBattributes1\fP, \fBPxFilterData\fP \fBfilterData1\fP, \fBPxPairFlags\fP &\fBpairFlags\fP, \fBconst\fP \fBvoid\fP *\fBconstantBlock\fP, \fBPxU32\fP \fBconstantBlockSize\fP)"
.br
.ti -1c
.RI "glm::vec3 \fBQuatToEuler\fP (\fBf32\fP \fBw\fP, \fBf32\fP \fBx\fP, \fBf32\fP \fBy\fP, \fBf32\fP \fBz\fP)"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "\fBenum\fP \fBclass\fP \fBxpe::physics::eShapeType\fP\fR [strong]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fINONE \fP\fP
.TP
\fB\fISPHERE \fP\fP
.TP
\fB\fICAPSULE \fP\fP
.TP
\fB\fIBOX \fP\fP
.TP
\fB\fIPLANE \fP\fP
.SH "Function Documentation"
.PP 
.SS "\fBPxFilterFlags\fP xpe::physics::FilterShader (\fBPxFilterObjectAttributes\fP attributes0, \fBPxFilterData\fP filterData0, \fBPxFilterObjectAttributes\fP attributes1, \fBPxFilterData\fP filterData1, \fBPxPairFlags\fP & pairFlags, \fBconst\fP \fBvoid\fP * constantBlock, \fBPxU32\fP constantBlockSize)"

.SS "glm::vec3 xpe::physics::QuatToEuler (\fBf32\fP w, \fBf32\fP x, \fBf32\fP y, \fBf32\fP z)"

.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
