.TH "xpe::anim::sAnimationNode" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xpe::anim::sAnimationNode
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <anim\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBstring\fP \fBName\fP"
.br
.ti -1c
.RI "glm::mat4 \fBTransform\fP"
.br
.ti -1c
.RI "\fBvector\fP< \fBsAnimationNode\fP > \fBChildren\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBvector\fP<\fBsAnimationNode\fP> xpe::anim::sAnimationNode::Children"

.SS "\fBstring\fP xpe::anim::sAnimationNode::Name"

.SS "glm::mat4 xpe::anim::sAnimationNode::Transform"


.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
