.TH "xpe::render::sMaterialFormat" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xpe::render::sMaterialFormat
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <material\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBeTextureFormat\fP \fBFormat\fP"
.br
.ti -1c
.RI "\fBusize\fP \fBWidth\fP"
.br
.ti -1c
.RI "\fBusize\fP \fBHeight\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBSlot\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBeTextureFormat\fP xpe::render::sMaterialFormat::Format"

.SS "\fBusize\fP xpe::render::sMaterialFormat::Height"

.SS "\fBu32\fP xpe::render::sMaterialFormat::Slot"

.SS "\fBusize\fP xpe::render::sMaterialFormat::Width"


.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
