.TH "xpe::ecs::CGeometry" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xpe::ecs::CGeometry
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <components\&.hpp>\fP
.PP
Inherits \fBxpe::render::sGeometry\fP, and \fBxpe::res::cJson\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCGeometry\fP (\fBconst\fP \fBsGeometry\fP &\fBgeometry\fP={})"
.br
.ti -1c
.RI "\fBCGeometry\fP (\fBsGeometry\fP &&\fBgeometry\fP)"
.br
.in -1c

Public Member Functions inherited from \fBxpe::res::cJson\fP
.in +1c
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBToJson\fP (\fBjson\fP &\fBroot\fP)=0"
.br
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBFromJson\fP (\fBjson\fP &\fBroot\fP)=0"
.br
.in -1c
.SS "Additional Inherited Members"


Public Attributes inherited from \fBxpe::render::sGeometry\fP
.in +1c
.ti -1c
.RI "\fBePrimitiveTopology\fP \fBPrimitiveTopology\fP = \fBePrimitiveTopology::DEFAULT\fP"
.br
.ti -1c
.RI "\fBvector\fP< \fBsVertex\fP > \fBVertices\fP"
.br
.ti -1c
.RI "\fBvector\fP< \fBu32\fP > \fBIndices\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "xpe::ecs::CGeometry::CGeometry (\fBconst\fP \fBsGeometry\fP & geometry = \fR{}\fP)\fR [inline]\fP"

.SS "xpe::ecs::CGeometry::CGeometry (\fBsGeometry\fP && geometry)\fR [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
