.TH "xpe::anim::sSkeleton" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xpe::anim::sSkeleton
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <skeleton\&.hpp>\fP
.PP
Inherited by \fBxpe::ecs::CSkeleton\fP\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBunordered_map\fP< \fBstring\fP, \fBsBone\fP > \fBBones\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBunordered_map\fP<\fBstring\fP, \fBsBone\fP> xpe::anim::sSkeleton::Bones"


.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
