.TH "xpe::core::sKeyState" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xpe::core::sKeyState
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <codes_keyboard\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBbool\fP \fBPressed\fP = \fBfalse\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBReleased\fP = \fBfalse\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBHold\fP = \fBfalse\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBbool\fP xpe::core::sKeyState::Hold = \fBfalse\fP"

.SS "\fBbool\fP xpe::core::sKeyState::Pressed = \fBfalse\fP"

.SS "\fBbool\fP xpe::core::sKeyState::Released = \fBfalse\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
