.TH "xpe::res::cJson" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xpe::res::cJson
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <json\&.hpp>\fP
.PP
Inherited by \fBxpe::core::sAppConfig\fP, \fBxpe::ecs::CAnimation\fP, \fBxpe::ecs::CAudio\fP, \fBxpe::ecs::CCamera\fP, \fBxpe::ecs::CDirectionalLight\fP, \fBxpe::ecs::CGeometry\fP, \fBxpe::ecs::CMaterial\fP, \fBxpe::ecs::CPhysicsActor\fP, \fBxpe::ecs::CPointLight\fP, \fBxpe::ecs::CSkeleton\fP, \fBxpe::ecs::CSpotLight\fP, \fBxpe::ecs::CStreamAudio\fP, \fBxpe::ecs::CVoice\fP, \fBxpe::ecs::cEntity\fP, \fBxpe::ecs::cScene\fP\fR [private]\fP, and \fBxpe::render::cCamera\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBToJson\fP (\fBjson\fP &\fBroot\fP)=0"
.br
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBFromJson\fP (\fBjson\fP &\fBroot\fP)=0"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "\fBvirtual\fP \fBvoid\fP xpe::res::cJson::FromJson (\fBjson\fP & root)\fR [pure virtual]\fP"

.PP
Implemented in \fBxpe::ecs::cScene\fP, and \fBxpe::ecs::cEntity\fP\&.
.SS "\fBvirtual\fP \fBvoid\fP xpe::res::cJson::ToJson (\fBjson\fP & root)\fR [pure virtual]\fP"

.PP
Implemented in \fBxpe::ecs::cScene\fP, and \fBxpe::ecs::cEntity\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
