.TH "xpe::ecs::CGeometryInfo" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xpe::ecs::CGeometryInfo
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <components\&.hpp>\fP
.PP
Inherits \fBxpe::render::sGeometryInfo\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCGeometryInfo\fP (\fBconst\fP \fBsGeometryInfo\fP &\fBgeometryInfo\fP={})"
.br
.ti -1c
.RI "\fBCGeometryInfo\fP (\fBsGeometryInfo\fP &&\fBgeometryInfo\fP)"
.br
.in -1c
.SS "Additional Inherited Members"


Public Attributes inherited from \fBxpe::render::sGeometryInfo\fP
.in +1c
.ti -1c
.RI "\fBePrimitiveTopology\fP \fBPrimitiveTopology\fP = \fBePrimitiveTopology::DEFAULT\fP"
.br
.ti -1c
.RI "\fBusize\fP \fBVertexOffset\fP = 0"
.br
.ti -1c
.RI "\fBusize\fP \fBIndexOffset\fP = 0"
.br
.ti -1c
.RI "\fBusize\fP \fBVertexCount\fP = 0"
.br
.ti -1c
.RI "\fBusize\fP \fBIndexCount\fP = 0"
.br
.ti -1c
.RI "\fBvector\fP< \fBEntityID\fP > \fBEntities\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "xpe::ecs::CGeometryInfo::CGeometryInfo (\fBconst\fP \fBsGeometryInfo\fP & geometryInfo = \fR{}\fP)\fR [inline]\fP"

.SS "xpe::ecs::CGeometryInfo::CGeometryInfo (\fBsGeometryInfo\fP && geometryInfo)\fR [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
