.TH "xpe::render::Textures" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xpe::render::Textures
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <bindings\&.hpp>\fP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "\fBstatic\fP \fBsTexture\fP * \fBCanvas\fP = \fBnullptr\fP"
.br
.ti -1c
.RI "\fBstatic\fP \fBsTexture\fP * \fBSharedDepth\fP = \fBnullptr\fP"
.br
.ti -1c
.RI "\fBstatic\fP \fBsTexture\fP * \fBAlbedoAtlas\fP = \fBnullptr\fP"
.br
.ti -1c
.RI "\fBstatic\fP \fBsTexture\fP * \fBNormalAtlas\fP = \fBnullptr\fP"
.br
.ti -1c
.RI "\fBstatic\fP \fBsTexture\fP * \fBParallaxAtlas\fP = \fBnullptr\fP"
.br
.ti -1c
.RI "\fBstatic\fP \fBsTexture\fP * \fBMetalAtlas\fP = \fBnullptr\fP"
.br
.ti -1c
.RI "\fBstatic\fP \fBsTexture\fP * \fBRoughnessAtlas\fP = \fBnullptr\fP"
.br
.ti -1c
.RI "\fBstatic\fP \fBsTexture\fP * \fBAOAtlas\fP = \fBnullptr\fP"
.br
.ti -1c
.RI "\fBstatic\fP \fBsTexture\fP * \fBEmissionAtlas\fP = \fBnullptr\fP"
.br
.ti -1c
.RI "\fBstatic\fP \fBsAtlas\fP * \fBWidgetAtlas\fP = \fBnullptr\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBsTexture\fP * xpe::render::Textures::AlbedoAtlas = \fBnullptr\fP\fR [static]\fP"

.SS "\fBsTexture\fP * xpe::render::Textures::AOAtlas = \fBnullptr\fP\fR [static]\fP"

.SS "\fBsTexture\fP * xpe::render::Textures::Canvas = \fBnullptr\fP\fR [static]\fP"

.SS "\fBsTexture\fP * xpe::render::Textures::EmissionAtlas = \fBnullptr\fP\fR [static]\fP"

.SS "\fBsTexture\fP * xpe::render::Textures::MetalAtlas = \fBnullptr\fP\fR [static]\fP"

.SS "\fBsTexture\fP * xpe::render::Textures::NormalAtlas = \fBnullptr\fP\fR [static]\fP"

.SS "\fBsTexture\fP * xpe::render::Textures::ParallaxAtlas = \fBnullptr\fP\fR [static]\fP"

.SS "\fBsTexture\fP * xpe::render::Textures::RoughnessAtlas = \fBnullptr\fP\fR [static]\fP"

.SS "\fBsTexture\fP * xpe::render::Textures::SharedDepth = \fBnullptr\fP\fR [static]\fP"

.SS "\fBsAtlas\fP * xpe::render::Textures::WidgetAtlas = \fBnullptr\fP\fR [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
