.TH "xpe::audio" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xpe::audio
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBcontext\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBcAudioManager\fP"
.br
.ti -1c
.RI "class \fBcAudioSystem\fP"
.br
.ti -1c
.RI "struct \fBsAudioFile\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBeAudioState\fP { \fBINITIAL\fP, \fBPLAYING\fP, \fBPAUSED\fP, \fBSTOPPED\fP }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBJSON_ENUM\fP (\fBeAudioState\fP, { { \fBeAudioState::INITIAL\fP, 'INITIAL' }, { \fBeAudioState::PLAYING\fP, 'PLAYING' }, { \fBeAudioState::PAUSED\fP, 'PAUSED' }, { \fBeAudioState::STOPPED\fP, 'STOPPED' }, }) \fBenum\fP \fBeAudioError\fP"
.br
.ti -1c
.RI "\fBJSON_ENUM\fP (\fBeAudioError\fP, { { eAudioError::NONE, 'INITIAL' }, { eAudioError::INVALID_NAME, 'INVALID_NAME' }, { eAudioError::INVALID_ENUM, 'INVALID_ENUM' }, { eAudioError::INVALID_VALUE, 'INVALID_VALUE' }, { eAudioError::INVALID_OPERATION, 'INVALID_OPERATION' }, { eAudioError::OUT_OF_MEMORY, 'OUT_OF_MEMORY' }, }) \fBstruct\fP \fBENGINE_API\fP \fBsAudioSource\fP"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "\fBenum\fP \fBxpe::audio::eAudioState\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIINITIAL \fP\fP
.TP
\fB\fIPLAYING \fP\fP
.TP
\fB\fIPAUSED \fP\fP
.TP
\fB\fISTOPPED \fP\fP
.SH "Function Documentation"
.PP 
.SS "xpe::audio::JSON_ENUM (\fBeAudioError\fP, { { eAudioError::NONE, 'INITIAL' }, { eAudioError::INVALID_NAME, 'INVALID_NAME' }, { eAudioError::INVALID_ENUM, 'INVALID_ENUM' }, { eAudioError::INVALID_VALUE, 'INVALID_VALUE' }, { eAudioError::INVALID_OPERATION, 'INVALID_OPERATION' }, { eAudioError::OUT_OF_MEMORY, 'OUT_OF_MEMORY' }, })"

.SS "xpe::audio::JSON_ENUM (\fBeAudioState\fP, { { \fBeAudioState::INITIAL\fP, 'INITIAL' }, { \fBeAudioState::PLAYING\fP, 'PLAYING' }, { \fBeAudioState::PAUSED\fP, 'PAUSED' }, { \fBeAudioState::STOPPED\fP, 'STOPPED' }, })"

.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
