.TH "xpe::render::sDirectLightData" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xpe::render::sDirectLightData
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <buffers\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "glm::vec3 \fBPosition\fP = { 0, 0, 0 }"
.br
.ti -1c
.RI "glm::vec3 \fBColor\fP = { 1, 1, 1 }"
.br
.ti -1c
.RI "glm::mat4 \fBViewProjection\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "glm::vec3 xpe::render::sDirectLightData::Color = { 1, 1, 1 }"

.SS "glm::vec3 xpe::render::sDirectLightData::Position = { 0, 0, 0 }"

.SS "glm::mat4 xpe::render::sDirectLightData::ViewProjection"


.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
