.TH "xpe::render::cShadowShader" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xpe::render::cShadowShader
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <shaders\&.hpp>\fP
.PP
Inherits \fBxpe::render::cInstancingShader\fP\&.
.PP
Inherited by \fBxpe::render::cDirectionalShadowShader\fP, \fBxpe::render::cPointShadowShader\fP, and \fBxpe::render::cSpotShadowShader\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBcShadowShader\fP (\fBconst\fP \fBstring\fP &\fBname\fP)"
.br
.in -1c

Public Member Functions inherited from \fBxpe::render::cInstancingShader\fP
.in +1c
.ti -1c
.RI "\fBcInstancingShader\fP (\fBeCategory\fP \fBcategory\fP, \fBconst\fP \fBstring\fP &\fBname\fP)"
.br
.in -1c

Public Member Functions inherited from \fBxpe::render::cDefaultShader\fP
.in +1c
.ti -1c
.RI "\fBcDefaultShader\fP (\fBcShader::eCategory\fP \fBcategory\fP, \fBconst\fP \fBstring\fP &\fBname\fP)"
.br
.ti -1c
.RI "\fB~cDefaultShader\fP () \fBoverride\fP"
.br
.ti -1c
.RI "\fBvoid\fP \fBBind\fP () \fBoverride\fP"
.br
.ti -1c
.RI "\fBvoid\fP \fBUnbind\fP () \fBoverride\fP"
.br
.in -1c

Public Member Functions inherited from \fBxpe::render::cShader\fP
.in +1c
.ti -1c
.RI "\fBcShader\fP (\fBcShader::eCategory\fP \fBcategory\fP, \fBconst\fP \fBstring\fP &\fBname\fP)"
.br
.ti -1c
.RI "\fBvirtual\fP \fB~cShader\fP ()"
.br
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBDraw\fP (\fBecs::cScene\fP *\fBscene\fP)"
.br
.in -1c

Public Member Functions inherited from \fBxpe::core::cObject\fP
.in +1c
.ti -1c
.RI "\fBvoid\fP * \fBoperator new\fP (\fBusize\fP \fBbyteSize\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBoperator delete\fP (\fBvoid\fP *\fBaddress\fP)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBvoid\fP \fBDrawShadow\fP (\fBcScene\fP *\fBscene\fP, \fBu32\fP \fBlightIndex\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBInitPrepass\fP () \fBoverride\fP"
.br
.in -1c

Protected Member Functions inherited from \fBxpe::render::cInstancingShader\fP
.in +1c
.ti -1c
.RI "\fBvoid\fP \fBDrawInstanced\fP (\fBcScene\fP *\fBscene\fP, \fBconst\fP \fBsGeometryInfo\fP &\fBgeometryInfo\fP, \fBconst\fP std::function< \fBvoid\fP(\fBEntityID\fP \fBentityId\fP, \fBsRenderInstance\fP &)> &\fBcallback\fP=[](\fBEntityID\fP, \fBsRenderInstance\fP &) {})"
.br
.in -1c

Protected Member Functions inherited from \fBxpe::render::cDefaultShader\fP
.in +1c
.ti -1c
.RI "\fBvoid\fP \fBInit\fP ()"
.br
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBInitOpaque\fP ()"
.br
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBInitTransparent\fP ()"
.br
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBInitPostFX\fP ()"
.br
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBInitUI\fP ()"
.br
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBInitFinal\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"


Public Types inherited from \fBxpe::render::cShader\fP
.in +1c
.ti -1c
.RI "enum \fBeCategory\fP { \fBNONE\fP = 0, \fBPREPASS\fP = 1, \fBOPAQUE\fP = 2, \fBTRANSPARENT\fP = 3, \fBPOSTFX\fP = 4, \fBUI\fP = 5, \fBFINAL\fP = 6, \fBCOMPUTE\fP = 7 }"
.br
.in -1c

Public Attributes inherited from \fBxpe::render::cDefaultShader\fP
.in +1c
.ti -1c
.RI "\fBePrimitiveTopology\fP \fBPrimitiveTopology\fP = \fBePrimitiveTopology::DEFAULT\fP"
.br
.ti -1c
.RI "\fBsInputLayout\fP \fBInputLayout\fP = \fBsVertex::k_Format\fP"
.br
.ti -1c
.RI "\fBsShaderStage\fP * \fBVertexStage\fP = \fBnullptr\fP"
.br
.ti -1c
.RI "\fBsShaderStage\fP * \fBPixelStage\fP = \fBnullptr\fP"
.br
.ti -1c
.RI "\fBsShaderStage\fP * \fBGeometryStage\fP = \fBnullptr\fP"
.br
.ti -1c
.RI "\fBsRenderTarget\fP * \fBRenderTarget\fP = \fBnullptr\fP"
.br
.ti -1c
.RI "\fBsRasterizer\fP \fBRasterizer\fP"
.br
.ti -1c
.RI "\fBsDepthStencilMode\fP \fBDepthStencilMode\fP"
.br
.ti -1c
.RI "\fBsBlendMode\fP \fBBlendMode\fP"
.br
.in -1c

Public Attributes inherited from \fBxpe::render::cShader\fP
.in +1c
.ti -1c
.RI "\fBu64\fP \fBID\fP = 0"
.br
.ti -1c
.RI "\fBbool\fP \fBEnable\fP = \fBtrue\fP"
.br
.ti -1c
.RI "\fBeCategory\fP \fBCategory\fP = \fBeCategory::PREPASS\fP"
.br
.ti -1c
.RI "\fBcShader\fP * \fBNext\fP = \fBnullptr\fP"
.br
.in -1c

Protected Attributes inherited from \fBxpe::render::cInstancingShader\fP
.in +1c
.ti -1c
.RI "\fBsInstanceBuffer\fP \fBm_InstanceBuffer\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "xpe::render::cShadowShader::cShadowShader (\fBconst\fP \fBstring\fP & name)"

.SH "Member Function Documentation"
.PP 
.SS "\fBvoid\fP xpe::render::cShadowShader::DrawShadow (\fBcScene\fP * scene, \fBu32\fP lightIndex)\fR [protected]\fP"

.SS "\fBvoid\fP xpe::render::cShadowShader::InitPrepass ()\fR [override]\fP, \fR [protected]\fP, \fR [virtual]\fP"

.PP
Reimplemented from \fBxpe::render::cDefaultShader\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
