.TH "xpe::physics::cPhysicsErrorCallback" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xpe::physics::cPhysicsErrorCallback
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <callbacks\&.hpp>\fP
.PP
Inherits PxErrorCallback\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBcPhysicsErrorCallback\fP (\fBbool\fP \fBenableInfo\fP=\fBtrue\fP, \fBbool\fP \fBenableWarning\fP=\fBtrue\fP, \fBbool\fP \fBenableError\fP=\fBtrue\fP)"
.br
.ti -1c
.RI "\fB~cPhysicsErrorCallback\fP () \fBoverride\fP"
.br
.ti -1c
.RI "\fBvoid\fP \fBreportError\fP (PxErrorCode::Enum \fBcode\fP, \fBconst\fP \fBchar\fP *\fBmessage\fP, \fBconst\fP \fBchar\fP *\fBfile\fP, \fBint\fP \fBline\fP) \fBoverride\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBbool\fP \fBEnableInfo\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBEnableWarning\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBEnableError\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "xpe::physics::cPhysicsErrorCallback::cPhysicsErrorCallback (\fBbool\fP enableInfo = \fR\fBtrue\fP\fP, \fBbool\fP enableWarning = \fR\fBtrue\fP\fP, \fBbool\fP enableError = \fR\fBtrue\fP\fP)"

.SS "xpe::physics::cPhysicsErrorCallback::~cPhysicsErrorCallback ()\fR [override]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBvoid\fP xpe::physics::cPhysicsErrorCallback::reportError (PxErrorCode::Enum code, \fBconst\fP \fBchar\fP * message, \fBconst\fP \fBchar\fP * file, \fBint\fP line)\fR [override]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBbool\fP xpe::physics::cPhysicsErrorCallback::EnableError"

.SS "\fBbool\fP xpe::physics::cPhysicsErrorCallback::EnableInfo"

.SS "\fBbool\fP xpe::physics::cPhysicsErrorCallback::EnableWarning"


.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
