.TH "xpe::render::cCameraManager" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xpe::render::cCameraManager
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <camera_manager\&.hpp>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "\fBstatic\fP \fBvoid\fP \fBInit\fP ()"
.br
.ti -1c
.RI "\fBstatic\fP \fBvoid\fP \fBFree\fP ()"
.br
.ti -1c
.RI "\fBstatic\fP glm::mat4 \fBGetViewProjection\fP ()"
.br
.ti -1c
.RI "\fBstatic\fP \fBvoid\fP \fBFlush\fP ()"
.br
.ti -1c
.RI "\fBstatic\fP \fBvoid\fP \fBBind\fP ()"
.br
.ti -1c
.RI "\fBstatic\fP \fBvoid\fP \fBUnbind\fP ()"
.br
.ti -1c
.RI "\fBstatic\fP \fBvoid\fP \fBSetExposure\fP (\fBfloat\fP \fBexposure\fP)"
.br
.ti -1c
.RI "\fBstatic\fP \fBvoid\fP \fBSetGamma\fP (\fBfloat\fP \fBgamma\fP)"
.br
.ti -1c
.RI "\fBstatic\fP \fBfloat\fP \fBGetExposure\fP ()"
.br
.ti -1c
.RI "\fBstatic\fP \fBfloat\fP \fBGetGamma\fP ()"
.br
.ti -1c
.RI "\fBstatic\fP \fBvoid\fP \fBSetViewport\fP (\fBconst\fP \fBsViewport\fP &\fBviewport\fP)"
.br
.ti -1c
.RI "\fBstatic\fP \fBsViewport\fP * \fBGetViewport\fP ()"
.br
.ti -1c
.RI "\fBstatic\fP \fBcCamera\fP * \fBGetCamera\fP ()"
.br
.ti -1c
.RI "\fBstatic\fP \fBvoid\fP \fBSetCamera\fP (\fBcCamera\fP *\fBcamera\fP)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "\fBvoid\fP xpe::render::cCameraManager::Bind ()\fR [static]\fP"

.SS "\fBvoid\fP xpe::render::cCameraManager::Flush ()\fR [static]\fP"

.SS "\fBvoid\fP xpe::render::cCameraManager::Free ()\fR [static]\fP"

.SS "\fBcCamera\fP * xpe::render::cCameraManager::GetCamera ()\fR [static]\fP"

.SS "\fBfloat\fP xpe::render::cCameraManager::GetExposure ()\fR [static]\fP"

.SS "\fBfloat\fP xpe::render::cCameraManager::GetGamma ()\fR [static]\fP"

.SS "\fBsViewport\fP * xpe::render::cCameraManager::GetViewport ()\fR [static]\fP"

.SS "glm::mat4 xpe::render::cCameraManager::GetViewProjection ()\fR [static]\fP"

.SS "\fBvoid\fP xpe::render::cCameraManager::Init ()\fR [static]\fP"

.SS "\fBvoid\fP xpe::render::cCameraManager::SetCamera (\fBcCamera\fP * camera)\fR [static]\fP"

.SS "\fBvoid\fP xpe::render::cCameraManager::SetExposure (\fBfloat\fP exposure)\fR [static]\fP"

.SS "\fBvoid\fP xpe::render::cCameraManager::SetGamma (\fBfloat\fP gamma)\fR [static]\fP"

.SS "\fBvoid\fP xpe::render::cCameraManager::SetViewport (\fBconst\fP \fBsViewport\fP & viewport)\fR [static]\fP"

.SS "\fBvoid\fP xpe::render::cCameraManager::Unbind ()\fR [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
