.TH "xpe::math::cMathManager" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xpe::math::cMathManager
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <math_manager\&.hpp>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "\fBstatic\fP \fBsRay\fP \fBToLocalSpace\fP (\fBconst\fP \fBsRay\fP &\fBray\fP, \fBconst\fP glm::mat4 &\fBmodelMatrix\fP)"
.br
.ti -1c
.RI "\fBstatic\fP \fBsRay\fP \fBToWorldSpace\fP (\fBconst\fP \fBsRay\fP &\fBray\fP, \fBconst\fP glm::mat4 &\fBmodelMatrix\fP)"
.br
.ti -1c
.RI "\fBstatic\fP \fBsRay\fP \fBToWorldSpaceInverse\fP (\fBconst\fP \fBsRay\fP &\fBray\fP, \fBconst\fP glm::mat4 &\fBviewMatrix\fP)"
.br
.ti -1c
.RI "\fBstatic\fP \fBsRay\fP \fBToViewSpace\fP (\fBconst\fP \fBsRay\fP &\fBray\fP, \fBconst\fP glm::mat4 &\fBviewMatrix\fP)"
.br
.ti -1c
.RI "\fBstatic\fP \fBsRay\fP \fBToViewSpaceInverse\fP (\fBconst\fP \fBsRay\fP &\fBray\fP, \fBconst\fP \fBfloat\fP \fBfov\fP, \fBconst\fP \fBfloat\fP \fBaspectRatio\fP)"
.br
.ti -1c
.RI "\fBstatic\fP \fBsRay\fP \fBToViewSpaceInverse\fP (\fBconst\fP \fBsRay\fP &\fBray\fP, \fBconst\fP glm::mat4 &\fBperspectiveMatrix\fP)"
.br
.ti -1c
.RI "\fBstatic\fP \fBsRay\fP \fBToClipSpace\fP (\fBconst\fP \fBsRay\fP &\fBray\fP, \fBconst\fP \fBfloat\fP \fBfov\fP, \fBconst\fP \fBfloat\fP \fBaspectRatio\fP)"
.br
.ti -1c
.RI "\fBstatic\fP \fBsRay\fP \fBToClipSpace\fP (\fBconst\fP \fBsRay\fP &\fBray\fP, \fBconst\fP glm::mat4 &\fBperspectiveMatrix\fP)"
.br
.ti -1c
.RI "\fBstatic\fP \fBsRay\fP \fBToClipSpaceInverse\fP (\fBconst\fP \fBsRay\fP &\fBray\fP)"
.br
.ti -1c
.RI "\fBstatic\fP \fBsRay\fP \fBToNDCSpace\fP (\fBconst\fP \fBsRay\fP &\fBray\fP)"
.br
.ti -1c
.RI "\fBstatic\fP \fBsRay\fP \fBToNDCSpaceInverse\fP (\fBconst\fP \fBsRay\fP &\fBray\fP, \fBint\fP \fBwidth\fP, \fBint\fP \fBheight\fP)"
.br
.ti -1c
.RI "\fBstatic\fP \fBsRay\fP \fBToScreenSpace\fP (\fBconst\fP \fBsRay\fP &\fBray\fP, \fBint\fP \fBwidth\fP, \fBint\fP \fBheight\fP)"
.br
.ti -1c
.RI "\fBstatic\fP glm::mat4 \fBUpdateModelMatrix\fP (\fBconst\fP \fBsModelMatrix\fP &\fBmodelMatrix\fP)"
.br
.ti -1c
.RI "\fBstatic\fP glm::mat4 \fBUpdateNormalMatrix\fP (\fBconst\fP glm::mat4 &\fBmodelMatrix\fP)"
.br
.ti -1c
.RI "\fBstatic\fP glm::mat4 \fBUpdateViewMatrix\fP (\fBconst\fP \fBsViewMatrix\fP &\fBviewMatrix\fP)"
.br
.ti -1c
.RI "\fBstatic\fP glm::mat4 \fBUpdateOrthoMatrix\fP (\fBconst\fP sOrthoMatrix &\fBorthoMatrix\fP)"
.br
.ti -1c
.RI "\fBstatic\fP glm::mat4 \fBUpdatePerspectiveMatrix\fP (\fBconst\fP sPerspectiveMatrix &\fBperspectiveMatrix\fP)"
.br
.ti -1c
.RI "\fBstatic\fP glm::mat4 \fBUpdateLightMatrix\fP (\fBconst\fP sOrthoMatrix &\fBorthoMatrix\fP, \fBconst\fP \fBsViewMatrix\fP &\fBviewMatrix\fP)"
.br
.ti -1c
.RI "\fBstatic\fP glm::mat4 \fBUpdateLightMatrix\fP (\fBconst\fP sPerspectiveMatrix &\fBperspectiveMatrix\fP, \fBconst\fP \fBsViewMatrix\fP &\fBviewMatrix\fP)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "\fBsRay\fP xpe::math::cMathManager::ToClipSpace (\fBconst\fP \fBsRay\fP & ray, \fBconst\fP \fBfloat\fP fov, \fBconst\fP \fBfloat\fP aspectRatio)\fR [static]\fP"

.SS "\fBsRay\fP xpe::math::cMathManager::ToClipSpace (\fBconst\fP \fBsRay\fP & ray, \fBconst\fP glm::mat4 & perspectiveMatrix)\fR [static]\fP"

.SS "\fBsRay\fP xpe::math::cMathManager::ToClipSpaceInverse (\fBconst\fP \fBsRay\fP & ray)\fR [static]\fP"

.SS "\fBsRay\fP xpe::math::cMathManager::ToLocalSpace (\fBconst\fP \fBsRay\fP & ray, \fBconst\fP glm::mat4 & modelMatrix)\fR [static]\fP"

.SS "\fBsRay\fP xpe::math::cMathManager::ToNDCSpace (\fBconst\fP \fBsRay\fP & ray)\fR [static]\fP"

.SS "\fBsRay\fP xpe::math::cMathManager::ToNDCSpaceInverse (\fBconst\fP \fBsRay\fP & ray, \fBint\fP width, \fBint\fP height)\fR [static]\fP"

.SS "\fBsRay\fP xpe::math::cMathManager::ToScreenSpace (\fBconst\fP \fBsRay\fP & ray, \fBint\fP width, \fBint\fP height)\fR [static]\fP"

.SS "\fBsRay\fP xpe::math::cMathManager::ToViewSpace (\fBconst\fP \fBsRay\fP & ray, \fBconst\fP glm::mat4 & viewMatrix)\fR [static]\fP"

.SS "\fBsRay\fP xpe::math::cMathManager::ToViewSpaceInverse (\fBconst\fP \fBsRay\fP & ray, \fBconst\fP \fBfloat\fP fov, \fBconst\fP \fBfloat\fP aspectRatio)\fR [static]\fP"

.SS "\fBsRay\fP xpe::math::cMathManager::ToViewSpaceInverse (\fBconst\fP \fBsRay\fP & ray, \fBconst\fP glm::mat4 & perspectiveMatrix)\fR [static]\fP"

.SS "\fBsRay\fP xpe::math::cMathManager::ToWorldSpace (\fBconst\fP \fBsRay\fP & ray, \fBconst\fP glm::mat4 & modelMatrix)\fR [static]\fP"

.SS "\fBsRay\fP xpe::math::cMathManager::ToWorldSpaceInverse (\fBconst\fP \fBsRay\fP & ray, \fBconst\fP glm::mat4 & viewMatrix)\fR [static]\fP"

.SS "glm::mat4 xpe::math::cMathManager::UpdateLightMatrix (\fBconst\fP sOrthoMatrix & orthoMatrix, \fBconst\fP \fBsViewMatrix\fP & viewMatrix)\fR [static]\fP"

.SS "glm::mat4 xpe::math::cMathManager::UpdateLightMatrix (\fBconst\fP sPerspectiveMatrix & perspectiveMatrix, \fBconst\fP \fBsViewMatrix\fP & viewMatrix)\fR [static]\fP"

.SS "glm::mat4 xpe::math::cMathManager::UpdateModelMatrix (\fBconst\fP \fBsModelMatrix\fP & modelMatrix)\fR [static]\fP"

.SS "glm::mat4 xpe::math::cMathManager::UpdateNormalMatrix (\fBconst\fP glm::mat4 & modelMatrix)\fR [static]\fP"

.SS "glm::mat4 xpe::math::cMathManager::UpdateOrthoMatrix (\fBconst\fP sOrthoMatrix & orthoMatrix)\fR [static]\fP"

.SS "glm::mat4 xpe::math::cMathManager::UpdatePerspectiveMatrix (\fBconst\fP sPerspectiveMatrix & perspectiveMatrix)\fR [static]\fP"

.SS "glm::mat4 xpe::math::cMathManager::UpdateViewMatrix (\fBconst\fP \fBsViewMatrix\fP & viewMatrix)\fR [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
