.TH "xpe::render::sVertexFormat" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xpe::render::sVertexFormat
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <core\&.hpp>\fP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBsAttribute\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsVertexFormat\fP ()=\fBdefault\fP"
.br
.ti -1c
.RI "\fBsVertexFormat\fP (\fBconst\fP std::vector< \fBsAttribute\fP > &\fBattributes\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::vector< \fBsAttribute\fP > \fBAttributes\fP"
.br
.ti -1c
.RI "\fBusize\fP \fBStride\fP = 0"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "xpe::render::sVertexFormat::sVertexFormat ()\fR [default]\fP"

.SS "xpe::render::sVertexFormat::sVertexFormat (\fBconst\fP std::vector< \fBsAttribute\fP > & attributes)"

.SH "Member Data Documentation"
.PP 
.SS "std::vector<\fBsAttribute\fP> xpe::render::sVertexFormat::Attributes"

.SS "\fBusize\fP xpe::render::sVertexFormat::Stride = 0"


.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
