.TH "xpe::ecs::CPhysicsActor" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xpe::ecs::CPhysicsActor
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <components\&.hpp>\fP
.PP
Inherits \fBxpe::physics::sActor\fP, and \fBxpe::res::cJson\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCPhysicsActor\fP (\fBphysics::sActor\fP *\fBactor\fP)"
.br
.in -1c

Public Member Functions inherited from \fBxpe::physics::sActor\fP
.in +1c
.ti -1c
.RI "\fBJSON_ENUM\fP (\fBeActorType\fP, { { \fBeActorType::NONE\fP, 'NONE' }, { \fBeActorType::RIGID_STATIC\fP, 'RIGID_STATIC' }, { \fBeActorType::RIGID_DYNAMIC\fP, 'RIGID_DYNAMIC' }, }) \fBsActor\fP()=\fBdefault\fP"
.br
.ti -1c
.RI "\fBsActor\fP (\fBPxActor\fP *\fBactor\fP, \fBPxMaterial\fP *\fBmaterial\fP, \fBPxShape\fP *\fBshape\fP, \fBconst\fP \fBeActorType\fP &\fBactorType\fP, sShapeDescriptor *\fBshapeDesc\fP, \fBconst\fP glm::vec3 &\fBlinearVelocity\fP, \fBf32\fP \fBstaticFriction\fP, \fBf32\fP \fBdynamicFriction\fP, \fBf32\fP \fBrestitution\fP, \fBf32\fP \fBcontactOffset\fP, \fBf32\fP \fBrestOffset\fP)"
.br
.in -1c

Public Member Functions inherited from \fBxpe::res::cJson\fP
.in +1c
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBToJson\fP (\fBjson\fP &\fBroot\fP)=0"
.br
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBFromJson\fP (\fBjson\fP &\fBroot\fP)=0"
.br
.in -1c
.SS "Additional Inherited Members"


Public Types inherited from \fBxpe::physics::sActor\fP
.in +1c
.ti -1c
.RI "enum class \fBeActorType\fP { \fBNONE\fP = 0, \fBRIGID_STATIC\fP = 1, \fBRIGID_DYNAMIC\fP = 2 }"
.br
.in -1c

Public Attributes inherited from \fBxpe::physics::sActor\fP
.in +1c
.ti -1c
.RI "\fBPxActor\fP * \fBActor\fP = \fBnullptr\fP"
.br
.ti -1c
.RI "\fBPxMaterial\fP * \fBMaterial\fP = \fBnullptr\fP"
.br
.ti -1c
.RI "\fBPxShape\fP * \fBShape\fP = \fBnullptr\fP"
.br
.ti -1c
.RI "\fBeActorType\fP \fBActorType\fP = \fBeActorType::NONE\fP"
.br
.ti -1c
.RI "sShapeDescriptor \fBShapeDesc\fP = sShapeDescriptor(\fBeShapeType::NONE\fP)"
.br
.ti -1c
.RI "glm::vec3 \fBLinearVelocity\fP = glm::vec3(0\&.0f)"
.br
.ti -1c
.RI "\fBf32\fP \fBStaticFriction\fP = 0\&.0f"
.br
.ti -1c
.RI "\fBf32\fP \fBDynamicFriction\fP = 0\&.0f"
.br
.ti -1c
.RI "\fBf32\fP \fBRestitution\fP = 0\&.0f"
.br
.ti -1c
.RI "\fBf32\fP \fBContactOffset\fP = 0\&.0f"
.br
.ti -1c
.RI "\fBf32\fP \fBRestOffset\fP = 0\&.0f"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "xpe::ecs::CPhysicsActor::CPhysicsActor (\fBphysics::sActor\fP * actor)\fR [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
