.TH "xpe::physics::sRagdoll" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xpe::physics::sRagdoll
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <physics_manager\&.hpp>\fP
.PP
Inherits \fBxpe::core::cObject\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBeBodypart\fP { \fBNONE\fP = 0, \fBHEAD\fP = 1, \fBTORSO_TOP\fP = 2, \fBTORSO_MIDDLE\fP = 3, \fBTORSO_BOTTOM\fP = 4, \fBLEFT_ARM_TOP\fP = 5, \fBLEFT_ARM_BOTTOM\fP = 6, \fBRIGHT_ARM_TOP\fP = 7, \fBRIGHT_ARM_BOTTOM\fP = 8, \fBLEFT_LEG_TOP\fP = 9, \fBLEFT_LEG_BOTTOM\fP = 10, \fBRIGHT_LEG_TOP\fP = 11, \fBRIGHT_LEG_BOTTOM\fP = 12 }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsRagdoll\fP (\fBconst\fP \fBvector\fP< \fBsActor\fP * > &\fBbodyparts\fP)"
.br
.ti -1c
.RI "\fB~sRagdoll\fP ()=\fBdefault\fP"
.br
.in -1c

Public Member Functions inherited from \fBxpe::core::cObject\fP
.in +1c
.ti -1c
.RI "\fBvoid\fP * \fBoperator new\fP (\fBusize\fP \fBbyteSize\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBoperator delete\fP (\fBvoid\fP *\fBaddress\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBvector\fP< \fBsActor\fP * > \fBBodyparts\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "\fBstatic\fP \fBconst\fP \fBusize\fP \fBk_BodypartCount\fP = 12"
.br
.in -1c
.SH "Member Enumeration Documentation"
.PP 
.SS "\fBenum\fP \fBxpe::physics::sRagdoll::eBodypart\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fINONE \fP\fP
.TP
\fB\fIHEAD \fP\fP
.TP
\fB\fITORSO_TOP \fP\fP
.TP
\fB\fITORSO_MIDDLE \fP\fP
.TP
\fB\fITORSO_BOTTOM \fP\fP
.TP
\fB\fILEFT_ARM_TOP \fP\fP
.TP
\fB\fILEFT_ARM_BOTTOM \fP\fP
.TP
\fB\fIRIGHT_ARM_TOP \fP\fP
.TP
\fB\fIRIGHT_ARM_BOTTOM \fP\fP
.TP
\fB\fILEFT_LEG_TOP \fP\fP
.TP
\fB\fILEFT_LEG_BOTTOM \fP\fP
.TP
\fB\fIRIGHT_LEG_TOP \fP\fP
.TP
\fB\fIRIGHT_LEG_BOTTOM \fP\fP
.SH "Constructor & Destructor Documentation"
.PP 
.SS "xpe::physics::sRagdoll::sRagdoll (\fBconst\fP \fBvector\fP< \fBsActor\fP * > & bodyparts)\fR [inline]\fP"

.SS "xpe::physics::sRagdoll::~sRagdoll ()\fR [default]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBvector\fP<\fBsActor\fP*> xpe::physics::sRagdoll::Bodyparts"

.SS "\fBconst\fP \fBusize\fP xpe::physics::sRagdoll::k_BodypartCount = 12\fR [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
