.TH "xpe::core::cHotObject" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xpe::core::cHotObject
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <types\&.hpp>\fP
.PP
Inherited by \fBxpe::core::cHotScope< T >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBvoid\fP * \fBoperator new\fP (\fBusize\fP \fBbyteSize\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBoperator delete\fP (\fBvoid\fP *\fBaddress\fP)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "\fBvoid\fP xpe::core::cHotObject::operator \fBdelete\fP (\fBvoid\fP * address)"

.SS "\fBvoid\fP * xpe::core::cHotObject::operator \fBnew\fP (\fBusize\fP byteSize)"


.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
