.TH "xpe::render::sSphere" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xpe::render::sSphere
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <geometries\&.hpp>\fP
.PP
Inherits \fBxpe::render::sGeometry\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsSphere\fP (\fBs32\fP \fBxSegments\fP=64, \fBs32\fP \fBySegments\fP=64)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "glm::vec3 \fBCenter\fP"
.br
.ti -1c
.RI "\fBfloat\fP \fBRadius\fP"
.br
.in -1c

Public Attributes inherited from \fBxpe::render::sGeometry\fP
.in +1c
.ti -1c
.RI "\fBePrimitiveTopology\fP \fBPrimitiveTopology\fP = \fBePrimitiveTopology::DEFAULT\fP"
.br
.ti -1c
.RI "\fBvector\fP< \fBsVertex\fP > \fBVertices\fP"
.br
.ti -1c
.RI "\fBvector\fP< \fBu32\fP > \fBIndices\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "xpe::render::sSphere::sSphere (\fBs32\fP xSegments = \fR64\fP, \fBs32\fP ySegments = \fR64\fP)"

.SH "Member Data Documentation"
.PP 
.SS "glm::vec3 xpe::render::sSphere::Center"

.SS "\fBfloat\fP xpe::render::sSphere::Radius"


.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
