.TH "xpe::render::sGeometryInfo" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xpe::render::sGeometryInfo
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <geometry\&.hpp>\fP
.PP
Inherited by \fBxpe::ecs::CGeometryInfo\fP\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBePrimitiveTopology\fP \fBPrimitiveTopology\fP = \fBePrimitiveTopology::DEFAULT\fP"
.br
.ti -1c
.RI "\fBusize\fP \fBVertexOffset\fP = 0"
.br
.ti -1c
.RI "\fBusize\fP \fBIndexOffset\fP = 0"
.br
.ti -1c
.RI "\fBusize\fP \fBVertexCount\fP = 0"
.br
.ti -1c
.RI "\fBusize\fP \fBIndexCount\fP = 0"
.br
.ti -1c
.RI "\fBvector\fP< \fBEntityID\fP > \fBEntities\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBvector\fP<\fBEntityID\fP> xpe::render::sGeometryInfo::Entities"

.SS "\fBusize\fP xpe::render::sGeometryInfo::IndexCount = 0"

.SS "\fBusize\fP xpe::render::sGeometryInfo::IndexOffset = 0"

.SS "\fBePrimitiveTopology\fP xpe::render::sGeometryInfo::PrimitiveTopology = \fBePrimitiveTopology::DEFAULT\fP"

.SS "\fBusize\fP xpe::render::sGeometryInfo::VertexCount = 0"

.SS "\fBusize\fP xpe::render::sGeometryInfo::VertexOffset = 0"


.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
