.TH "xpe::render::sSkeletonData" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xpe::render::sSkeletonData
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <buffers\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "glm::mat4 \fBTransform\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "glm::mat4 xpe::render::sSkeletonData::Transform"


.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
