.TH "xpe::render::cSkyboxManager" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xpe::render::cSkyboxManager
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <skybox_manager\&.hpp>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "\fBstatic\fP \fBvoid\fP \fBInit\fP ()"
.br
.ti -1c
.RI "\fBstatic\fP \fBvoid\fP \fBFree\fP ()"
.br
.ti -1c
.RI "\fBstatic\fP \fBcSkyboxManager\fP & \fBGet\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBsSkybox\fP \fBSkybox\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "\fBvoid\fP xpe::render::cSkyboxManager::Free ()\fR [static]\fP"

.SS "\fBcSkyboxManager\fP & xpe::render::cSkyboxManager::Get ()\fR [static]\fP"

.SS "\fBvoid\fP xpe::render::cSkyboxManager::Init ()\fR [static]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBsSkybox\fP xpe::render::cSkyboxManager::Skybox"


.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
