.TH "xpe::core::cWindowManager" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xpe::core::cWindowManager
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <window_manager\&.hpp>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "\fBstatic\fP \fBvoid\fP \fBInit\fP ()"
.br
.ti -1c
.RI "\fBstatic\fP \fBvoid\fP \fBFree\fP ()"
.br
.ti -1c
.RI "\fBstatic\fP \fBvoid\fP \fBInitWindow\fP (\fBconst\fP \fBsWindowDescriptor\fP &\fBwindowDescriptor\fP)"
.br
.ti -1c
.RI "\fBstatic\fP \fBvoid\fP \fBFreeWindow\fP ()"
.br
.ti -1c
.RI "\fBstatic\fP \fBconst\fP \fBsWindowDescriptor\fP & \fBGetDescriptor\fP ()"
.br
.ti -1c
.RI "\fBstatic\fP \fBbool\fP \fBShouldClose\fP ()"
.br
.ti -1c
.RI "\fBstatic\fP \fBvoid\fP \fBClose\fP ()"
.br
.ti -1c
.RI "\fBstatic\fP \fBvoid\fP \fBPollEvents\fP ()"
.br
.ti -1c
.RI "\fBstatic\fP \fBvoid\fP \fBSwap\fP ()"
.br
.ti -1c
.RI "\fBstatic\fP \fBbool\fP \fBIsWindowed\fP ()"
.br
.ti -1c
.RI "\fBstatic\fP \fBbool\fP \fBIsFullscreen\fP ()"
.br
.ti -1c
.RI "\fBstatic\fP \fBint\fP \fBGetWidth\fP ()"
.br
.ti -1c
.RI "\fBstatic\fP \fBint\fP \fBGetHeight\fP ()"
.br
.ti -1c
.RI "\fBstatic\fP \fBint\fP \fBGetFrameWidth\fP ()"
.br
.ti -1c
.RI "\fBstatic\fP \fBint\fP \fBGetFrameHeight\fP ()"
.br
.ti -1c
.RI "\fBstatic\fP \fBint\fP \fBGetPosX\fP ()"
.br
.ti -1c
.RI "\fBstatic\fP \fBint\fP \fBGetPosY\fP ()"
.br
.ti -1c
.RI "\fBstatic\fP \fBconst\fP \fBchar\fP * \fBGetTitle\fP ()"
.br
.ti -1c
.RI "\fBstatic\fP \fBvoid\fP * \fBGetInstance\fP ()"
.br
.ti -1c
.RI "\fBstatic\fP \fBvoid\fP * \fBGetWin32Instance\fP ()"
.br
.ti -1c
.RI "\fBstatic\fP \fBint\fP \fBGetRefreshRate\fP ()"
.br
.ti -1c
.RI "\fBstatic\fP \fBint\fP \fBGetMonitorWidth\fP ()"
.br
.ti -1c
.RI "\fBstatic\fP \fBint\fP \fBGetMonitorHeight\fP ()"
.br
.ti -1c
.RI "\fBstatic\fP \fBvoid\fP \fBSetPos\fP (\fBint\fP \fBx\fP, \fBint\fP \fBy\fP)"
.br
.ti -1c
.RI "\fBstatic\fP \fBvoid\fP \fBSetSize\fP (\fBint\fP \fBw\fP, \fBint\fP \fBh\fP)"
.br
.ti -1c
.RI "\fBstatic\fP \fBvoid\fP \fBSetUserPointer\fP (\fBvoid\fP *\fBuserPtr\fP)"
.br
.ti -1c
.RI "\fBstatic\fP \fBvoid\fP * \fBGetUserPointer\fP ()"
.br
.ti -1c
.RI "\fBstatic\fP \fBvoid\fP \fBSetVSync\fP (\fBbool\fP \fBvsync\fP)"
.br
.ti -1c
.RI "\fBstatic\fP \fBvoid\fP \fBSetFullscreen\fP ()"
.br
.ti -1c
.RI "\fBstatic\fP \fBvoid\fP \fBSetWindowed\fP ()"
.br
.ti -1c
.RI "\fBstatic\fP \fBvoid\fP \fBSetFullscreenWindowed\fP ()"
.br
.ti -1c
.RI "\fBstatic\fP \fBvoid\fP \fBToggleWindowMode\fP ()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "\fBvoid\fP xpe::core::cWindowManager::Close ()\fR [static]\fP"

.SS "\fBvoid\fP xpe::core::cWindowManager::Free ()\fR [static]\fP"

.SS "\fBvoid\fP xpe::core::cWindowManager::FreeWindow ()\fR [static]\fP"

.SS "\fBconst\fP \fBsWindowDescriptor\fP & xpe::core::cWindowManager::GetDescriptor ()\fR [static]\fP"

.SS "\fBint\fP xpe::core::cWindowManager::GetFrameHeight ()\fR [static]\fP"

.SS "\fBint\fP xpe::core::cWindowManager::GetFrameWidth ()\fR [static]\fP"

.SS "\fBint\fP xpe::core::cWindowManager::GetHeight ()\fR [static]\fP"

.SS "\fBvoid\fP * xpe::core::cWindowManager::GetInstance ()\fR [static]\fP"

.SS "\fBint\fP xpe::core::cWindowManager::GetMonitorHeight ()\fR [static]\fP"

.SS "\fBint\fP xpe::core::cWindowManager::GetMonitorWidth ()\fR [static]\fP"

.SS "\fBint\fP xpe::core::cWindowManager::GetPosX ()\fR [static]\fP"

.SS "\fBint\fP xpe::core::cWindowManager::GetPosY ()\fR [static]\fP"

.SS "\fBint\fP xpe::core::cWindowManager::GetRefreshRate ()\fR [static]\fP"

.SS "\fBconst\fP \fBchar\fP * xpe::core::cWindowManager::GetTitle ()\fR [static]\fP"

.SS "\fBvoid\fP * xpe::core::cWindowManager::GetUserPointer ()\fR [static]\fP"

.SS "\fBint\fP xpe::core::cWindowManager::GetWidth ()\fR [static]\fP"

.SS "\fBvoid\fP * xpe::core::cWindowManager::GetWin32Instance ()\fR [static]\fP"

.SS "\fBvoid\fP xpe::core::cWindowManager::Init ()\fR [static]\fP"

.SS "\fBvoid\fP xpe::core::cWindowManager::InitWindow (\fBconst\fP \fBsWindowDescriptor\fP & windowDescriptor)\fR [static]\fP"

.SS "\fBbool\fP xpe::core::cWindowManager::IsFullscreen ()\fR [static]\fP"

.SS "\fBbool\fP xpe::core::cWindowManager::IsWindowed ()\fR [static]\fP"

.SS "\fBvoid\fP xpe::core::cWindowManager::PollEvents ()\fR [static]\fP"

.SS "\fBvoid\fP xpe::core::cWindowManager::SetFullscreen ()\fR [static]\fP"

.SS "\fBvoid\fP xpe::core::cWindowManager::SetFullscreenWindowed ()\fR [static]\fP"

.SS "\fBvoid\fP xpe::core::cWindowManager::SetPos (\fBint\fP x, \fBint\fP y)\fR [static]\fP"

.SS "\fBvoid\fP xpe::core::cWindowManager::SetSize (\fBint\fP w, \fBint\fP h)\fR [static]\fP"

.SS "\fBvoid\fP xpe::core::cWindowManager::SetUserPointer (\fBvoid\fP * userPtr)\fR [static]\fP"

.SS "\fBvoid\fP xpe::core::cWindowManager::SetVSync (\fBbool\fP vsync)\fR [static]\fP"

.SS "\fBvoid\fP xpe::core::cWindowManager::SetWindowed ()\fR [static]\fP"

.SS "\fBbool\fP xpe::core::cWindowManager::ShouldClose ()\fR [static]\fP"

.SS "\fBvoid\fP xpe::core::cWindowManager::Swap ()\fR [static]\fP"

.SS "\fBvoid\fP xpe::core::cWindowManager::ToggleWindowMode ()\fR [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
