.TH "xpe::core::cTimeManager" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xpe::core::cTimeManager
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <time_manager\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBcTimeManager\fP (\fBcTime\fP *\fBoutput\fP)"
.br
.ti -1c
.RI "\fB~cTimeManager\fP ()"
.br
.ti -1c
.RI "\fBcTime\fP \fBGetStartTime\fP ()"
.br
.ti -1c
.RI "\fBcTime\fP \fBGetEndTime\fP ()"
.br
.ti -1c
.RI "\fBcTime\fP \fBGetDeltaTime\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "\fBstatic\fP \fBcTime\fP \fBNow\fP ()"
.br
.ti -1c
.RI "\fBstatic\fP \fBcTime\fP \fBCast\fP (\fBconst\fP system_clock::time_point &\fBtime\fP)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "xpe::core::cTimeManager::cTimeManager (\fBcTime\fP * output)\fR [inline]\fP"

.SS "xpe::core::cTimeManager::~cTimeManager ()\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBcTime\fP xpe::core::cTimeManager::Cast (\fBconst\fP system_clock::time_point & time)\fR [static]\fP"

.SS "\fBcTime\fP xpe::core::cTimeManager::GetDeltaTime ()\fR [inline]\fP"

.SS "\fBcTime\fP xpe::core::cTimeManager::GetEndTime ()\fR [inline]\fP"

.SS "\fBcTime\fP xpe::core::cTimeManager::GetStartTime ()\fR [inline]\fP"

.SS "\fBcTime\fP xpe::core::cTimeManager::Now ()\fR [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
