.TH "xpe::ecs::cEntity" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xpe::ecs::cEntity
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <ecs\&.hpp>\fP
.PP
Inherits \fBxpe::res::cJson\fP, and \fBxpe::res::cXml\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBcEntity\fP ()=\fBdefault\fP"
.br
.ti -1c
.RI "\fBcEntity\fP (\fBconst\fP \fBstring\fP &\fBtag\fP, \fBcScene\fP *\fBscene\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBSetScene\fP (\fBcScene\fP *\fBscene\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBSetTag\fP (\fBconst\fP \fBstring\fP &\fBtag\fP)"
.br
.ti -1c
.RI "template<typename\&.\&.\&. Args> \fBvoid\fP \fBSetTransform\fP (\fBArgs\fP &&\&.\&.\&. \fBargs\fP)"
.br
.ti -1c
.RI "template<typename\&.\&.\&. Args> \fBvoid\fP \fBSetPosition\fP (\fBArgs\fP &&\&.\&.\&. \fBargs\fP)"
.br
.ti -1c
.RI "template<typename\&.\&.\&. Args> \fBvoid\fP \fBSetRotation\fP (\fBArgs\fP &&\&.\&.\&. \fBargs\fP)"
.br
.ti -1c
.RI "template<typename\&.\&.\&. Args> \fBvoid\fP \fBSetScale\fP (\fBArgs\fP &&\&.\&.\&. \fBargs\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBSetSpace2D\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBSetSpace3D\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBSetVisible\fP (\fBbool\fP \fBvisible\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBSetTransparent\fP (\fBbool\fP \fBtransparent\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBSetOpaque\fP (\fBbool\fP \fBopaque\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBSetShadow\fP (\fBbool\fP \fBshadow\fP)"
.br
.ti -1c
.RI "template<typename\&.\&.\&. Args> \fBvoid\fP \fBMove\fP (\fBArgs\fP &&\&.\&.\&. \fBargs\fP)"
.br
.ti -1c
.RI "template<typename\&.\&.\&. Args> \fBvoid\fP \fBRotate\fP (\fBArgs\fP &&\&.\&.\&. \fBargs\fP)"
.br
.ti -1c
.RI "template<typename\&.\&.\&. Args> \fBvoid\fP \fBScale\fP (\fBArgs\fP &&\&.\&.\&. \fBargs\fP)"
.br
.ti -1c
.RI "\fBconst\fP \fBEntityID\fP \fBGetID\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBconst\fP \fBcScene\fP * \fBGetScene\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBconst\fP \fBstring\fP & \fBGetTag\fP ()"
.br
.ti -1c
.RI "\fBsTransform\fP & \fBGetTransform\fP ()"
.br
.ti -1c
.RI "glm::vec3 & \fBGetPosition\fP ()"
.br
.ti -1c
.RI "glm::vec3 & \fBGetRotation\fP ()"
.br
.ti -1c
.RI "glm::vec3 & \fBGetScale\fP ()"
.br
.ti -1c
.RI "\fBbool\fP \fBIsVisible\fP ()"
.br
.ti -1c
.RI "\fBbool\fP \fBIsTransparent\fP ()"
.br
.ti -1c
.RI "\fBbool\fP \fBIsOpaque\fP ()"
.br
.ti -1c
.RI "\fBbool\fP \fBHasShadow\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBUpdateXmlChildren\fP ()"
.br
.ti -1c
.RI "template<\fBtypename\fP \fBT\fP , typename\&.\&.\&. Args> \fBT\fP & \fBAdd\fP (\fBArgs\fP &&\&.\&.\&. \fBargs\fP)"
.br
.ti -1c
.RI "template<\fBtypename\fP \fBT\fP > \fBT\fP & \fBGet\fP ()"
.br
.ti -1c
.RI "template<\fBtypename\fP \fBT\fP > \fBvoid\fP \fBRemove\fP ()"
.br
.ti -1c
.RI "template<typename\&.\&.\&. T> \fBbool\fP \fBHasAny\fP ()"
.br
.ti -1c
.RI "template<typename\&.\&.\&. T> \fBbool\fP \fBHasAll\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBToJson\fP (\fBjson\fP &\fBroot\fP) \fBoverride\fP"
.br
.ti -1c
.RI "\fBvoid\fP \fBFromJson\fP (\fBjson\fP &\fBroot\fP) \fBoverride\fP"
.br
.ti -1c
.RI "\fBxml\fP \fBToXml\fP (\fBxml\fP &\fBroot\fP) \fBoverride\fP"
.br
.ti -1c
.RI "\fBxml\fP \fBFromXml\fP (\fBxml\fP &\fBroot\fP) \fBoverride\fP"
.br
.in -1c

Public Member Functions inherited from \fBxpe::res::cXml\fP
.in +1c
.ti -1c
.RI "\fBbool\fP \fBLoadFile\fP (\fBconst\fP \fBchar\fP *\fBfilepath\fP)"
.br
.ti -1c
.RI "\fBbool\fP \fBSaveFile\fP (\fBconst\fP \fBchar\fP *\fBfilepath\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBvector\fP< \fBcEntity\fP * > \fBChildren\fP"
.br
.in -1c

Public Attributes inherited from \fBxpe::res::cXml\fP
.in +1c
.ti -1c
.RI "\fBxpe::core::vector\fP< \fBcXml\fP * > \fBXmlChildren\fP"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBEntityID\fP \fBm_ID\fP = \fBEntityNull\fP"
.br
.ti -1c
.RI "\fBcScene\fP * \fBm_Scene\fP = \fBnullptr\fP"
.br
.in -1c

Protected Attributes inherited from \fBxpe::res::cXml\fP
.in +1c
.ti -1c
.RI "pugi::xml_document \fBm_Doc\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "xpe::ecs::cEntity::cEntity ()\fR [default]\fP"

.SS "xpe::ecs::cEntity::cEntity (\fBconst\fP \fBstring\fP & tag, \fBcScene\fP * scene)"

.SH "Member Function Documentation"
.PP 
.SS "template<\fBtypename\fP \fBT\fP , typename\&.\&.\&. Args> \fBT\fP & xpe::ecs::cEntity::Add (\fBArgs\fP &&\&.\&.\&. args)"

.SS "\fBvoid\fP xpe::ecs::cEntity::FromJson (\fBjson\fP & root)\fR [override]\fP, \fR [virtual]\fP"

.PP
Implements \fBxpe::res::cJson\fP\&.
.SS "\fBxml\fP xpe::ecs::cEntity::FromXml (\fBxml\fP & root)\fR [override]\fP, \fR [virtual]\fP"

.PP
Implements \fBxpe::res::cXml\fP\&.
.SS "template<\fBtypename\fP \fBT\fP > \fBT\fP & xpe::ecs::cEntity::Get ()"

.SS "\fBconst\fP \fBEntityID\fP xpe::ecs::cEntity::GetID () const\fR [inline]\fP"

.SS "glm::vec3 & xpe::ecs::cEntity::GetPosition ()"

.SS "glm::vec3 & xpe::ecs::cEntity::GetRotation ()"

.SS "glm::vec3 & xpe::ecs::cEntity::GetScale ()"

.SS "\fBconst\fP \fBcScene\fP * xpe::ecs::cEntity::GetScene () const\fR [inline]\fP"

.SS "\fBconst\fP \fBstring\fP & xpe::ecs::cEntity::GetTag ()"

.SS "\fBsTransform\fP & xpe::ecs::cEntity::GetTransform ()"

.SS "template<typename\&.\&.\&. T> \fBbool\fP xpe::ecs::cEntity::HasAll ()"

.SS "template<typename\&.\&.\&. T> \fBbool\fP xpe::ecs::cEntity::HasAny ()"

.SS "\fBbool\fP xpe::ecs::cEntity::HasShadow ()"

.SS "\fBbool\fP xpe::ecs::cEntity::IsOpaque ()"

.SS "\fBbool\fP xpe::ecs::cEntity::IsTransparent ()"

.SS "\fBbool\fP xpe::ecs::cEntity::IsVisible ()"

.SS "template<typename\&.\&.\&. Args> \fBvoid\fP xpe::ecs::cEntity::Move (\fBArgs\fP &&\&.\&.\&. args)"

.SS "template<\fBtypename\fP \fBT\fP > \fBvoid\fP xpe::ecs::cEntity::Remove ()"

.SS "template<typename\&.\&.\&. Args> \fBvoid\fP xpe::ecs::cEntity::Rotate (\fBArgs\fP &&\&.\&.\&. args)"

.SS "template<typename\&.\&.\&. Args> \fBvoid\fP xpe::ecs::cEntity::Scale (\fBArgs\fP &&\&.\&.\&. args)"

.SS "\fBvoid\fP xpe::ecs::cEntity::SetOpaque (\fBbool\fP opaque)"

.SS "template<typename\&.\&.\&. Args> \fBvoid\fP xpe::ecs::cEntity::SetPosition (\fBArgs\fP &&\&.\&.\&. args)"

.SS "template<typename\&.\&.\&. Args> \fBvoid\fP xpe::ecs::cEntity::SetRotation (\fBArgs\fP &&\&.\&.\&. args)"

.SS "template<typename\&.\&.\&. Args> \fBvoid\fP xpe::ecs::cEntity::SetScale (\fBArgs\fP &&\&.\&.\&. args)"

.SS "\fBvoid\fP xpe::ecs::cEntity::SetScene (\fBcScene\fP * scene)\fR [inline]\fP"

.SS "\fBvoid\fP xpe::ecs::cEntity::SetShadow (\fBbool\fP shadow)"

.SS "\fBvoid\fP xpe::ecs::cEntity::SetSpace2D ()"

.SS "\fBvoid\fP xpe::ecs::cEntity::SetSpace3D ()"

.SS "\fBvoid\fP xpe::ecs::cEntity::SetTag (\fBconst\fP \fBstring\fP & tag)"

.SS "template<typename\&.\&.\&. Args> \fBvoid\fP xpe::ecs::cEntity::SetTransform (\fBArgs\fP &&\&.\&.\&. args)"

.SS "\fBvoid\fP xpe::ecs::cEntity::SetTransparent (\fBbool\fP transparent)"

.SS "\fBvoid\fP xpe::ecs::cEntity::SetVisible (\fBbool\fP visible)"

.SS "\fBvoid\fP xpe::ecs::cEntity::ToJson (\fBjson\fP & root)\fR [override]\fP, \fR [virtual]\fP"

.PP
Implements \fBxpe::res::cJson\fP\&.
.SS "\fBxml\fP xpe::ecs::cEntity::ToXml (\fBxml\fP & root)\fR [override]\fP, \fR [virtual]\fP"

.PP
Implements \fBxpe::res::cXml\fP\&.
.SS "\fBvoid\fP xpe::ecs::cEntity::UpdateXmlChildren ()"

.SH "Member Data Documentation"
.PP 
.SS "\fBvector\fP<\fBcEntity\fP*> xpe::ecs::cEntity::Children"

.SS "\fBEntityID\fP xpe::ecs::cEntity::m_ID = \fBEntityNull\fP\fR [protected]\fP"

.SS "\fBcScene\fP* xpe::ecs::cEntity::m_Scene = \fBnullptr\fP\fR [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
