.TH "xpe::render::sAtlas::sLocation" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xpe::render::sAtlas::sLocation
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <texture\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBu32\fP \fBLayerIndex\fP = 0"
.br
.ti -1c
.RI "glm::vec2 \fBUV\fP [4]"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBu32\fP xpe::render::sAtlas::sLocation::LayerIndex = 0"

.SS "glm::vec2 xpe::render::sAtlas::sLocation::UV[4]"
\fBInitial value:\fP.PP
.nf
= {
                    glm::vec2(0),
                    glm::vec2(0),
                    glm::vec2(0),
                    glm::vec2(0)
                }
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
