.TH "xpe::physics::sCapsuleShapeDescriptor" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xpe::physics::sCapsuleShapeDescriptor
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <physics_manager\&.hpp>\fP
.PP
Inherits sShapeDescriptor\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsCapsuleShapeDescriptor\fP ()=\fBdelete\fP"
.br
.ti -1c
.RI "\fBsCapsuleShapeDescriptor\fP (\fBf32\fP \fBradius\fP, \fBf32\fP \fBhalfHeight\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBf32\fP \fBRadius\fP"
.br
.ti -1c
.RI "\fBf32\fP \fBHalfHeight\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "xpe::physics::sCapsuleShapeDescriptor::sCapsuleShapeDescriptor ()\fR [delete]\fP"

.SS "xpe::physics::sCapsuleShapeDescriptor::sCapsuleShapeDescriptor (\fBf32\fP radius, \fBf32\fP halfHeight)\fR [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBf32\fP xpe::physics::sCapsuleShapeDescriptor::HalfHeight"

.SS "\fBf32\fP xpe::physics::sCapsuleShapeDescriptor::Radius"


.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
