.TH "xpe::render::sCameraData" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xpe::render::sCameraData
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <buffers\&.hpp>\fP
.PP
Inherits \fBxpe::core::cObject\fP\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "glm::vec3 \fBPosition\fP"
.br
.ti -1c
.RI "\fBfloat\fP \fB_pad0\fP = 0"
.br
.ti -1c
.RI "glm::mat4 \fBView\fP"
.br
.ti -1c
.RI "glm::mat4 \fBProjection\fP"
.br
.ti -1c
.RI "\fBsViewport\fP \fBViewport\fP"
.br
.ti -1c
.RI "\fBfloat\fP \fBExposure\fP = 1\&.0f"
.br
.ti -1c
.RI "\fBfloat\fP \fBGamma\fP = 2\&.2\fBf\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Public Member Functions inherited from \fBxpe::core::cObject\fP
.in +1c
.ti -1c
.RI "\fBvoid\fP * \fBoperator new\fP (\fBusize\fP \fBbyteSize\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBoperator delete\fP (\fBvoid\fP *\fBaddress\fP)"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBfloat\fP xpe::render::sCameraData::_pad0 = 0"

.SS "\fBfloat\fP xpe::render::sCameraData::Exposure = 1\&.0f"

.SS "\fBfloat\fP xpe::render::sCameraData::Gamma = 2\&.2\fBf\fP"

.SS "glm::vec3 xpe::render::sCameraData::Position"

.SS "glm::mat4 xpe::render::sCameraData::Projection"

.SS "glm::mat4 xpe::render::sCameraData::View"

.SS "\fBsViewport\fP xpe::render::sCameraData::Viewport"


.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
