.TH "xpe::ecs::CAnimation" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xpe::ecs::CAnimation
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <components\&.hpp>\fP
.PP
Inherits \fBxpe::res::cJson\fP\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBvector\fP< \fBcEntity\fP * > \fBEntities\fP"
.br
.ti -1c
.RI "\fBsSkeleton\fP \fBSkeleton\fP"
.br
.ti -1c
.RI "\fBvector\fP< \fBsAnimation\fP > \fBAnimations\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Public Member Functions inherited from \fBxpe::res::cJson\fP
.in +1c
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBToJson\fP (\fBjson\fP &\fBroot\fP)=0"
.br
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBFromJson\fP (\fBjson\fP &\fBroot\fP)=0"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBvector\fP<\fBsAnimation\fP> xpe::ecs::CAnimation::Animations"

.SS "\fBvector\fP<\fBcEntity\fP*> xpe::ecs::CAnimation::Entities"

.SS "\fBsSkeleton\fP xpe::ecs::CAnimation::Skeleton"


.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
