.TH "xpe::core::cTime" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xpe::core::cTime
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <time_manager\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBcTime\fP ()=\fBdefault\fP"
.br
.ti -1c
.RI "\fBcTime\fP (\fBconst\fP \fBfloat\fP \fBmillis\fP)"
.br
.ti -1c
.RI "\fBcTime\fP (\fBconst\fP \fBcTime\fP &\fBtime\fP)"
.br
.ti -1c
.RI "\fBfloat\fP \fBMillis\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBfloat\fP \fBSeconds\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBfloat\fP \fBMinutes\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBfloat\fP \fBHours\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBfloat\fP \fBFps\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBvoid\fP \fBSetFps\fP (\fBfloat\fP \fBfps\fP)"
.br
.ti -1c
.RI "\fBcTime\fP & \fBoperator=\fP (\fBfloat\fP \fBf\fP)"
.br
.ti -1c
.RI "\fBoperator float\fP () \fBconst\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "\fBcTime\fP \fBoperator+\fP (\fBconst\fP \fBcTime\fP &\fBt1\fP, \fBconst\fP \fBcTime\fP &\fBt2\fP)"
.br
.ti -1c
.RI "\fBcTime\fP \fBoperator\-\fP (\fBconst\fP \fBcTime\fP &\fBt1\fP, \fBconst\fP \fBcTime\fP &\fBt2\fP)"
.br
.ti -1c
.RI "\fBcTime\fP \fBoperator*\fP (\fBconst\fP \fBcTime\fP &\fBt1\fP, \fBconst\fP \fBcTime\fP &\fBt2\fP)"
.br
.ti -1c
.RI "\fBcTime\fP \fBoperator/\fP (\fBconst\fP \fBcTime\fP &\fBt1\fP, \fBconst\fP \fBcTime\fP &\fBt2\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBoperator+=\fP (\fBcTime\fP &\fBt1\fP, \fBconst\fP \fBcTime\fP &\fBt2\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBoperator\-=\fP (\fBcTime\fP &\fBt1\fP, \fBconst\fP \fBcTime\fP &\fBt2\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBoperator*=\fP (\fBcTime\fP &\fBt1\fP, \fBconst\fP \fBcTime\fP &\fBt2\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBoperator/=\fP (\fBcTime\fP &\fBt1\fP, \fBconst\fP \fBcTime\fP &\fBt2\fP)"
.br
.ti -1c
.RI "\fBfloat\fP \fBoperator+\fP (\fBconst\fP \fBcTime\fP &\fBt1\fP, \fBfloat\fP \fBt2\fP)"
.br
.ti -1c
.RI "\fBfloat\fP \fBoperator\-\fP (\fBconst\fP \fBcTime\fP &\fBt1\fP, \fBfloat\fP \fBt2\fP)"
.br
.ti -1c
.RI "\fBfloat\fP \fBoperator*\fP (\fBconst\fP \fBcTime\fP &\fBt1\fP, \fBfloat\fP \fBt2\fP)"
.br
.ti -1c
.RI "\fBfloat\fP \fBoperator/\fP (\fBconst\fP \fBcTime\fP &\fBt1\fP, \fBfloat\fP \fBt2\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBoperator+=\fP (\fBcTime\fP &\fBt1\fP, \fBfloat\fP \fBt2\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBoperator\-=\fP (\fBcTime\fP &\fBt1\fP, \fBfloat\fP \fBt2\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBoperator*=\fP (\fBcTime\fP &\fBt1\fP, \fBfloat\fP \fBt2\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBoperator/=\fP (\fBcTime\fP &\fBt1\fP, \fBfloat\fP \fBt2\fP)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "xpe::core::cTime::cTime ()\fR [default]\fP"

.SS "xpe::core::cTime::cTime (\fBconst\fP \fBfloat\fP millis)\fR [inline]\fP"

.SS "xpe::core::cTime::cTime (\fBconst\fP \fBcTime\fP & time)\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBfloat\fP xpe::core::cTime::Fps () const\fR [inline]\fP"

.SS "\fBfloat\fP xpe::core::cTime::Hours () const\fR [inline]\fP"

.SS "\fBfloat\fP xpe::core::cTime::Millis () const\fR [inline]\fP"

.SS "\fBfloat\fP xpe::core::cTime::Minutes () const\fR [inline]\fP"

.SS "xpe::core::cTime::operator \fBfloat\fP () const\fR [inline]\fP"

.SS "\fBcTime\fP & xpe::core::cTime::operator= (\fBfloat\fP f)\fR [inline]\fP"

.SS "\fBfloat\fP xpe::core::cTime::Seconds () const\fR [inline]\fP"

.SS "\fBvoid\fP xpe::core::cTime::SetFps (\fBfloat\fP fps)\fR [inline]\fP"

.SH "Friends And Related Symbol Documentation"
.PP 
.SS "\fBcTime\fP \fBoperator\fP* (\fBconst\fP \fBcTime\fP & t1, \fBconst\fP \fBcTime\fP & t2)\fR [friend]\fP"

.SS "\fBfloat\fP \fBoperator\fP* (\fBconst\fP \fBcTime\fP & t1, \fBfloat\fP t2)\fR [friend]\fP"

.SS "\fBvoid\fP \fBoperator\fP*= (\fBcTime\fP & t1, \fBconst\fP \fBcTime\fP & t2)\fR [friend]\fP"

.SS "\fBvoid\fP \fBoperator\fP*= (\fBcTime\fP & t1, \fBfloat\fP t2)\fR [friend]\fP"

.SS "\fBcTime\fP \fBoperator\fP+ (\fBconst\fP \fBcTime\fP & t1, \fBconst\fP \fBcTime\fP & t2)\fR [friend]\fP"

.SS "\fBfloat\fP \fBoperator\fP+ (\fBconst\fP \fBcTime\fP & t1, \fBfloat\fP t2)\fR [friend]\fP"

.SS "\fBvoid\fP \fBoperator\fP+= (\fBcTime\fP & t1, \fBconst\fP \fBcTime\fP & t2)\fR [friend]\fP"

.SS "\fBvoid\fP \fBoperator\fP+= (\fBcTime\fP & t1, \fBfloat\fP t2)\fR [friend]\fP"

.SS "\fBcTime\fP \fBoperator\fP\- (\fBconst\fP \fBcTime\fP & t1, \fBconst\fP \fBcTime\fP & t2)\fR [friend]\fP"

.SS "\fBfloat\fP \fBoperator\fP\- (\fBconst\fP \fBcTime\fP & t1, \fBfloat\fP t2)\fR [friend]\fP"

.SS "\fBvoid\fP \fBoperator\fP\-= (\fBcTime\fP & t1, \fBconst\fP \fBcTime\fP & t2)\fR [friend]\fP"

.SS "\fBvoid\fP \fBoperator\fP\-= (\fBcTime\fP & t1, \fBfloat\fP t2)\fR [friend]\fP"

.SS "\fBcTime\fP \fBoperator\fP/ (\fBconst\fP \fBcTime\fP & t1, \fBconst\fP \fBcTime\fP & t2)\fR [friend]\fP"

.SS "\fBfloat\fP \fBoperator\fP/ (\fBconst\fP \fBcTime\fP & t1, \fBfloat\fP t2)\fR [friend]\fP"

.SS "\fBvoid\fP \fBoperator\fP/= (\fBcTime\fP & t1, \fBconst\fP \fBcTime\fP & t2)\fR [friend]\fP"

.SS "\fBvoid\fP \fBoperator\fP/= (\fBcTime\fP & t1, \fBfloat\fP t2)\fR [friend]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
