.TH "xpe::render::sRenderInstance" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xpe::render::sRenderInstance
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <buffers\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "glm::mat4 \fBModelMatrix\fP"
.br
.ti -1c
.RI "glm::mat4 \fBNormalMatrix\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBMaterialIndex\fP = 0"
.br
.ti -1c
.RI "\fBu32\fP \fBSkeletonIndex\fP = 0"
.br
.ti -1c
.RI "\fBu32\fP \fBLightIndex\fP = 0"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBu32\fP xpe::render::sRenderInstance::LightIndex = 0"

.SS "\fBu32\fP xpe::render::sRenderInstance::MaterialIndex = 0"

.SS "glm::mat4 xpe::render::sRenderInstance::ModelMatrix"

.SS "glm::mat4 xpe::render::sRenderInstance::NormalMatrix"

.SS "\fBu32\fP xpe::render::sRenderInstance::SkeletonIndex = 0"


.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
