.TH "xpe::core::cLogManager" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xpe::core::cLogManager
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <log_manager\&.hpp>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "\fBstatic\fP \fBvoid\fP \fBInit\fP (\fBconst\fP \fBsLoggerDescriptor\fP &\fBdescriptor\fP)"
.br
.ti -1c
.RI "\fBstatic\fP \fBvoid\fP \fBFree\fP ()"
.br
.ti -1c
.RI "\fBstatic\fP spdlog::logger * \fBGetLogger\fP ()"
.br
.ti -1c
.RI "\fBstatic\fP spdlog::logger * \fBGetTracer\fP ()"
.br
.ti -1c
.RI "\fBstatic\fP spdlog::logger * \fBGetMemLogger\fP ()"
.br
.ti -1c
.RI "\fBstatic\fP \fBvoid\fP \fBDumpBacktrace\fP ()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "\fBvoid\fP xpe::core::cLogManager::DumpBacktrace ()\fR [static]\fP"

.SS "\fBvoid\fP xpe::core::cLogManager::Free ()\fR [static]\fP"

.SS "spdlog::logger * xpe::core::cLogManager::GetLogger ()\fR [static]\fP"

.SS "spdlog::logger * xpe::core::cLogManager::GetMemLogger ()\fR [static]\fP"

.SS "spdlog::logger * xpe::core::cLogManager::GetTracer ()\fR [static]\fP"

.SS "\fBvoid\fP xpe::core::cLogManager::Init (\fBconst\fP \fBsLoggerDescriptor\fP & descriptor)\fR [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
