.TH "xpe::render::sFont::sGlyph" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xpe::render::sFont::sGlyph
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <font\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBu8\fP \fBChar\fP"
.br
.ti -1c
.RI "\fBusize\fP \fBWidth\fP"
.br
.ti -1c
.RI "\fBusize\fP \fBHeight\fP"
.br
.ti -1c
.RI "\fBssize\fP \fBLeft\fP"
.br
.ti -1c
.RI "\fBssize\fP \fBTop\fP"
.br
.ti -1c
.RI "\fBusize\fP \fBAdvanceX\fP"
.br
.ti -1c
.RI "\fBusize\fP \fBAdvanceY\fP"
.br
.ti -1c
.RI "\fBvoid\fP * \fBBitmapData\fP = \fBnullptr\fP"
.br
.ti -1c
.RI "\fBusize\fP \fBAtlasXOffset\fP"
.br
.ti -1c
.RI "\fBusize\fP \fBAtlasYOffset\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBusize\fP xpe::render::sFont::sGlyph::AdvanceX"

.SS "\fBusize\fP xpe::render::sFont::sGlyph::AdvanceY"

.SS "\fBusize\fP xpe::render::sFont::sGlyph::AtlasXOffset"

.SS "\fBusize\fP xpe::render::sFont::sGlyph::AtlasYOffset"

.SS "\fBvoid\fP* xpe::render::sFont::sGlyph::BitmapData = \fBnullptr\fP"

.SS "\fBu8\fP xpe::render::sFont::sGlyph::Char"

.SS "\fBusize\fP xpe::render::sFont::sGlyph::Height"

.SS "\fBssize\fP xpe::render::sFont::sGlyph::Left"

.SS "\fBssize\fP xpe::render::sFont::sGlyph::Top"

.SS "\fBusize\fP xpe::render::sFont::sGlyph::Width"


.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
