.TH "xpe::render::sAtlas::sCell" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xpe::render::sAtlas::sCell
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <texture\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsCell\fP ()=\fBdefault\fP"
.br
.ti -1c
.RI "\fBsCell\fP (\fBu32\fP \fBatlasIndex\fP, \fBconst\fP glm::vec2 &\fBposition\fP, \fBconst\fP glm::vec2 &\fBsize\fP, \fBsTextureLayer\fP *\fBtexture\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBu32\fP \fBLayerIndex\fP = 0"
.br
.ti -1c
.RI "glm::vec2 \fBPosition\fP = { 0, 0 }"
.br
.ti -1c
.RI "glm::vec2 \fBSize\fP = { 0, 0 }"
.br
.ti -1c
.RI "\fBsTextureLayer\fP * \fBTexture\fP = \fBnullptr\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "xpe::render::sAtlas::sCell::sCell ()\fR [default]\fP"

.SS "xpe::render::sAtlas::sCell::sCell (\fBu32\fP atlasIndex, \fBconst\fP glm::vec2 & position, \fBconst\fP glm::vec2 & size, \fBsTextureLayer\fP * texture)\fR [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBu32\fP xpe::render::sAtlas::sCell::LayerIndex = 0"

.SS "glm::vec2 xpe::render::sAtlas::sCell::Position = { 0, 0 }"

.SS "glm::vec2 xpe::render::sAtlas::sCell::Size = { 0, 0 }"

.SS "\fBsTextureLayer\fP* xpe::render::sAtlas::sCell::Texture = \fBnullptr\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
