.TH "xpe::core::sMemoryStats" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xpe::core::sMemoryStats
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <hardware_manager\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBusize\fP \fBTotalPhysical\fP = 0"
.br
.ti -1c
.RI "\fBusize\fP \fBAvailablePhysical\fP = 0"
.br
.ti -1c
.RI "\fBusize\fP \fBTotalPageFile\fP = 0"
.br
.ti -1c
.RI "\fBusize\fP \fBAvailablePageFile\fP = 0"
.br
.ti -1c
.RI "\fBusize\fP \fBTotalVirtual\fP = 0"
.br
.ti -1c
.RI "\fBusize\fP \fBAvailableVirtual\fP = 0"
.br
.ti -1c
.RI "\fBusize\fP \fBAvailableVirtualExtended\fP = 0"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBusize\fP xpe::core::sMemoryStats::AvailablePageFile = 0"

.SS "\fBusize\fP xpe::core::sMemoryStats::AvailablePhysical = 0"

.SS "\fBusize\fP xpe::core::sMemoryStats::AvailableVirtual = 0"

.SS "\fBusize\fP xpe::core::sMemoryStats::AvailableVirtualExtended = 0"

.SS "\fBusize\fP xpe::core::sMemoryStats::TotalPageFile = 0"

.SS "\fBusize\fP xpe::core::sMemoryStats::TotalPhysical = 0"

.SS "\fBusize\fP xpe::core::sMemoryStats::TotalVirtual = 0"


.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
