.TH "xpe::render::sCube" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xpe::render::sCube
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <geometries\&.hpp>\fP
.PP
Inherits \fBxpe::render::sGeometry\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsCube\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"


Public Attributes inherited from \fBxpe::render::sGeometry\fP
.in +1c
.ti -1c
.RI "\fBePrimitiveTopology\fP \fBPrimitiveTopology\fP = \fBePrimitiveTopology::DEFAULT\fP"
.br
.ti -1c
.RI "\fBvector\fP< \fBsVertex\fP > \fBVertices\fP"
.br
.ti -1c
.RI "\fBvector\fP< \fBu32\fP > \fBIndices\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "xpe::render::sCube::sCube ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
