.TH "xpe::render::cShader" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xpe::render::cShader
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <shader\&.hpp>\fP
.PP
Inherits \fBxpe::core::cObject\fP\&.
.PP
Inherited by \fBxpe::render::cComputeShader\fP, and \fBxpe::render::cDefaultShader\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBeCategory\fP { \fBNONE\fP = 0, \fBPREPASS\fP = 1, \fBOPAQUE\fP = 2, \fBTRANSPARENT\fP = 3, \fBPOSTFX\fP = 4, \fBUI\fP = 5, \fBFINAL\fP = 6, \fBCOMPUTE\fP = 7 }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBcShader\fP (\fBcShader::eCategory\fP \fBcategory\fP, \fBconst\fP \fBstring\fP &\fBname\fP)"
.br
.ti -1c
.RI "\fBvirtual\fP \fB~cShader\fP ()"
.br
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBDraw\fP (\fBecs::cScene\fP *\fBscene\fP)"
.br
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBBind\fP ()=0"
.br
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBUnbind\fP ()=0"
.br
.in -1c

Public Member Functions inherited from \fBxpe::core::cObject\fP
.in +1c
.ti -1c
.RI "\fBvoid\fP * \fBoperator new\fP (\fBusize\fP \fBbyteSize\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBoperator delete\fP (\fBvoid\fP *\fBaddress\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBu64\fP \fBID\fP = 0"
.br
.ti -1c
.RI "\fBbool\fP \fBEnable\fP = \fBtrue\fP"
.br
.ti -1c
.RI "\fBeCategory\fP \fBCategory\fP = \fBeCategory::PREPASS\fP"
.br
.ti -1c
.RI "\fBcShader\fP * \fBNext\fP = \fBnullptr\fP"
.br
.in -1c
.SH "Member Enumeration Documentation"
.PP 
.SS "\fBenum\fP \fBxpe::render::cShader::eCategory\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fINONE \fP\fP
.TP
\fB\fIPREPASS \fP\fP
.TP
\fB\fIOPAQUE \fP\fP
.TP
\fB\fITRANSPARENT \fP\fP
.TP
\fB\fIPOSTFX \fP\fP
.TP
\fB\fIUI \fP\fP
.TP
\fB\fIFINAL \fP\fP
.TP
\fB\fICOMPUTE \fP\fP
.SH "Constructor & Destructor Documentation"
.PP 
.SS "xpe::render::cShader::cShader (\fBcShader::eCategory\fP category, \fBconst\fP \fBstring\fP & name)\fR [inline]\fP"

.SS "\fBvirtual\fP xpe::render::cShader::~cShader ()\fR [inline]\fP, \fR [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBvirtual\fP \fBvoid\fP xpe::render::cShader::Bind ()\fR [pure virtual]\fP"

.PP
Implemented in \fBxpe::render::cDefaultShader\fP, and \fBxpe::render::cComputeShader\fP\&.
.SS "\fBvirtual\fP \fBvoid\fP xpe::render::cShader::Draw (\fBecs::cScene\fP * scene)\fR [inline]\fP, \fR [virtual]\fP"

.PP
Reimplemented in \fBxpe::render::cDirectionalShadowShader\fP, \fBxpe::render::cPointShadowShader\fP, \fBxpe::render::cSpotShadowShader\fP, \fBxpe::render::cSkyboxShader\fP, \fBxpe::render::cWidgetShader\fP, \fBxpe::render::cTextShader\fP, \fBxpe::render::cComputeShader\fP, \fBxpe::render::cOpaqueShader\fP, \fBxpe::render::cTransparentShader\fP, \fBxpe::render::cCompositeTransparentShader\fP, \fBxpe::render::cSsaoShader\fP, and \fBxpe::render::cFinalShader\fP\&.
.SS "\fBvirtual\fP \fBvoid\fP xpe::render::cShader::Unbind ()\fR [pure virtual]\fP"

.PP
Implemented in \fBxpe::render::cDefaultShader\fP, and \fBxpe::render::cComputeShader\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBeCategory\fP xpe::render::cShader::Category = \fBeCategory::PREPASS\fP"

.SS "\fBbool\fP xpe::render::cShader::Enable = \fBtrue\fP"

.SS "\fBu64\fP xpe::render::cShader::ID = 0"

.SS "\fBcShader\fP* xpe::render::cShader::Next = \fBnullptr\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
