.TH "xpe::core::sGpuStats" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xpe::core::sGpuStats
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <hardware_manager\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBusize\fP \fBMaxTexture2dArray\fP"
.br
.ti -1c
.RI "\fBusize\fP \fBMaxAnisotropyLevel\fP"
.br
.ti -1c
.RI "\fBusize\fP \fBMaxRenderTargetsPerStage\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBIsConcurrentCreatesSupported\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBIsCommandListSupported\fP"
.br
.ti -1c
.RI "\fBusize\fP \fBMaxThreadGroupsPerDimension\fP"
.br
.ti -1c
.RI "\fBusize\fP \fBMaxThreadsPerGroup\fP"
.br
.ti -1c
.RI "glm::ivec3 \fBMaxThreadGroup\fP"
.br
.ti -1c
.RI "\fBusize\fP \fBMaxUnorderedAccessViews\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBbool\fP xpe::core::sGpuStats::IsCommandListSupported"

.SS "\fBbool\fP xpe::core::sGpuStats::IsConcurrentCreatesSupported"

.SS "\fBusize\fP xpe::core::sGpuStats::MaxAnisotropyLevel"

.SS "\fBusize\fP xpe::core::sGpuStats::MaxRenderTargetsPerStage"

.SS "\fBusize\fP xpe::core::sGpuStats::MaxTexture2dArray"

.SS "glm::ivec3 xpe::core::sGpuStats::MaxThreadGroup"

.SS "\fBusize\fP xpe::core::sGpuStats::MaxThreadGroupsPerDimension"

.SS "\fBusize\fP xpe::core::sGpuStats::MaxThreadsPerGroup"

.SS "\fBusize\fP xpe::core::sGpuStats::MaxUnorderedAccessViews"


.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
