.TH "xpe::ecs::CAudio" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xpe::ecs::CAudio
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <components\&.hpp>\fP
.PP
Inherits \fBxpe::res::cJson\fP\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBsAudioSource\fP \fBSource\fP"
.br
.ti -1c
.RI "\fBeAudioState\fP \fBState\fP = eAudioState::INITIAL"
.br
.ti -1c
.RI "\fBu32\fP \fBBufferID\fP = 0"
.br
.ti -1c
.RI "\fBsAudioFile\fP * \fBFile\fP = \fBnullptr\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Public Member Functions inherited from \fBxpe::res::cJson\fP
.in +1c
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBToJson\fP (\fBjson\fP &\fBroot\fP)=0"
.br
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBFromJson\fP (\fBjson\fP &\fBroot\fP)=0"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBu32\fP xpe::ecs::CAudio::BufferID = 0"

.SS "\fBsAudioFile\fP* xpe::ecs::CAudio::File = \fBnullptr\fP"

.SS "\fBsAudioSource\fP xpe::ecs::CAudio::Source"

.SS "\fBeAudioState\fP xpe::ecs::CAudio::State = eAudioState::INITIAL"


.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
