.TH "xpe::core::cHardwareManager" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xpe::core::cHardwareManager
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <hardware_manager\&.hpp>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "\fBstatic\fP \fBvoid\fP \fBUpdateMemoryStats\fP ()"
.br
.ti -1c
.RI "\fBstatic\fP \fBvoid\fP \fBUpdateCpuStats\fP ()"
.br
.ti -1c
.RI "\fBstatic\fP \fBvoid\fP \fBUpdateGpuStats\fP (\fBvoid\fP *\fBdevice\fP)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "\fBstatic\fP \fBsMemoryStats\fP \fBMemory\fP"
.br
.ti -1c
.RI "\fBstatic\fP \fBsCpuStats\fP \fBCPU\fP"
.br
.ti -1c
.RI "\fBstatic\fP \fBsGpuStats\fP \fBGPU\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "\fBstatic\fP \fBvoid\fP xpe::core::cHardwareManager::UpdateCpuStats ()\fR [static]\fP"

.SS "\fBstatic\fP \fBvoid\fP xpe::core::cHardwareManager::UpdateGpuStats (\fBvoid\fP * device)\fR [static]\fP"

.SS "\fBstatic\fP \fBvoid\fP xpe::core::cHardwareManager::UpdateMemoryStats ()\fR [static]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBsCpuStats\fP xpe::core::cHardwareManager::CPU\fR [static]\fP"

.SS "\fBsGpuStats\fP xpe::core::cHardwareManager::GPU\fR [static]\fP"

.SS "\fBsMemoryStats\fP xpe::core::cHardwareManager::Memory\fR [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
