.TH "xpe::render::sModel" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xpe::render::sModel
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <geometries\&.hpp>\fP
.PP
Inherits \fBxpe::render::sGeometry\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsGeometry\fP \fBMerge\fP ()"
.br
.ti -1c
.RI "\fBsGeometry\fP & \fBoperator[]\fP (\fBu32\fP \fBi\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBvector\fP< \fBsGeometry\fP > \fBGeometries\fP"
.br
.in -1c

Public Attributes inherited from \fBxpe::render::sGeometry\fP
.in +1c
.ti -1c
.RI "\fBePrimitiveTopology\fP \fBPrimitiveTopology\fP = \fBePrimitiveTopology::DEFAULT\fP"
.br
.ti -1c
.RI "\fBvector\fP< \fBsVertex\fP > \fBVertices\fP"
.br
.ti -1c
.RI "\fBvector\fP< \fBu32\fP > \fBIndices\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "\fBsGeometry\fP xpe::render::sModel::Merge ()"

.SS "\fBsGeometry\fP & xpe::render::sModel::operator[] (\fBu32\fP i)\fR [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBvector\fP<\fBsGeometry\fP> xpe::render::sModel::Geometries"


.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
