.TH "xpe::render::sMip" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xpe::render::sMip
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <texture\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsMip\fP ()=\fBdefault\fP"
.br
.ti -1c
.RI "\fBsMip\fP (\fBeTextureFormat\fP \fBformat\fP, \fBs32\fP \fBwidth\fP, \fBs32\fP \fBheight\fP, \fBvoid\fP *\fBpixels\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBeTextureFormat\fP \fBFormat\fP"
.br
.ti -1c
.RI "\fBs32\fP \fBWidth\fP"
.br
.ti -1c
.RI "\fBs32\fP \fBHeight\fP = 0"
.br
.ti -1c
.RI "\fBvoid\fP * \fBPixels\fP = \fBnullptr\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "xpe::render::sMip::sMip ()\fR [default]\fP"

.SS "xpe::render::sMip::sMip (\fBeTextureFormat\fP format, \fBs32\fP width, \fBs32\fP height, \fBvoid\fP * pixels)\fR [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBeTextureFormat\fP xpe::render::sMip::Format"

.SS "\fBs32\fP xpe::render::sMip::Height = 0"

.SS "\fBvoid\fP* xpe::render::sMip::Pixels = \fBnullptr\fP"

.SS "\fBs32\fP xpe::render::sMip::Width"


.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
