.TH "xpe::render::sBlendTarget" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xpe::render::sBlendTarget
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <core\&.hpp>\fP
.PP
Inherits \fBxpe::core::cObject\fP\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBbool\fP \fBEnable\fP = \fBfalse\fP"
.br
.ti -1c
.RI "\fBeBlend\fP \fBSrc\fP = \fBeBlend::ONE\fP"
.br
.ti -1c
.RI "\fBeBlend\fP \fBDest\fP = \fBeBlend::ZERO\fP"
.br
.ti -1c
.RI "\fBeBlendOp\fP \fBBlendOp\fP = \fBeBlendOp::ADD\fP"
.br
.ti -1c
.RI "\fBeBlend\fP \fBSrcAlpha\fP = \fBeBlend::ONE\fP"
.br
.ti -1c
.RI "\fBeBlend\fP \fBDestAlpha\fP = \fBeBlend::ZERO\fP"
.br
.ti -1c
.RI "\fBeBlendOp\fP \fBBlendOpAlpha\fP = \fBeBlendOp::ADD\fP"
.br
.ti -1c
.RI "\fBu8\fP \fBRenderTargetWriteMask\fP = \fBeColorWriteEnableMask::ALL\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Public Member Functions inherited from \fBxpe::core::cObject\fP
.in +1c
.ti -1c
.RI "\fBvoid\fP * \fBoperator new\fP (\fBusize\fP \fBbyteSize\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBoperator delete\fP (\fBvoid\fP *\fBaddress\fP)"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBeBlendOp\fP xpe::render::sBlendTarget::BlendOp = \fBeBlendOp::ADD\fP"

.SS "\fBeBlendOp\fP xpe::render::sBlendTarget::BlendOpAlpha = \fBeBlendOp::ADD\fP"

.SS "\fBeBlend\fP xpe::render::sBlendTarget::Dest = \fBeBlend::ZERO\fP"

.SS "\fBeBlend\fP xpe::render::sBlendTarget::DestAlpha = \fBeBlend::ZERO\fP"

.SS "\fBbool\fP xpe::render::sBlendTarget::Enable = \fBfalse\fP"

.SS "\fBu8\fP xpe::render::sBlendTarget::RenderTargetWriteMask = \fBeColorWriteEnableMask::ALL\fP"

.SS "\fBeBlend\fP xpe::render::sBlendTarget::Src = \fBeBlend::ONE\fP"

.SS "\fBeBlend\fP xpe::render::sBlendTarget::SrcAlpha = \fBeBlend::ONE\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
