.TH "xpe::render::sVertex" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xpe::render::sVertex
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <core\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "glm::vec3 \fBPosition\fP = { 0, 0, 0 }"
.br
.ti -1c
.RI "glm::vec2 \fBUV\fP = { 0, 0 }"
.br
.ti -1c
.RI "glm::vec3 \fBNormal\fP = { 0, 0, 0 }"
.br
.ti -1c
.RI "glm::vec3 \fBTangent\fP = { 0, 0, 0 }"
.br
.ti -1c
.RI "glm::ivec4 \fBBoneIDs\fP = { \-1, \-1, \-1, \-1 }"
.br
.ti -1c
.RI "glm::vec4 \fBBoneWeights\fP = { 0, 0, 0, 0 }"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "\fBstatic\fP \fBconst\fP \fBsVertexFormat\fP \fBk_Format\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "glm::ivec4 xpe::render::sVertex::BoneIDs = { \-1, \-1, \-1, \-1 }"

.SS "glm::vec4 xpe::render::sVertex::BoneWeights = { 0, 0, 0, 0 }"

.SS "\fBconst\fP \fBsVertexFormat\fP xpe::render::sVertex::k_Format\fR [static]\fP"
\fBInitial value:\fP.PP
.nf
=
        {{
             sAttributes::k_Pos,
             sAttributes::k_UV,
             sAttributes::k_Normal,
             sAttributes::k_Tangent,
             sAttributes::k_BoneIds,
             sAttributes::k_BoneWeights
         }}
.fi

.SS "glm::vec3 xpe::render::sVertex::Normal = { 0, 0, 0 }"

.SS "glm::vec3 xpe::render::sVertex::Position = { 0, 0, 0 }"

.SS "glm::vec3 xpe::render::sVertex::Tangent = { 0, 0, 0 }"

.SS "glm::vec2 xpe::render::sVertex::UV = { 0, 0 }"


.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
