.TH "xpe::render::sRasterizer" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xpe::render::sRasterizer
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <core\&.hpp>\fP
.PP
Inherits \fBxpe::core::cObject\fP\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBvoid\fP * \fBState\fP = \fBnullptr\fP"
.br
.ti -1c
.RI "\fBeFillMode\fP \fBFillMode\fP = \fBeFillMode::DEFAULT\fP"
.br
.ti -1c
.RI "\fBeCullMode\fP \fBCullMode\fP = \fBeCullMode::DEFAULT\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBFrontCounterClockwise\fP = \fBfalse\fP"
.br
.ti -1c
.RI "\fBint\fP \fBDepthBias\fP = 0"
.br
.ti -1c
.RI "\fBfloat\fP \fBDepthBiasClamp\fP = 0"
.br
.ti -1c
.RI "\fBfloat\fP \fBSlopeScaledDepthBias\fP = 0"
.br
.ti -1c
.RI "\fBbool\fP \fBDepthClipEnable\fP = \fBtrue\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBScissorEnable\fP = \fBfalse\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBMultisampleEnable\fP = \fBfalse\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBAntialiasedLineEnable\fP = \fBfalse\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Public Member Functions inherited from \fBxpe::core::cObject\fP
.in +1c
.ti -1c
.RI "\fBvoid\fP * \fBoperator new\fP (\fBusize\fP \fBbyteSize\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBoperator delete\fP (\fBvoid\fP *\fBaddress\fP)"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBbool\fP xpe::render::sRasterizer::AntialiasedLineEnable = \fBfalse\fP"

.SS "\fBeCullMode\fP xpe::render::sRasterizer::CullMode = \fBeCullMode::DEFAULT\fP"

.SS "\fBint\fP xpe::render::sRasterizer::DepthBias = 0"

.SS "\fBfloat\fP xpe::render::sRasterizer::DepthBiasClamp = 0"

.SS "\fBbool\fP xpe::render::sRasterizer::DepthClipEnable = \fBtrue\fP"

.SS "\fBeFillMode\fP xpe::render::sRasterizer::FillMode = \fBeFillMode::DEFAULT\fP"

.SS "\fBbool\fP xpe::render::sRasterizer::FrontCounterClockwise = \fBfalse\fP"

.SS "\fBbool\fP xpe::render::sRasterizer::MultisampleEnable = \fBfalse\fP"

.SS "\fBbool\fP xpe::render::sRasterizer::ScissorEnable = \fBfalse\fP"

.SS "\fBfloat\fP xpe::render::sRasterizer::SlopeScaledDepthBias = 0"

.SS "\fBvoid\fP* xpe::render::sRasterizer::State = \fBnullptr\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
