.TH "xpe::core::sLoggerDescriptor" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xpe::core::sLoggerDescriptor
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <log_manager\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBconst\fP \fBchar\fP * \fBName\fP"
.br
.ti -1c
.RI "\fBint\fP \fBBacktrace\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBint\fP xpe::core::sLoggerDescriptor::Backtrace"

.SS "\fBconst\fP \fBchar\fP* xpe::core::sLoggerDescriptor::Name"


.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
