.TH "xpe::render::cGeometryManager" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xpe::render::cGeometryManager
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <geometry_manager\&.hpp>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "\fBstatic\fP \fBvoid\fP \fBInit\fP ()"
.br
.ti -1c
.RI "\fBstatic\fP \fBvoid\fP \fBFree\fP ()"
.br
.ti -1c
.RI "\fBstatic\fP std::pair< \fBsGeometry\fP, \fBsGeometryInfo\fP > \fBAddGeometry\fP (\fBconst\fP \fBsGeometry\fP &\fB_geometry\fP)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "std::pair< \fBsGeometry\fP, \fBsGeometryInfo\fP > xpe::render::cGeometryManager::AddGeometry (\fBconst\fP \fBsGeometry\fP & _geometry)\fR [static]\fP"

.SS "\fBvoid\fP xpe::render::cGeometryManager::Free ()\fR [static]\fP"

.SS "\fBvoid\fP xpe::render::cGeometryManager::Init ()\fR [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
