.TH "xpe::ecs::CCamera" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xpe::ecs::CCamera
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <components\&.hpp>\fP
.PP
Inherits \fBxpe::res::cJson\fP\&.
.PP
Inherited by \fBxpe::ecs::COrthoCamera\fP, and \fBxpe::ecs::CPerspectiveCamera\fP\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "glm::vec3 \fBPosition\fP = { 0, 0, \-1 }"
.br
.ti -1c
.RI "glm::vec3 \fBFront\fP = { 0, 0, 0 }"
.br
.ti -1c
.RI "glm::vec3 \fBUp\fP = { 0, 1, 0 }"
.br
.in -1c
.SS "Additional Inherited Members"


Public Member Functions inherited from \fBxpe::res::cJson\fP
.in +1c
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBToJson\fP (\fBjson\fP &\fBroot\fP)=0"
.br
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBFromJson\fP (\fBjson\fP &\fBroot\fP)=0"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "glm::vec3 xpe::ecs::CCamera::Front = { 0, 0, 0 }"

.SS "glm::vec3 xpe::ecs::CCamera::Position = { 0, 0, \-1 }"

.SS "glm::vec3 xpe::ecs::CCamera::Up = { 0, 1, 0 }"


.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
