.TH "xpe::anim::sBone" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xpe::anim::sBone
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <skeleton\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBs32\fP \fBID\fP"
.br
.ti -1c
.RI "\fBstring\fP \fBName\fP"
.br
.ti -1c
.RI "glm::mat4 \fBOffset\fP"
.br
.ti -1c
.RI "glm::mat4 \fBTransform\fP = glm::mat4(1\&.0)"
.br
.ti -1c
.RI "\fBvector\fP< \fBsKeyPosition\fP > \fBKeyPositions\fP"
.br
.ti -1c
.RI "\fBvector\fP< \fBsKeyRotate\fP > \fBKeyRotations\fP"
.br
.ti -1c
.RI "\fBvector\fP< \fBsKeyScale\fP > \fBKeyScales\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBs32\fP xpe::anim::sBone::ID"

.SS "\fBvector\fP<\fBsKeyPosition\fP> xpe::anim::sBone::KeyPositions"

.SS "\fBvector\fP<\fBsKeyRotate\fP> xpe::anim::sBone::KeyRotations"

.SS "\fBvector\fP<\fBsKeyScale\fP> xpe::anim::sBone::KeyScales"

.SS "\fBstring\fP xpe::anim::sBone::Name"

.SS "glm::mat4 xpe::anim::sBone::Offset"

.SS "glm::mat4 xpe::anim::sBone::Transform = glm::mat4(1\&.0)"


.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
