.TH "xpe::ecs::CMaterial" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xpe::ecs::CMaterial
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <components\&.hpp>\fP
.PP
Inherits \fBxpe::res::cJson\fP, and \fBxpe::render::sMaterial\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCMaterial\fP (\fBconst\fP \fBsMaterial\fP &\fBmaterial\fP={})"
.br
.ti -1c
.RI "\fBCMaterial\fP (\fBsMaterial\fP &&\fBmaterial\fP)"
.br
.in -1c

Public Member Functions inherited from \fBxpe::res::cJson\fP
.in +1c
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBToJson\fP (\fBjson\fP &\fBroot\fP)=0"
.br
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBFromJson\fP (\fBjson\fP &\fBroot\fP)=0"
.br
.in -1c
.SS "Additional Inherited Members"


Public Attributes inherited from \fBxpe::render::sMaterial\fP
.in +1c
.ti -1c
.RI "\fBu32\fP \fBIndex\fP = 0"
.br
.ti -1c
.RI "\fBsTextureLayer\fP * \fBAlbedoMap\fP"
.br
.ti -1c
.RI "\fBsTextureLayer\fP * \fBNormalMap\fP"
.br
.ti -1c
.RI "\fBsTextureLayer\fP * \fBParallaxMap\fP"
.br
.ti -1c
.RI "\fBsTextureLayer\fP * \fBMetalMap\fP"
.br
.ti -1c
.RI "\fBsTextureLayer\fP * \fBRoughnessMap\fP"
.br
.ti -1c
.RI "\fBsTextureLayer\fP * \fBAOMap\fP"
.br
.ti -1c
.RI "\fBsTextureLayer\fP * \fBEmissionMap\fP"
.br
.in -1c

Public Attributes inherited from \fBxpe::render::sMaterialData\fP
.in +1c
.ti -1c
.RI "glm::vec4 \fBAlbedo\fP = { 0\&.5, 0\&.5, 0\&.5, 1\&.0 }"
.br
.ti -1c
.RI "\fBBoolean\fP \fBEnableAlbedoMap\fP = \fBfalse\fP"
.br
.ti -1c
.RI "\fBBoolean\fP \fBEnableNormalMap\fP = \fBfalse\fP"
.br
.ti -1c
.RI "\fBBoolean\fP \fBEnableParallaxMap\fP = \fBfalse\fP"
.br
.ti -1c
.RI "\fBfloat\fP \fBParallaxHeightScale\fP = 0\&.1"
.br
.ti -1c
.RI "\fBfloat\fP \fBParallaxMinLayers\fP = 8"
.br
.ti -1c
.RI "\fBfloat\fP \fBParallaxMaxLayers\fP = 32"
.br
.ti -1c
.RI "\fBfloat\fP \fBMetallness\fP = 0\&.5\fBf\fP"
.br
.ti -1c
.RI "\fBBoolean\fP \fBEnableMetalMap\fP = \fBfalse\fP"
.br
.ti -1c
.RI "\fBfloat\fP \fBRoughness\fP = 0\&.5\fBf\fP"
.br
.ti -1c
.RI "\fBBoolean\fP \fBEnableRoughnessMap\fP = \fBfalse\fP"
.br
.ti -1c
.RI "\fBfloat\fP \fBAO\fP = 0\&.5\fBf\fP"
.br
.ti -1c
.RI "\fBBoolean\fP \fBEnableAOMap\fP = \fBfalse\fP"
.br
.ti -1c
.RI "glm::vec3 \fBEmission\fP = { 0, 0, 0 }"
.br
.ti -1c
.RI "\fBBoolean\fP \fBEnableEmissionMap\fP = \fBfalse\fP"
.br
.in -1c

Static Public Attributes inherited from \fBxpe::render::sMaterial\fP
.in +1c
.ti -1c
.RI "\fBstatic\fP \fBconst\fP \fBsMaterialFormat\fP \fBk_AlbedoFormat\fP = {\fBeTextureFormat::SRGBA8\fP, 2048, 2048, \fBK_SLOT_ALBEDO\fP }"
.br
.ti -1c
.RI "\fBstatic\fP \fBconst\fP \fBsMaterialFormat\fP \fBk_NormalFormat\fP = {\fBeTextureFormat::RGBA8\fP, 2048, 2048, \fBK_SLOT_BUMPING\fP }"
.br
.ti -1c
.RI "\fBstatic\fP \fBconst\fP \fBsMaterialFormat\fP \fBk_ParallaxFormat\fP = {\fBeTextureFormat::R8\fP, 2048, 2048, \fBK_SLOT_PARALLAX\fP }"
.br
.ti -1c
.RI "\fBstatic\fP \fBconst\fP \fBsMaterialFormat\fP \fBk_MetalFormat\fP = {\fBeTextureFormat::R8\fP, 2048, 2048, \fBK_SLOT_METALLIC\fP }"
.br
.ti -1c
.RI "\fBstatic\fP \fBconst\fP \fBsMaterialFormat\fP \fBk_RoughnessFormat\fP = {\fBeTextureFormat::R8\fP, 2048, 2048, \fBK_SLOT_ROUGHNESS\fP }"
.br
.ti -1c
.RI "\fBstatic\fP \fBconst\fP \fBsMaterialFormat\fP \fBk_AoFormat\fP = {\fBeTextureFormat::R8\fP, 2048, 2048, \fBK_SLOT_AO\fP }"
.br
.ti -1c
.RI "\fBstatic\fP \fBconst\fP \fBsMaterialFormat\fP \fBk_EmissionFormat\fP = {\fBeTextureFormat::SRGBA8\fP, 2048, 2048, \fBK_SLOT_EMISSION\fP }"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "xpe::ecs::CMaterial::CMaterial (\fBconst\fP \fBsMaterial\fP & material = \fR{}\fP)\fR [inline]\fP"

.SS "xpe::ecs::CMaterial::CMaterial (\fBsMaterial\fP && material)\fR [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
