.TH "xpe::anim" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xpe::anim
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBcAnimSystem\fP"
.br
.ti -1c
.RI "class \fBcSkeletonManager\fP"
.br
.ti -1c
.RI "struct \fBsAnimation\fP"
.br
.ti -1c
.RI "struct \fBsAnimationNode\fP"
.br
.ti -1c
.RI "struct \fBsBone\fP"
.br
.ti -1c
.RI "struct \fBsKeyPosition\fP"
.br
.ti -1c
.RI "struct \fBsKeyRotate\fP"
.br
.ti -1c
.RI "struct \fBsKeyScale\fP"
.br
.ti -1c
.RI "struct \fBsSkeleton\fP"
.br
.ti -1c
.RI "struct \fBsSkeletonInfo\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
