.TH "xpe::ecs::CSkeletonInfo" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xpe::ecs::CSkeletonInfo
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <components\&.hpp>\fP
.PP
Inherits \fBxpe::anim::sSkeletonInfo\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCSkeletonInfo\fP (\fBconst\fP \fBsSkeletonInfo\fP &\fBskeletonInfo\fP={})"
.br
.ti -1c
.RI "\fBCSkeletonInfo\fP (\fBsSkeletonInfo\fP &&\fBskeletonInfo\fP)"
.br
.in -1c
.SS "Additional Inherited Members"


Public Attributes inherited from \fBxpe::anim::sSkeletonInfo\fP
.in +1c
.ti -1c
.RI "\fBrender::sGeometryInfo\fP \fBGeometryInfo\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBSkeletonIndex\fP = 0"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "xpe::ecs::CSkeletonInfo::CSkeletonInfo (\fBconst\fP \fBsSkeletonInfo\fP & skeletonInfo = \fR{}\fP)\fR [inline]\fP"

.SS "xpe::ecs::CSkeletonInfo::CSkeletonInfo (\fBsSkeletonInfo\fP && skeletonInfo)\fR [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
