.TH "xpe::ecs::COrthoCamera" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xpe::ecs::COrthoCamera
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <components\&.hpp>\fP
.PP
Inherits \fBxpe::ecs::CCamera\fP, and sOrthoMatrix\&.
.SS "Additional Inherited Members"


Public Member Functions inherited from \fBxpe::res::cJson\fP
.in +1c
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBToJson\fP (\fBjson\fP &\fBroot\fP)=0"
.br
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBFromJson\fP (\fBjson\fP &\fBroot\fP)=0"
.br
.in -1c

Public Attributes inherited from \fBxpe::ecs::CCamera\fP
.in +1c
.ti -1c
.RI "glm::vec3 \fBPosition\fP = { 0, 0, \-1 }"
.br
.ti -1c
.RI "glm::vec3 \fBFront\fP = { 0, 0, 0 }"
.br
.ti -1c
.RI "glm::vec3 \fBUp\fP = { 0, 1, 0 }"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
