.TH "xpe::core::sStackTypedAllocator< T >" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xpe::core::sStackTypedAllocator< T >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <allocators\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsStackTypedAllocator\fP (\fBusize\fP \fBcount\fP)"
.br
.ti -1c
.RI "\fB~sStackTypedAllocator\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBusize\fP \fBSize\fP = 0"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<\fBtypename\fP \fBT\fP > \fBxpe::core::sStackTypedAllocator\fP< \fBT\fP >::sStackTypedAllocator (\fBusize\fP count)"

.SS "template<\fBtypename\fP \fBT\fP > \fBxpe::core::sStackTypedAllocator\fP< \fBT\fP >::~\fBsStackTypedAllocator\fP ()"

.SH "Member Data Documentation"
.PP 
.SS "template<\fBtypename\fP \fBT\fP > \fBusize\fP \fBxpe::core::sStackTypedAllocator\fP< \fBT\fP >::Size = 0"


.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
