.TH "xpe::render::Samplers" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xpe::render::Samplers
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <bindings\&.hpp>\fP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "\fBstatic\fP \fBsSampler\fP * \fBMaterial\fP = \fBnullptr\fP"
.br
.ti -1c
.RI "\fBstatic\fP \fBsSampler\fP * \fBShadow\fP = \fBnullptr\fP"
.br
.ti -1c
.RI "\fBstatic\fP \fBsSampler\fP * \fBWidget\fP = \fBnullptr\fP"
.br
.ti -1c
.RI "\fBstatic\fP \fBsSampler\fP * \fBSkybox\fP = \fBnullptr\fP"
.br
.ti -1c
.RI "\fBstatic\fP \fBsSampler\fP * \fBFont\fP = \fBnullptr\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBsSampler\fP * xpe::render::Samplers::Font = \fBnullptr\fP\fR [static]\fP"

.SS "\fBsSampler\fP * xpe::render::Samplers::Material = \fBnullptr\fP\fR [static]\fP"

.SS "\fBsSampler\fP * xpe::render::Samplers::Shadow = \fBnullptr\fP\fR [static]\fP"

.SS "\fBsSampler\fP * xpe::render::Samplers::Skybox = \fBnullptr\fP\fR [static]\fP"

.SS "\fBsSampler\fP * xpe::render::Samplers::Widget = \fBnullptr\fP\fR [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
