.TH "xpe::render::sSkybox" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xpe::render::sSkybox
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <skybox_manager\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBsGeometry\fP \fBGeometry\fP"
.br
.ti -1c
.RI "\fBsGeometryInfo\fP \fBGeometryInfo\fP"
.br
.ti -1c
.RI "\fBsTexture\fP * \fBTexture\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBsGeometry\fP xpe::render::sSkybox::Geometry"

.SS "\fBsGeometryInfo\fP xpe::render::sSkybox::GeometryInfo"

.SS "\fBsTexture\fP* xpe::render::sSkybox::Texture"


.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
