.TH "xpe::core::sMouseCursor" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xpe::core::sMouseCursor
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <input_manager\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "glm::vec2 \fBPosition\fP = { 0, 0 }"
.br
.ti -1c
.RI "glm::vec2 \fBDelta\fP = { 0, 0 }"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "glm::vec2 xpe::core::sMouseCursor::Delta = { 0, 0 }"

.SS "glm::vec2 xpe::core::sMouseCursor::Position = { 0, 0 }"


.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
