.TH "xpe::render::Buffers" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xpe::render::Buffers
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <bindings\&.hpp>\fP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "\fBstatic\fP \fBsVertexBuffer\fP * \fBVertex\fP = \fBnullptr\fP"
.br
.ti -1c
.RI "\fBstatic\fP \fBsIndexBuffer\fP * \fBIndex\fP = \fBnullptr\fP"
.br
.ti -1c
.RI "\fBstatic\fP \fBsCameraBuffer\fP * \fBCamera\fP = \fBnullptr\fP"
.br
.ti -1c
.RI "\fBstatic\fP \fBsDirectLightBuffer\fP * \fBDirectLight\fP = \fBnullptr\fP"
.br
.ti -1c
.RI "\fBstatic\fP \fBsPointLightBuffer\fP * \fBPointLight\fP = \fBnullptr\fP"
.br
.ti -1c
.RI "\fBstatic\fP \fBsSpotLightBuffer\fP * \fBSpotLight\fP = \fBnullptr\fP"
.br
.ti -1c
.RI "\fBstatic\fP \fBsMaterialDataBuffer\fP * \fBMaterial\fP = \fBnullptr\fP"
.br
.ti -1c
.RI "\fBstatic\fP \fBsShadowPcfBuffer\fP * \fBShadowPCF\fP = \fBnullptr\fP"
.br
.ti -1c
.RI "\fBstatic\fP \fBsSkeletonBuffer\fP * \fBSkeleton\fP = \fBnullptr\fP"
.br
.ti -1c
.RI "\fBstatic\fP \fBsSsaoBuffer\fP * \fBSSAO\fP = \fBnullptr\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBsCameraBuffer\fP * xpe::render::Buffers::Camera = \fBnullptr\fP\fR [static]\fP"

.SS "\fBsDirectLightBuffer\fP * xpe::render::Buffers::DirectLight = \fBnullptr\fP\fR [static]\fP"

.SS "\fBsIndexBuffer\fP * xpe::render::Buffers::Index = \fBnullptr\fP\fR [static]\fP"

.SS "\fBsMaterialDataBuffer\fP * xpe::render::Buffers::Material = \fBnullptr\fP\fR [static]\fP"

.SS "\fBsPointLightBuffer\fP * xpe::render::Buffers::PointLight = \fBnullptr\fP\fR [static]\fP"

.SS "\fBsShadowPcfBuffer\fP * xpe::render::Buffers::ShadowPCF = \fBnullptr\fP\fR [static]\fP"

.SS "\fBsSkeletonBuffer\fP * xpe::render::Buffers::Skeleton = \fBnullptr\fP\fR [static]\fP"

.SS "\fBsSpotLightBuffer\fP * xpe::render::Buffers::SpotLight = \fBnullptr\fP\fR [static]\fP"

.SS "\fBsSsaoBuffer\fP * xpe::render::Buffers::SSAO = \fBnullptr\fP\fR [static]\fP"

.SS "\fBsVertexBuffer\fP * xpe::render::Buffers::Vertex = \fBnullptr\fP\fR [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
