.TH "xpe::render::sMaterialData" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xpe::render::sMaterialData
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <buffers\&.hpp>\fP
.PP
Inherited by \fBxpe::render::sMaterial\fP\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "glm::vec4 \fBAlbedo\fP = { 0\&.5, 0\&.5, 0\&.5, 1\&.0 }"
.br
.ti -1c
.RI "\fBBoolean\fP \fBEnableAlbedoMap\fP = \fBfalse\fP"
.br
.ti -1c
.RI "\fBBoolean\fP \fBEnableNormalMap\fP = \fBfalse\fP"
.br
.ti -1c
.RI "\fBBoolean\fP \fBEnableParallaxMap\fP = \fBfalse\fP"
.br
.ti -1c
.RI "\fBfloat\fP \fBParallaxHeightScale\fP = 0\&.1"
.br
.ti -1c
.RI "\fBfloat\fP \fBParallaxMinLayers\fP = 8"
.br
.ti -1c
.RI "\fBfloat\fP \fBParallaxMaxLayers\fP = 32"
.br
.ti -1c
.RI "\fBfloat\fP \fBMetallness\fP = 0\&.5\fBf\fP"
.br
.ti -1c
.RI "\fBBoolean\fP \fBEnableMetalMap\fP = \fBfalse\fP"
.br
.ti -1c
.RI "\fBfloat\fP \fBRoughness\fP = 0\&.5\fBf\fP"
.br
.ti -1c
.RI "\fBBoolean\fP \fBEnableRoughnessMap\fP = \fBfalse\fP"
.br
.ti -1c
.RI "\fBfloat\fP \fBAO\fP = 0\&.5\fBf\fP"
.br
.ti -1c
.RI "\fBBoolean\fP \fBEnableAOMap\fP = \fBfalse\fP"
.br
.ti -1c
.RI "glm::vec3 \fBEmission\fP = { 0, 0, 0 }"
.br
.ti -1c
.RI "\fBBoolean\fP \fBEnableEmissionMap\fP = \fBfalse\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "glm::vec4 xpe::render::sMaterialData::Albedo = { 0\&.5, 0\&.5, 0\&.5, 1\&.0 }"

.SS "\fBfloat\fP xpe::render::sMaterialData::AO = 0\&.5\fBf\fP"

.SS "glm::vec3 xpe::render::sMaterialData::Emission = { 0, 0, 0 }"

.SS "\fBBoolean\fP xpe::render::sMaterialData::EnableAlbedoMap = \fBfalse\fP"

.SS "\fBBoolean\fP xpe::render::sMaterialData::EnableAOMap = \fBfalse\fP"

.SS "\fBBoolean\fP xpe::render::sMaterialData::EnableEmissionMap = \fBfalse\fP"

.SS "\fBBoolean\fP xpe::render::sMaterialData::EnableMetalMap = \fBfalse\fP"

.SS "\fBBoolean\fP xpe::render::sMaterialData::EnableNormalMap = \fBfalse\fP"

.SS "\fBBoolean\fP xpe::render::sMaterialData::EnableParallaxMap = \fBfalse\fP"

.SS "\fBBoolean\fP xpe::render::sMaterialData::EnableRoughnessMap = \fBfalse\fP"

.SS "\fBfloat\fP xpe::render::sMaterialData::Metallness = 0\&.5\fBf\fP"

.SS "\fBfloat\fP xpe::render::sMaterialData::ParallaxHeightScale = 0\&.1"

.SS "\fBfloat\fP xpe::render::sMaterialData::ParallaxMaxLayers = 32"

.SS "\fBfloat\fP xpe::render::sMaterialData::ParallaxMinLayers = 8"

.SS "\fBfloat\fP xpe::render::sMaterialData::Roughness = 0\&.5\fBf\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
