.TH "xpe::anim::cSkeletonManager" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xpe::anim::cSkeletonManager
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <skeleton_manager\&.hpp>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "\fBstatic\fP \fBvoid\fP \fBInit\fP ()"
.br
.ti -1c
.RI "\fBstatic\fP \fBvoid\fP \fBFree\fP ()"
.br
.ti -1c
.RI "\fBstatic\fP \fBvoid\fP \fBFlush\fP ()"
.br
.ti -1c
.RI "template<typename\&.\&.\&. Args> \fBstatic\fP std::pair< \fBsSkeleton\fP, \fBsSkeletonInfo\fP > \fBAddSkeleton\fP (\fBArgs\fP &&\&.\&.\&. \fBargs\fP)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "template<typename\&.\&.\&. Args> std::pair< \fBsSkeleton\fP, \fBsSkeletonInfo\fP > xpe::anim::cSkeletonManager::AddSkeleton (\fBArgs\fP &&\&.\&.\&. args)\fR [static]\fP"

.SS "\fBvoid\fP xpe::anim::cSkeletonManager::Flush ()\fR [static]\fP"

.SS "\fBvoid\fP xpe::anim::cSkeletonManager::Free ()\fR [static]\fP"

.SS "\fBvoid\fP xpe::anim::cSkeletonManager::Init ()\fR [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
