.TH "xpe::ecs::CSkeleton" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xpe::ecs::CSkeleton
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <components\&.hpp>\fP
.PP
Inherits \fBxpe::anim::sSkeleton\fP, and \fBxpe::res::cJson\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCSkeleton\fP (\fBconst\fP \fBsSkeleton\fP &\fBskeleton\fP={})"
.br
.ti -1c
.RI "\fBCSkeleton\fP (\fBsSkeleton\fP &&\fBskeleton\fP)"
.br
.in -1c

Public Member Functions inherited from \fBxpe::res::cJson\fP
.in +1c
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBToJson\fP (\fBjson\fP &\fBroot\fP)=0"
.br
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBFromJson\fP (\fBjson\fP &\fBroot\fP)=0"
.br
.in -1c
.SS "Additional Inherited Members"


Public Attributes inherited from \fBxpe::anim::sSkeleton\fP
.in +1c
.ti -1c
.RI "\fBunordered_map\fP< \fBstring\fP, \fBsBone\fP > \fBBones\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "xpe::ecs::CSkeleton::CSkeleton (\fBconst\fP \fBsSkeleton\fP & skeleton = \fR{}\fP)\fR [inline]\fP"

.SS "xpe::ecs::CSkeleton::CSkeleton (\fBsSkeleton\fP && skeleton)\fR [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
