.TH "xpe::physics::sPlaneShapeDescriptor" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xpe::physics::sPlaneShapeDescriptor
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <physics_manager\&.hpp>\fP
.PP
Inherits sShapeDescriptor\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsPlaneShapeDescriptor\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "xpe::physics::sPlaneShapeDescriptor::sPlaneShapeDescriptor ()\fR [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
