.TH "xpe::ecs::CTransform" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xpe::ecs::CTransform
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <components\&.hpp>\fP
.PP
Inherits \fBxpe::math::sTransform\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCTransform\fP (\fBconst\fP \fBsTransform\fP &\fBtransform\fP={})"
.br
.ti -1c
.RI "\fBCTransform\fP (\fBsTransform\fP &&\fBtransform\fP)"
.br
.in -1c
.SS "Additional Inherited Members"


Public Attributes inherited from \fBxpe::math::sModelMatrix\fP
.in +1c
.ti -1c
.RI "glm::vec3 \fBPosition\fP = { 0, 0, 0 }"
.br
.ti -1c
.RI "glm::vec3 \fBRotation\fP = { 0, 0, 0 }"
.br
.ti -1c
.RI "glm::vec3 \fBScale\fP = { 1, 1, 1 }"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "xpe::ecs::CTransform::CTransform (\fBconst\fP \fBsTransform\fP & transform = \fR{}\fP)\fR [inline]\fP"

.SS "xpe::ecs::CTransform::CTransform (\fBsTransform\fP && transform)\fR [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
