.TH "xpe::render::Viewports" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xpe::render::Viewports
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <bindings\&.hpp>\fP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "\fBstatic\fP \fBsViewport\fP * \fBShadow\fP = \fBnullptr\fP"
.br
.ti -1c
.RI "\fBstatic\fP \fBsViewport\fP * \fBSSAO\fP = \fBnullptr\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBsViewport\fP * xpe::render::Viewports::Shadow = \fBnullptr\fP\fR [static]\fP"

.SS "\fBsViewport\fP * xpe::render::Viewports::SSAO = \fBnullptr\fP\fR [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
