.TH "xpe::render::sAttributes" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xpe::render::sAttributes
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <core\&.hpp>\fP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "\fBstatic\fP \fBconstexpr\fP \fBsVertexFormat::sAttribute\fP \fBk_Pos\fP = { 0, 'XPE_POSITION', \fBsVertexFormat::sAttribute::eType::VEC3_FLOAT\fP, 12 }"
.br
.ti -1c
.RI "\fBstatic\fP \fBconstexpr\fP \fBsVertexFormat::sAttribute\fP \fBk_UV\fP = { 1, 'XPE_UV', \fBsVertexFormat::sAttribute::eType::VEC2_FLOAT\fP, 8 }"
.br
.ti -1c
.RI "\fBstatic\fP \fBconstexpr\fP \fBsVertexFormat::sAttribute\fP \fBk_Normal\fP = { 2, 'XPE_NORMAL', \fBsVertexFormat::sAttribute::eType::VEC3_FLOAT\fP, 12 }"
.br
.ti -1c
.RI "\fBstatic\fP \fBconstexpr\fP \fBsVertexFormat::sAttribute\fP \fBk_Tangent\fP = { 3, 'XPE_TANGENT', \fBsVertexFormat::sAttribute::eType::VEC3_FLOAT\fP, 12 }"
.br
.ti -1c
.RI "\fBstatic\fP \fBconstexpr\fP \fBsVertexFormat::sAttribute\fP \fBk_BoneIds\fP = { 4, 'XPE_BONE_IDS', \fBsVertexFormat::sAttribute::eType::VEC4_INT\fP, 16 }"
.br
.ti -1c
.RI "\fBstatic\fP \fBconstexpr\fP \fBsVertexFormat::sAttribute\fP \fBk_BoneWeights\fP = { 5, 'XPE_BONE_WEIGHTS', \fBsVertexFormat::sAttribute::eType::VEC4_FLOAT\fP, 16 }"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBconstexpr\fP \fBsVertexFormat::sAttribute\fP xpe::render::sAttributes::k_BoneIds = { 4, 'XPE_BONE_IDS', \fBsVertexFormat::sAttribute::eType::VEC4_INT\fP, 16 }\fR [static]\fP, \fR [constexpr]\fP"

.SS "\fBconstexpr\fP \fBsVertexFormat::sAttribute\fP xpe::render::sAttributes::k_BoneWeights = { 5, 'XPE_BONE_WEIGHTS', \fBsVertexFormat::sAttribute::eType::VEC4_FLOAT\fP, 16 }\fR [static]\fP, \fR [constexpr]\fP"

.SS "\fBconstexpr\fP \fBsVertexFormat::sAttribute\fP xpe::render::sAttributes::k_Normal = { 2, 'XPE_NORMAL', \fBsVertexFormat::sAttribute::eType::VEC3_FLOAT\fP, 12 }\fR [static]\fP, \fR [constexpr]\fP"

.SS "\fBconstexpr\fP \fBsVertexFormat::sAttribute\fP xpe::render::sAttributes::k_Pos = { 0, 'XPE_POSITION', \fBsVertexFormat::sAttribute::eType::VEC3_FLOAT\fP, 12 }\fR [static]\fP, \fR [constexpr]\fP"

.SS "\fBconstexpr\fP \fBsVertexFormat::sAttribute\fP xpe::render::sAttributes::k_Tangent = { 3, 'XPE_TANGENT', \fBsVertexFormat::sAttribute::eType::VEC3_FLOAT\fP, 12 }\fR [static]\fP, \fR [constexpr]\fP"

.SS "\fBconstexpr\fP \fBsVertexFormat::sAttribute\fP xpe::render::sAttributes::k_UV = { 1, 'XPE_UV', \fBsVertexFormat::sAttribute::eType::VEC2_FLOAT\fP, 8 }\fR [static]\fP, \fR [constexpr]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
