.TH "xpe::render::sAtlas" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xpe::render::sAtlas
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <texture\&.hpp>\fP
.PP
Inherits \fBxpe::render::sTexture\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBsCell\fP"
.br
.ti -1c
.RI "struct \fBsLocation\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBvoid\fP \fBAddLayer\fP ()"
.br
.ti -1c
.RI "template<typename\&.\&.\&. Args> \fBsLocation\fP \fBAddCell\fP (\fBArgs\fP &&\&.\&.\&. \fBargs\fP)"
.br
.ti -1c
.RI "template<typename\&.\&.\&. Args> \fBvoid\fP \fBRemoveCell\fP (\fBArgs\fP &&\&.\&.\&. \fBargs\fP)"
.br
.in -1c

Public Member Functions inherited from \fBxpe::render::sTexture\fP
.in +1c
.ti -1c
.RI "\fBsTexture\fP ()"
.br
.ti -1c
.RI "\fB~sTexture\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBInit\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBFree\fP ()"
.br
.ti -1c
.RI "\fBsTextureLayer\fP \fBCreateLayer\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBvoid\fP \fBRemoveLayerAt\fP (\fBu32\fP \fBindex\fP)"
.br
.ti -1c
.RI "\fBu32\fP \fBGetMipLevels\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBvoid\fP \fBWindowFrameResized\fP (\fBs32\fP \fBwidth\fP, \fBs32\fP \fBheight\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBResize\fP (\fBs32\fP \fBwidth\fP, \fBs32\fP \fBheight\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBResizePixels\fP (\fBs32\fP \fBwidth\fP, \fBs32\fP \fBheight\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBFlip\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBGenerateMips\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBFlushLayer\fP (\fBu32\fP \fBindex\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBFlush\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBSetResizable\fP (\fBbool\fP \fBresizable\fP)"
.br
.ti -1c
.RI "\fBbool\fP \fBIsResizable\fP () \fBconst\fP"
.br
.in -1c

Public Member Functions inherited from \fBxpe::core::cObject\fP
.in +1c
.ti -1c
.RI "\fBvoid\fP * \fBoperator new\fP (\fBusize\fP \fBbyteSize\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBoperator delete\fP (\fBvoid\fP *\fBaddress\fP)"
.br
.in -1c
.SS "Additional Inherited Members"


Public Types inherited from \fBxpe::render::sTexture\fP
.in +1c
.ti -1c
.RI "enum class \fBeType\fP { \fBTEXTURE_1D\fP, \fBTEXTURE_2D\fP, \fBTEXTURE_2D_MS\fP, \fBTEXTURE_2D_DEPTH_STENCIL\fP, \fBTEXTURE_2D_ARRAY\fP, \fBTEXTURE_3D\fP, \fBTEXTURE_CUBE\fP, \fBTEXTURE_DEFAULT\fP = TEXTURE_2D }"
.br
.ti -1c
.RI "enum class \fBeUsage\fP { \fBDEFAULT\fP, \fBSTATIC\fP, \fBDYNAMIC\fP, \fBSTAGING\fP }"
.br
.in -1c

Public Types inherited from \fBxpe::render::sResource\fP
.in +1c
.ti -1c
.RI "enum class \fBeViewType\fP { \fBNONE\fP, \fBDEPTH_STENCIL\fP, \fBRENDER_TARGET\fP, \fBSRV\fP, \fBUAV\fP }"
.br
.ti -1c
.RI "enum class \fBeMapType\fP { \fBREAD\fP, \fBWRITE\fP, \fBREAD_WRITE\fP, \fBWRITE_NO_OVERWRITE\fP, \fBWRITE_DISCARD\fP }"
.br
.in -1c

Static Public Member Functions inherited from \fBxpe::render::sTexture\fP
.in +1c
.ti -1c
.RI "\fBstatic\fP \fBu32\fP \fBGetMipsLevels\fP (\fBs32\fP \fBwidth\fP)"
.br
.in -1c

Public Attributes inherited from \fBxpe::render::sTexture\fP
.in +1c
.ti -1c
.RI "\fBeType\fP \fBType\fP = \fBeType::TEXTURE_DEFAULT\fP"
.br
.ti -1c
.RI "\fBeUsage\fP \fBUsage\fP = \fBeUsage::DEFAULT\fP"
.br
.ti -1c
.RI "\fBs32\fP \fBWidth\fP"
.br
.ti -1c
.RI "\fBs32\fP \fBHeight\fP"
.br
.ti -1c
.RI "\fBs32\fP \fBDepth\fP = 1"
.br
.ti -1c
.RI "\fBs32\fP \fBChannels\fP"
.br
.ti -1c
.RI "\fBeTextureFormat\fP \fBFormat\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBSampleCount\fP = 1"
.br
.ti -1c
.RI "\fBbool\fP \fBEnableRenderTarget\fP = \fBfalse\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBSlot\fP = 0"
.br
.ti -1c
.RI "\fBu32\fP \fBMostDetailedMip\fP = 0"
.br
.ti -1c
.RI "\fBbool\fP \fBInitializeData\fP = \fBtrue\fP"
.br
.ti -1c
.RI "\fBvector\fP< \fBsTextureLayer\fP > \fBLayers\fP"
.br
.in -1c

Public Attributes inherited from \fBxpe::render::sResource\fP
.in +1c
.ti -1c
.RI "\fBvoid\fP * \fBInstance\fP = \fBnullptr\fP"
.br
.ti -1c
.RI "\fBvoid\fP * \fBViewInstance\fP = \fBnullptr\fP"
.br
.ti -1c
.RI "\fBeViewType\fP \fBViewType\fP = \fBeViewType::NONE\fP"
.br
.in -1c

Static Public Attributes inherited from \fBxpe::render::sTexture\fP
.in +1c
.ti -1c
.RI "\fBstatic\fP \fBconst\fP std::unordered_map< \fBeTextureFormat\fP, \fBint\fP > \fBk_ChannelTable\fP"
.br
.ti -1c
.RI "\fBstatic\fP \fBconst\fP std::unordered_map< \fBeTextureFormat\fP, \fBint\fP > \fBk_BppTable\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "template<typename\&.\&.\&. Args> \fBsAtlas::sLocation\fP xpe::render::sAtlas::AddCell (\fBArgs\fP &&\&.\&.\&. args)"

.SS "\fBvoid\fP xpe::render::sAtlas::AddLayer ()"

.SS "template<typename\&.\&.\&. Args> \fBvoid\fP xpe::render::sAtlas::RemoveCell (\fBArgs\fP &&\&.\&.\&. args)"


.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
