.TH "xpe::anim::sSkeletonInfo" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xpe::anim::sSkeletonInfo
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <skeleton\&.hpp>\fP
.PP
Inherited by \fBxpe::ecs::CSkeletonInfo\fP\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBrender::sGeometryInfo\fP \fBGeometryInfo\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBSkeletonIndex\fP = 0"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBrender::sGeometryInfo\fP xpe::anim::sSkeletonInfo::GeometryInfo"

.SS "\fBu32\fP xpe::anim::sSkeletonInfo::SkeletonIndex = 0"


.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
