.TH "xpe::core::cMemoryPool" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xpe::core::cMemoryPool
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <memory_manager\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBvoid\fP \fBInit\fP (\fBconst\fP \fBusize\fP \fBbyteSize\fP, \fBconst\fP \fBusize\fP \fBallocs\fP, \fBconst\fP \fBusize\fP \fBalignment\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBRelease\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP * \fBAllocate\fP (\fBconst\fP \fBusize\fP \fBsize\fP)"
.br
.ti -1c
.RI "\fBbool\fP \fBFree\fP (\fBvoid\fP *\fBaddress\fP)"
.br
.ti -1c
.RI "\fBusize\fP \fBGetAllocCount\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBusize\fP \fBGetByteSize\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBusize\fP \fBGetBytesUsage\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBusize\fP \fBGetLastFreedBytes\fP () \fBconst\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "\fBvoid\fP * xpe::core::cMemoryPool::Allocate (\fBconst\fP \fBusize\fP size)"

.SS "\fBbool\fP xpe::core::cMemoryPool::Free (\fBvoid\fP * address)"

.SS "\fBusize\fP xpe::core::cMemoryPool::GetAllocCount () const\fR [inline]\fP"

.SS "\fBusize\fP xpe::core::cMemoryPool::GetByteSize () const\fR [inline]\fP"

.SS "\fBusize\fP xpe::core::cMemoryPool::GetBytesUsage () const\fR [inline]\fP"

.SS "\fBusize\fP xpe::core::cMemoryPool::GetLastFreedBytes () const\fR [inline]\fP"

.SS "\fBvoid\fP xpe::core::cMemoryPool::Init (\fBconst\fP \fBusize\fP byteSize, \fBconst\fP \fBusize\fP allocs, \fBconst\fP \fBusize\fP alignment)"

.SS "\fBvoid\fP xpe::core::cMemoryPool::Release ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
