.TH "xpe::render::sSampler" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xpe::render::sSampler
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <texture\&.hpp>\fP
.PP
Inherits \fBxpe::render::sResource\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum class \fBeComparison\fP { \fBNEVER\fP, \fBLESS\fP, \fBEQUAL\fP, \fBLESS_EQUAL\fP, \fBGREATER\fP, \fBNOT_EQUAL\fP, \fBGREATER_EQUAL\fP, \fBALWAYS\fP }"
.br
.ti -1c
.RI "enum class \fBeAddress\fP { \fBWRAP\fP, \fBMIRROR\fP, \fBCLAMP\fP, \fBBORDER\fP, \fBMIRROR_ONCE\fP }"
.br
.ti -1c
.RI "enum class \fBeFilter\fP { \fBMIN_MAG_MIP_POINT\fP, \fBMIN_MAG_MIP_LINEAR\fP, \fBANISOTROPIC\fP }"
.br
.in -1c

Public Types inherited from \fBxpe::render::sResource\fP
.in +1c
.ti -1c
.RI "enum class \fBeViewType\fP { \fBNONE\fP, \fBDEPTH_STENCIL\fP, \fBRENDER_TARGET\fP, \fBSRV\fP, \fBUAV\fP }"
.br
.ti -1c
.RI "enum class \fBeMapType\fP { \fBREAD\fP, \fBWRITE\fP, \fBREAD_WRITE\fP, \fBWRITE_NO_OVERWRITE\fP, \fBWRITE_DISCARD\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsSampler\fP ()"
.br
.ti -1c
.RI "\fB~sSampler\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBInit\fP ()"
.br
.in -1c

Public Member Functions inherited from \fBxpe::core::cObject\fP
.in +1c
.ti -1c
.RI "\fBvoid\fP * \fBoperator new\fP (\fBusize\fP \fBbyteSize\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBoperator delete\fP (\fBvoid\fP *\fBaddress\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBu32\fP \fBSlot\fP = 0"
.br
.ti -1c
.RI "\fBeFilter\fP \fBFilter\fP = \fBeFilter::MIN_MAG_MIP_POINT\fP"
.br
.ti -1c
.RI "\fBf32\fP \fBMinLOD\fP = 0"
.br
.ti -1c
.RI "\fBf32\fP \fBMaxLOD\fP = \fBFLT_MAX\fP"
.br
.ti -1c
.RI "\fBf32\fP \fBMipLODBias\fP = 0"
.br
.ti -1c
.RI "\fBu32\fP \fBAnisotropyLevel\fP = 1"
.br
.ti -1c
.RI "glm::vec4 \fBBorderColor\fP = { 0, 0, 0, 0 }"
.br
.ti -1c
.RI "\fBeComparison\fP \fBComparison\fP = \fBeComparison::NEVER\fP"
.br
.ti -1c
.RI "\fBeAddress\fP \fBAddressU\fP = \fBeAddress::CLAMP\fP"
.br
.ti -1c
.RI "\fBeAddress\fP \fBAddressV\fP = \fBeAddress::CLAMP\fP"
.br
.ti -1c
.RI "\fBeAddress\fP \fBAddressW\fP = \fBeAddress::CLAMP\fP"
.br
.in -1c

Public Attributes inherited from \fBxpe::render::sResource\fP
.in +1c
.ti -1c
.RI "\fBvoid\fP * \fBInstance\fP = \fBnullptr\fP"
.br
.ti -1c
.RI "\fBvoid\fP * \fBViewInstance\fP = \fBnullptr\fP"
.br
.ti -1c
.RI "\fBeViewType\fP \fBViewType\fP = \fBeViewType::NONE\fP"
.br
.in -1c
.SH "Member Enumeration Documentation"
.PP 
.SS "\fBenum\fP \fBclass\fP \fBxpe::render::sSampler::eAddress\fP\fR [strong]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIWRAP \fP\fP
.TP
\fB\fIMIRROR \fP\fP
.TP
\fB\fICLAMP \fP\fP
.TP
\fB\fIBORDER \fP\fP
.TP
\fB\fIMIRROR_ONCE \fP\fP
.SS "\fBenum\fP \fBclass\fP \fBxpe::render::sSampler::eComparison\fP\fR [strong]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fINEVER \fP\fP
.TP
\fB\fILESS \fP\fP
.TP
\fB\fIEQUAL \fP\fP
.TP
\fB\fILESS_EQUAL \fP\fP
.TP
\fB\fIGREATER \fP\fP
.TP
\fB\fINOT_EQUAL \fP\fP
.TP
\fB\fIGREATER_EQUAL \fP\fP
.TP
\fB\fIALWAYS \fP\fP
.SS "\fBenum\fP \fBclass\fP \fBxpe::render::sSampler::eFilter\fP\fR [strong]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIMIN_MAG_MIP_POINT \fP\fP
.TP
\fB\fIMIN_MAG_MIP_LINEAR \fP\fP
.TP
\fB\fIANISOTROPIC \fP\fP
.SH "Constructor & Destructor Documentation"
.PP 
.SS "xpe::render::sSampler::sSampler ()"

.SS "xpe::render::sSampler::~sSampler ()"

.SH "Member Function Documentation"
.PP 
.SS "\fBvoid\fP xpe::render::sSampler::Init ()"

.SH "Member Data Documentation"
.PP 
.SS "\fBeAddress\fP xpe::render::sSampler::AddressU = \fBeAddress::CLAMP\fP"

.SS "\fBeAddress\fP xpe::render::sSampler::AddressV = \fBeAddress::CLAMP\fP"

.SS "\fBeAddress\fP xpe::render::sSampler::AddressW = \fBeAddress::CLAMP\fP"

.SS "\fBu32\fP xpe::render::sSampler::AnisotropyLevel = 1"

.SS "glm::vec4 xpe::render::sSampler::BorderColor = { 0, 0, 0, 0 }"

.SS "\fBeComparison\fP xpe::render::sSampler::Comparison = \fBeComparison::NEVER\fP"

.SS "\fBeFilter\fP xpe::render::sSampler::Filter = \fBeFilter::MIN_MAG_MIP_POINT\fP"

.SS "\fBf32\fP xpe::render::sSampler::MaxLOD = \fBFLT_MAX\fP"

.SS "\fBf32\fP xpe::render::sSampler::MinLOD = 0"

.SS "\fBf32\fP xpe::render::sSampler::MipLODBias = 0"

.SS "\fBu32\fP xpe::render::sSampler::Slot = 0"


.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
