.TH "xpe::render::sSsaoData" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xpe::render::sSsaoData
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <buffers\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBint\fP \fBDirectionCount\fP = 4"
.br
.ti -1c
.RI "\fBint\fP \fBSampleCount\fP = 4"
.br
.ti -1c
.RI "\fBfloat\fP \fBIntensity\fP = 1\&.0"
.br
.ti -1c
.RI "\fBfloat\fP \fB_pad0\fP = 0"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBfloat\fP xpe::render::sSsaoData::_pad0 = 0"

.SS "\fBint\fP xpe::render::sSsaoData::DirectionCount = 4"

.SS "\fBfloat\fP xpe::render::sSsaoData::Intensity = 1\&.0"

.SS "\fBint\fP xpe::render::sSsaoData::SampleCount = 4"


.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
