.TH "xpe::math::sModelMatrix" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xpe::math::sModelMatrix
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <matrices\&.hpp>\fP
.PP
Inherited by \fBxpe::math::sTransform\fP\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "glm::vec3 \fBPosition\fP = { 0, 0, 0 }"
.br
.ti -1c
.RI "glm::vec3 \fBRotation\fP = { 0, 0, 0 }"
.br
.ti -1c
.RI "glm::vec3 \fBScale\fP = { 1, 1, 1 }"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "glm::vec3 xpe::math::sModelMatrix::Position = { 0, 0, 0 }"

.SS "glm::vec3 xpe::math::sModelMatrix::Rotation = { 0, 0, 0 }"

.SS "glm::vec3 xpe::math::sModelMatrix::Scale = { 1, 1, 1 }"


.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
