.TH "xpe::core::sMemoryPoolAllocation" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xpe::core::sMemoryPoolAllocation
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <memory_manager\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBu8\fP \fBFreeFlag\fP = 0"
.br
.ti -1c
.RI "\fBu32\fP \fBAllocByteWidth\fP = 0"
.br
.ti -1c
.RI "\fBu32\fP \fBOccupiedByteWidth\fP = 0"
.br
.ti -1c
.RI "\fBvoid\fP * \fBAddress\fP = \fBnullptr\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBvoid\fP* xpe::core::sMemoryPoolAllocation::Address = \fBnullptr\fP"

.SS "\fBu32\fP xpe::core::sMemoryPoolAllocation::AllocByteWidth = 0"

.SS "\fBu8\fP xpe::core::sMemoryPoolAllocation::FreeFlag = 0"

.SS "\fBu32\fP xpe::core::sMemoryPoolAllocation::OccupiedByteWidth = 0"


.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
