.TH "xpe::physics::cPhysicsAllocator" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xpe::physics::cPhysicsAllocator
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <allocators\&.hpp>\fP
.PP
Inherits physx::PxAllocatorCallback\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB~cPhysicsAllocator\fP () \fBoverride\fP"
.br
.ti -1c
.RI "\fBvoid\fP * \fBallocate\fP (\fBsize_t\fP \fBsize\fP, \fBconst\fP \fBchar\fP *\fBtypeName\fP, \fBconst\fP \fBchar\fP *\fBfilename\fP, \fBint\fP \fBline\fP) \fBoverride\fP"
.br
.ti -1c
.RI "\fBvoid\fP \fBdeallocate\fP (\fBvoid\fP *\fBptr\fP) \fBoverride\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "xpe::physics::cPhysicsAllocator::~cPhysicsAllocator ()\fR [override]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBvoid\fP * xpe::physics::cPhysicsAllocator::allocate (\fBsize_t\fP size, \fBconst\fP \fBchar\fP * typeName, \fBconst\fP \fBchar\fP * filename, \fBint\fP line)\fR [override]\fP"

.SS "\fBvoid\fP xpe::physics::cPhysicsAllocator::deallocate (\fBvoid\fP * ptr)\fR [override]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
