.TH "xpe::render::sChar" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xpe::render::sChar
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <buffers\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBu32\fP \fBTextIndex\fP = 0"
.br
.ti -1c
.RI "\fBf32\fP \fBGlyphSize\fP = 0"
.br
.ti -1c
.RI "\fBf32\fP \fBWidth\fP = 0"
.br
.ti -1c
.RI "\fBf32\fP \fBHeight\fP = 0"
.br
.ti -1c
.RI "\fBf32\fP \fBLeft\fP = 0"
.br
.ti -1c
.RI "\fBf32\fP \fBTop\fP = 0"
.br
.ti -1c
.RI "\fBf32\fP \fBAdvanceX\fP = 0"
.br
.ti -1c
.RI "\fBf32\fP \fBAdvanceY\fP = 0"
.br
.ti -1c
.RI "\fBf32\fP \fBAtlasXOffset\fP = 0"
.br
.ti -1c
.RI "\fBf32\fP \fBAtlasYOffset\fP = 0"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBf32\fP xpe::render::sChar::AdvanceX = 0"

.SS "\fBf32\fP xpe::render::sChar::AdvanceY = 0"

.SS "\fBf32\fP xpe::render::sChar::AtlasXOffset = 0"

.SS "\fBf32\fP xpe::render::sChar::AtlasYOffset = 0"

.SS "\fBf32\fP xpe::render::sChar::GlyphSize = 0"

.SS "\fBf32\fP xpe::render::sChar::Height = 0"

.SS "\fBf32\fP xpe::render::sChar::Left = 0"

.SS "\fBu32\fP xpe::render::sChar::TextIndex = 0"

.SS "\fBf32\fP xpe::render::sChar::Top = 0"

.SS "\fBf32\fP xpe::render::sChar::Width = 0"


.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
