.TH "xpe::math::sRay" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xpe::math::sRay
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <ray\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "glm::vec4 \fBOrigin\fP = { 0, 0, 0, 1 }"
.br
.ti -1c
.RI "glm::vec4 \fBDirection\fP = { 0, 0, 0, 1 }"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "glm::vec4 xpe::math::sRay::Direction = { 0, 0, 0, 1 }"

.SS "glm::vec4 xpe::math::sRay::Origin = { 0, 0, 0, 1 }"


.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
