.TH "xpe::ecs::CLabel" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xpe::ecs::CLabel
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <components\&.hpp>\fP
.PP
Inherits \fBxpe::render::sWidget\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCLabel\fP (\fBsFont\fP *\fBfont\fP, \fBconst\fP \fBstring\fP &\fBtext\fP='', \fBconst\fP glm::vec4 &\fBcolor\fP={ 1, 1, 1, 1 })"
.br
.in -1c

Public Member Functions inherited from \fBxpe::res::cXml\fP
.in +1c
.ti -1c
.RI "\fBvirtual\fP \fBxml\fP \fBToXml\fP (\fBxml\fP &\fBroot\fP)=0"
.br
.ti -1c
.RI "\fBvirtual\fP \fBxml\fP \fBFromXml\fP (\fBxml\fP &\fBroot\fP)=0"
.br
.ti -1c
.RI "\fBbool\fP \fBLoadFile\fP (\fBconst\fP \fBchar\fP *\fBfilepath\fP)"
.br
.ti -1c
.RI "\fBbool\fP \fBSaveFile\fP (\fBconst\fP \fBchar\fP *\fBfilepath\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBsFont\fP * \fBFont\fP = \fBnullptr\fP"
.br
.ti -1c
.RI "\fBstring\fP \fBText\fP"
.br
.ti -1c
.RI "glm::vec4 \fBColor\fP = { 1, 1, 1, 1 }"
.br
.ti -1c
.RI "\fBbool\fP \fBFillFrame\fP = \fBtrue\fP"
.br
.in -1c

Public Attributes inherited from \fBxpe::render::sWidget\fP
.in +1c
.ti -1c
.RI "glm::mat4 \fBProjection\fP = glm::mat4(1)"
.br
.in -1c

Public Attributes inherited from \fBxpe::res::cXml\fP
.in +1c
.ti -1c
.RI "\fBxpe::core::vector\fP< \fBcXml\fP * > \fBXmlChildren\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Protected Attributes inherited from \fBxpe::res::cXml\fP
.in +1c
.ti -1c
.RI "pugi::xml_document \fBm_Doc\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "xpe::ecs::CLabel::CLabel (\fBsFont\fP * font, \fBconst\fP \fBstring\fP & text = \fR''\fP, \fBconst\fP glm::vec4 & color = \fR{ 1, 1, 1, 1 }\fP)\fR [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "glm::vec4 xpe::ecs::CLabel::Color = { 1, 1, 1, 1 }"

.SS "\fBbool\fP xpe::ecs::CLabel::FillFrame = \fBtrue\fP"

.SS "\fBsFont\fP* xpe::ecs::CLabel::Font = \fBnullptr\fP"

.SS "\fBstring\fP xpe::ecs::CLabel::Text"


.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
