.TH "xpe::render::sShadowPcf" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xpe::render::sShadowPcf
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <buffers\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBint\fP \fBFilterSize\fP = 0"
.br
.ti -1c
.RI "\fBfloat\fP \fBMinBias\fP = 0\&.005\fBf\fP"
.br
.ti -1c
.RI "\fBfloat\fP \fBMaxBias\fP = 0\&.05\fBf\fP"
.br
.ti -1c
.RI "\fBfloat\fP \fB_pad0\fP = 0"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBfloat\fP xpe::render::sShadowPcf::_pad0 = 0"

.SS "\fBint\fP xpe::render::sShadowPcf::FilterSize = 0"

.SS "\fBfloat\fP xpe::render::sShadowPcf::MaxBias = 0\&.05\fBf\fP"

.SS "\fBfloat\fP xpe::render::sShadowPcf::MinBias = 0\&.005\fBf\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
