.TH "xpe::ecs::CTag" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xpe::ecs::CTag
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <components\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCTag\fP (\fBconst\fP \fBstring\fP &\fBtag\fP={})"
.br
.ti -1c
.RI "\fBCTag\fP (\fBstring\fP &&\fBtag\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBstring\fP \fBTag\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "xpe::ecs::CTag::CTag (\fBconst\fP \fBstring\fP & tag = \fR{}\fP)\fR [inline]\fP"

.SS "xpe::ecs::CTag::CTag (\fBstring\fP && tag)\fR [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBstring\fP xpe::ecs::CTag::Tag"


.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
