.TH "xpe::physics::sSphereShapeDescriptor" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xpe::physics::sSphereShapeDescriptor
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <physics_manager\&.hpp>\fP
.PP
Inherits sShapeDescriptor\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsSphereShapeDescriptor\fP ()=\fBdelete\fP"
.br
.ti -1c
.RI "\fBsSphereShapeDescriptor\fP (\fBf32\fP \fBradius\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBf32\fP \fBRadius\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "xpe::physics::sSphereShapeDescriptor::sSphereShapeDescriptor ()\fR [delete]\fP"

.SS "xpe::physics::sSphereShapeDescriptor::sSphereShapeDescriptor (\fBf32\fP radius)\fR [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBf32\fP xpe::physics::sSphereShapeDescriptor::Radius"


.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
