.TH "xpe::ecs::CVisible" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xpe::ecs::CVisible
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <components\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBbool\fP \fBVisible\fP = \fBtrue\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBbool\fP xpe::ecs::CVisible::Visible = \fBtrue\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
