.TH "xpe::ecs::CButton" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xpe::ecs::CButton
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <components\&.hpp>\fP
.PP
Inherits \fBxpe::render::sWidget\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "\fBtypedef\fP \fBvoid\fP(* \fBfHovered\fP) ()"
.br
.ti -1c
.RI "\fBtypedef\fP \fBvoid\fP(* \fBfPressed\fP) ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "glm::vec4 \fBColor\fP = { 1, 1, 1, 1 }"
.br
.ti -1c
.RI "glm::vec4 \fBColorHover\fP = { 0\&.5, 0\&.5, 0\&.5, 1\&.0 }"
.br
.ti -1c
.RI "glm::vec4 \fBColorPressed\fP = { 0\&.25, 0\&.25, 0\&.25, 1\&.0 }"
.br
.ti -1c
.RI "\fBbool\fP \fBEnableTexture\fP = \fBfalse\fP"
.br
.ti -1c
.RI "\fBsAtlas::sLocation\fP \fBAtlasLocation\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBEnablePress\fP = \fBtrue\fP"
.br
.ti -1c
.RI "\fBeMouse\fP \fBMousePressed\fP = eMouse::ButtonLeft"
.br
.ti -1c
.RI "\fBbool\fP \fBFillFrame\fP = \fBtrue\fP"
.br
.ti -1c
.RI "\fBfHovered\fP \fBHovered\fP = \fBnullptr\fP"
.br
.ti -1c
.RI "\fBfPressed\fP \fBPressed\fP = \fBnullptr\fP"
.br
.in -1c

Public Attributes inherited from \fBxpe::render::sWidget\fP
.in +1c
.ti -1c
.RI "glm::mat4 \fBProjection\fP = glm::mat4(1)"
.br
.in -1c

Public Attributes inherited from \fBxpe::res::cXml\fP
.in +1c
.ti -1c
.RI "\fBxpe::core::vector\fP< \fBcXml\fP * > \fBXmlChildren\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Public Member Functions inherited from \fBxpe::res::cXml\fP
.in +1c
.ti -1c
.RI "\fBvirtual\fP \fBxml\fP \fBToXml\fP (\fBxml\fP &\fBroot\fP)=0"
.br
.ti -1c
.RI "\fBvirtual\fP \fBxml\fP \fBFromXml\fP (\fBxml\fP &\fBroot\fP)=0"
.br
.ti -1c
.RI "\fBbool\fP \fBLoadFile\fP (\fBconst\fP \fBchar\fP *\fBfilepath\fP)"
.br
.ti -1c
.RI "\fBbool\fP \fBSaveFile\fP (\fBconst\fP \fBchar\fP *\fBfilepath\fP)"
.br
.in -1c

Protected Attributes inherited from \fBxpe::res::cXml\fP
.in +1c
.ti -1c
.RI "pugi::xml_document \fBm_Doc\fP"
.br
.in -1c
.SH "Member Typedef Documentation"
.PP 
.SS "\fBtypedef\fP \fBvoid\fP(* xpe::ecs::CButton::fHovered) ()"

.SS "\fBtypedef\fP \fBvoid\fP(* xpe::ecs::CButton::fPressed) ()"

.SH "Member Data Documentation"
.PP 
.SS "\fBsAtlas::sLocation\fP xpe::ecs::CButton::AtlasLocation"

.SS "glm::vec4 xpe::ecs::CButton::Color = { 1, 1, 1, 1 }"

.SS "glm::vec4 xpe::ecs::CButton::ColorHover = { 0\&.5, 0\&.5, 0\&.5, 1\&.0 }"

.SS "glm::vec4 xpe::ecs::CButton::ColorPressed = { 0\&.25, 0\&.25, 0\&.25, 1\&.0 }"

.SS "\fBbool\fP xpe::ecs::CButton::EnablePress = \fBtrue\fP"

.SS "\fBbool\fP xpe::ecs::CButton::EnableTexture = \fBfalse\fP"

.SS "\fBbool\fP xpe::ecs::CButton::FillFrame = \fBtrue\fP"

.SS "\fBfHovered\fP xpe::ecs::CButton::Hovered = \fBnullptr\fP"

.SS "\fBeMouse\fP xpe::ecs::CButton::MousePressed = eMouse::ButtonLeft"

.SS "\fBfPressed\fP xpe::ecs::CButton::Pressed = \fBnullptr\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
