.TH "xpe::render::sPointLightData" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xpe::render::sPointLightData
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <buffers\&.hpp>\fP
.PP
Inherited by \fBxpe::ecs::CPointLight\fP\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "glm::vec3 \fBPosition\fP = { 0, 0, 0 }"
.br
.ti -1c
.RI "glm::vec3 \fBColor\fP = { 1, 1, 1 }"
.br
.ti -1c
.RI "\fBfloat\fP \fBConstant\fP = 1\&.0f"
.br
.ti -1c
.RI "\fBfloat\fP \fBLinear\fP = 0\&.09\fBf\fP"
.br
.ti -1c
.RI "\fBfloat\fP \fBQuadratic\fP = 0\&.032\fBf\fP"
.br
.ti -1c
.RI "glm::mat4 \fBViewProjection\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "glm::vec3 xpe::render::sPointLightData::Color = { 1, 1, 1 }"

.SS "\fBfloat\fP xpe::render::sPointLightData::Constant = 1\&.0f"

.SS "\fBfloat\fP xpe::render::sPointLightData::Linear = 0\&.09\fBf\fP"

.SS "glm::vec3 xpe::render::sPointLightData::Position = { 0, 0, 0 }"

.SS "\fBfloat\fP xpe::render::sPointLightData::Quadratic = 0\&.032\fBf\fP"

.SS "glm::mat4 xpe::render::sPointLightData::ViewProjection"


.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
