.TH "xpe::audio::sAudioFile" 3 "Version 0.1" "XPE-Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xpe::audio::sAudioFile
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <sndfile_context\&.hpp>\fP
.PP
Inherits \fBxpe::core::cObject\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsAudioFile\fP ()=\fBdefault\fP"
.br
.ti -1c
.RI "\fB~sAudioFile\fP ()"
.br
.in -1c

Public Member Functions inherited from \fBxpe::core::cObject\fP
.in +1c
.ti -1c
.RI "\fBvoid\fP * \fBoperator new\fP (\fBusize\fP \fBbyteSize\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBoperator delete\fP (\fBvoid\fP *\fBaddress\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBSNDFILE\fP * \fBFile\fP = \fBnullptr\fP"
.br
.ti -1c
.RI "\fBSF_INFO\fP \fBInfo\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "xpe::audio::sAudioFile::sAudioFile ()\fR [default]\fP"

.SS "xpe::audio::sAudioFile::~sAudioFile ()"

.SH "Member Data Documentation"
.PP 
.SS "\fBSNDFILE\fP* xpe::audio::sAudioFile::File = \fBnullptr\fP"

.SS "\fBSF_INFO\fP xpe::audio::sAudioFile::Info"


.SH "Author"
.PP 
Generated automatically by Doxygen for XPE-Engine from the source code\&.
